Repository eclipse-ee4j/glassfish, pull requests merged in 2021-10, with the labels that each got.

#23645 Update website for 6.2.2 release
  docs/website/src/main/resources/README.md
  docs/website/src/main/resources/download.md
Labels: Documentation

#23643 Fix #23642 CLI031 is printed out when execute list-resource-adapter-configs command
  appserver/connectors/admin/src/main/java/org/glassfish/connectors/admin/cli/ListResourceAdapterConfigs.java
Labels: bug

#23648 Fix #23647 Displayed clusters page instead of instance general page when click the instance name on configurations page
  appserver/admingui/common/src/main/resources/configuration/configurations.jsf
Labels: enhancement

#23649 Fix #23646 White page is displayed when click "Reload" on the application deployment page.
  appserver/admingui/common/src/main/resources/applications/deployTable.inc
  appserver/admingui/common/src/main/resources/applications/deployTableButtons.inc
Labels: bug
