Repository eclipse-ee4j/glassfish, pull requests merged in 2021-12, with the labels that each got.

#23730 Exclude jaxb as a transitive dependency
  appserver/admingui/common/pom.xml
  appserver/admingui/jackson-jaxb/pom.xml
  appserver/ejb/ejb-container/src/test/java/com/sun/ejb/EJBUtilsTest.java
  nucleus/parent/pom.xml
Labels: build and test improvement

#23736 Issue #23734 Using X509Certificate in java.security instead of javax.security
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/ssl/JSSESupport.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/ssl/GlassfishSSLSupport.java
Labels: bug, deprecation

#23737 Jersey ejb component provider for 6.x
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/BaseContainer.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/InternalInterceptorBindingNamingProxy.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/interceptors/InterceptorManager.java
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/shell/glassfish-embedded-static-shell/pom.xml
  appserver/extras/embedded/web/pom.xml
  appserver/featuresets/web/pom.xml
  appserver/web/jersey-ejb-component-provider/pom.xml
  appserver/web/jersey-ejb-component-provider/src/main/java/org/glassfish/jersey/gf/ejb/internal/EjbClassUtilities.java
  appserver/web/jersey-ejb-component-provider/src/main/java/org/glassfish/jersey/gf/ejb/internal/EjbComponentInterceptor.java
  appserver/web/jersey-ejb-component-provider/src/main/java/org/glassfish/jersey/gf/ejb/internal/EjbComponentProvider.java
  appserver/web/jersey-ejb-component-provider/src/main/java/org/glassfish/jersey/gf/ejb/internal/EjbExceptionMapper.java
  appserver/web/jersey-ejb-component-provider/src/main/java/org/glassfish/jersey/gf/ejb/internal/EjbSupplier.java
  appserver/web/jersey-ejb-component-provider/src/main/java/org/glassfish/jersey/gf/ejb/internal/package-info.java
  appserver/web/jersey-ejb-component-provider/src/main/resources/META-INF/services/org.glassfish.jersey.server.spi.ComponentProvider
  appserver/web/pom.xml
  nucleus/admin/rest/rest-service/osgi.bundle
  nucleus/admin/rest/rest-service/pom.xml
Labels: deprecation

#23751 No TCK on profile oss-release
  appserver/tests/pom.xml
Labels: ci-pipeline, build and test improvement

#23752 Add new property for logging Print Once
  appserver/admingui/concurrent/src/main/help/en/help/ref-executorserviceedit.html
  appserver/admingui/concurrent/src/main/help/en/help/ref-executorservicenew.html
  appserver/admingui/concurrent/src/main/help/en/help/ref-scheduledexecutorserviceedit.html
  appserver/admingui/concurrent/src/main/help/en/help/ref-scheduledexecutorservicenew.html
  appserver/admingui/concurrent/src/main/resources/managedExecutorServiceAttr.inc
  appserver/admingui/concurrent/src/main/resources/managedExecutorServiceEdit.jsf
  appserver/admingui/concurrent/src/main/resources/managedExecutorServiceNew.jsf
  appserver/admingui/concurrent/src/main/resources/managedScheduledExecutorServiceEdit.jsf
  appserver/admingui/concurrent/src/main/resources/managedScheduledExecutorServiceNew.jsf
  appserver/admingui/concurrent/src/main/resources/org/glassfish/concurrent/admingui/Strings.properties
  appserver/concurrent/concurrent-connector/src/main/java/org/glassfish/concurrent/config/ManagedExecutorServiceBase.java
  appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/admin/CreateManagedExecutorServiceBase.java
  appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/admin/ManagedExecutorServiceBaseManager.java
  appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ConcurrentRuntime.java
  appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ManagedExecutorServiceConfig.java
  appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/deployer/ManagedScheduledExecutorServiceConfig.java
  appserver/concurrent/concurrent-impl/src/main/manpages/org/glassfish/concurrent/admin/create-managed-executor-service.1
  appserver/concurrent/concurrent-impl/src/main/manpages/org/glassfish/concurrent/admin/create-managed-scheduled-executor-service.1
  appserver/resources/resources-connector/src/main/java/org/glassfish/resources/admin/cli/ResourceConstants.java
  docs/reference-manual/src/main/asciidoc/create-managed-executor-service.adoc
  docs/reference-manual/src/main/asciidoc/create-managed-scheduled-executor-service.adoc
Labels: New feature
