Repository eclipse-ee4j/glassfish, pull requests merged in 2021-09, with the labels that each got.

#23579 Fix #23578 Cannot enbale Security Manager from the admin console
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/SecurityHandler.java
Labels: bug

#23584 Fix #23580 Refer to parameter-encoding only if charset is not specified.
  appserver/web/web-core/src/main/java/org/apache/catalina/connector/Request.java
Labels: bug

#23583 Fix #23582, local packaged file is deleted when push redeploy button from the web console
  appserver/admingui/common/src/main/resources/applications/redeployFrame.jsf
Labels: bug

#23600 Fixed error message - wrong brace
  nucleus/admin/config-api/src/main/java/org/glassfish/config/support/DefaultConfigUpgrade.java
  nucleus/admin/config-api/src/main/java/org/glassfish/config/support/LocalStrings.properties
Labels: bug

#23604 Integrate Tyrus 2.0.1
  appserver/pom.xml
Labels: component upgrade

#23609 Fix #23608 Add properties file to resources-runtime
  appserver/resources/resources-runtime/src/main/java/com/sun/logging/enterprise/resource/resourceadapter/LogStrings.properties
  appserver/resources/resources-runtime/src/main/java/org/glassfish/resources/module/LocalStrings.properties
Labels: bug

#23618 Integrate Jersey 3.0.3
  nucleus/parent/pom.xml
Labels: component upgrade

#23613 #23612 Add export for LDAP to allow identity store to work
  appserver/admin/template/src/main/resources/config/domain.xml
  appserver/resources/resources-connector/src/test/resources/DomainTest.xml
  nucleus/admin/template/src/main/resources/config/domain.xml
  nucleus/core/kernel/src/test/resources/DomainTest.xml
Labels: bug

#23623 Remove unused variables
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/ApplicationHandlers.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/AbstractSingletonContainer.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/StatelessSessionContainer.java
  appserver/persistence/cmp/enhancer/src/main/java/com/sun/jdo/api/persistence/enhancer/generator/Main.java
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/perms/SMGlobalPolicyUtil.java
  appserver/transaction/jts/src/main/java/com/sun/jts/jta/TransactionManagerImpl.java
  nucleus/flashlight/framework/src/main/java/org/glassfish/flashlight/impl/provider/FlashlightProbeProviderFactory.java
Labels: code cleaning

#23624 Remove unused class
  nucleus/flashlight/framework/src/main/java/org/glassfish/flashlight/impl/core/ProbeClientAnnotationHandlerManager.java
Labels: code cleaning

#23625 Remove unused variables
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/CommandRunnerImpl.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java
Labels: code cleaning

#23626 Separate words in logged messages
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/deployment/annotation/handlers/AdministeredObjectDefinitionHandler.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/cli/UpdateFileUser.java
Labels: bug

#23617 PR for #23615 Professional Services Section to README.md, Update Download Page for 6.2.1
  README.md
  docs/website/src/main/resources/README.md
  docs/website/src/main/resources/download.md
Labels: Documentation

#23630 Started cleaning / refactoring of RealmAdapter and some related code
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/auth/digest/impl/HttpDigestParamGenerator.java
  appserver/security/webintegration/src/main/java/com/sun/web/security/RealmAdapter.java
  appserver/web/war-util/src/main/resources/com/sun/logging/enterprise/system/container/web/LogStrings.properties
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/Utility.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/digest/api/Key.java
Labels: code cleaning

#23631 Integrate Grizzly 3.0.1
  nucleus/parent/pom.xml
Labels: component upgrade

#23636 Fix #23634 Change @ExecuteOn targets for some of security commands.
  nucleus/security/core/src/main/java/com/sun/enterprise/security/cli/CreateFileUser.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/cli/DeleteFileUser.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/cli/UpdateFileUser.java
Labels: bug

#23635 Fix #23633 Message do not print properly when iiop listener port changed to invalid value
  appserver/orb/orb-enabler/pom.xml
  appserver/orb/orb-enabler/src/main/java/org/glassfish/orb/admin/config/LocalStrings.properties
Labels: bug

#23639 Fixed references to validation.jar to correct jakarta.validation-api.jar
  appserver/admin/template/src/main/resources/config/default-web.xml
  appserver/extras/javaee/manifest-jar/pom.xml
Labels: bug

#23640 Issue 23632 embedded is able to again
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/all/src/assembly/jdbcra-cp.xml
  appserver/extras/embedded/all/src/assembly/jdbcra-dm.xml
  appserver/extras/embedded/all/src/assembly/jdbcra-ds.xml
  appserver/extras/embedded/all/src/assembly/jdbcra-xa.xml
  appserver/extras/embedded/all/src/assembly/jmsra.xml
  appserver/extras/embedded/all/src/assembly/package.xml
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/JarUtil.java
Labels: bug, build and test improvement
