Repository eclipse-ee4j/glassfish, pull requests merged in 2021-11, with the labels that each got.

#23683 23674 cdi deployment failure null
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/DeploymentImpl.java
Labels: bug

#23685 Fix #23684 Config file for client JNLP not found when deploy application client
  appserver/distributions/glassfish/src/main/assembly/glassfish.xml
Labels: bug

#23687 Fix #23686 Unable to avoid creating an instance with the same name as a cluster
  nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/customvalidators/NotDuplicateTargetNameValidator.java
Labels: bug

#23689 Fix #23688 Change description on the JNDI External Resource page
  appserver/admingui/full/src/main/resources/customResourceEdit.jsf
  appserver/admingui/full/src/main/resources/customResourceNew.jsf
  appserver/admingui/full/src/main/resources/externalResourceEdit.jsf
  appserver/admingui/full/src/main/resources/externalResourceNew.jsf
  appserver/admingui/full/src/main/resources/jndiResourceAttr.inc
  appserver/admingui/full/src/main/resources/org/glassfish/full/admingui/Strings.properties
Labels: bug

#23691 Fix #23690 Wrong message is printed when setting an invalid hostname as an address of the IIOP listener
  nucleus/core/kernel/pom.xml
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/GrizzlyProxy.java
  nucleus/core/kernel/src/test/java/com/sun/enterprise/v3/services/impl/GrizzlyProxyTest.java
Labels: bug

#23693 Fix #21841 Setting non-integer value to a config bean attribute with @Min or @Max and without dataType=Integer.class locks the config bean
  appserver/jdbc/jdbc-config/src/main/java/org/glassfish/jdbc/config/JdbcConnectionPool.java
Labels: bug

#23697 Adding source for the javatest artefact.
  appserver/tests/tck/tck-download/javatest/pom.xml
  appserver/tests/tck/tck-download/javatest/src/assembly/sources.xml
Labels: build and test improvement

#23701 Fix #23700 Add properties file to ejb-full-container
  appserver/ejb/ejb-full-container/src/main/resources/com/sun/logging/enterprise/system/container/ejb/LogStrings.properties
Labels: bug

#23702 Jenkins related changes
  Jenkinsfile
  appserver/tests/appserv-tests/config.properties
  appserver/tests/appserv-tests/devtests/cdi/run_test.sh
  appserver/tests/tck/authorization/pom.xml
  runtests.sh
Labels: ci-pipeline, build and test improvement

#23704 Fix #23703 Unable to avoid creating a JDBC Connection Pool with the Datasource Classname whose length is over 512
  appserver/admingui/jdbc/src/main/resources/poolPropertyNew.inc
Labels: bug

#23707 Fix #23706 Add validation about CorePoolSize, MaxPoolSize and KeepAliveSeconds.
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EjbContainerUtilImpl.java
  appserver/ejb/ejb-container/src/test/java/com/sun/ejb/containers/EjbContainerUtilImplTest.java
Labels: bug

#23710 Fix #23708 Unable to remove an instance's system property override value on the web console.
  appserver/admingui/common/src/main/resources/configuration/sysInstanceValues.jsf
Labels: bug

#23712 Fix for classpath names for new jdbc-ra-distribution
  appserver/appclient/client/acc-standalone/pom.xml
Labels: bug

#23695 Integrate Activation+Mail API 2.1.0-RC2 + Angus-Activation+Mail 1.0.0-M1
  appserver/admin/template/src/main/resources/config/default-web.xml
  appserver/appclient/client/acc/pom.xml
  appserver/common/container-common/pom.xml
  appserver/core/api-exporter-fragment/pom.xml
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/web/pom.xml
  appserver/extras/javaee/manifest-jar/pom.xml
  appserver/featuresets/glassfish/pom.xml
  appserver/featuresets/web/pom.xml
  appserver/pom.xml
  appserver/resources/mail/mail-runtime/pom.xml
  appserver/resources/mail/pom.xml
  appserver/tests/quicklook/gfproject/build-impl.xml
  appserver/web/web-naming/pom.xml
  appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/monitoring/WebServiceTesterServlet.java
  appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/schemagen
  appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/schemagen.bat
  appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsgen
  appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsgen.bat
  appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsimport
  appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsimport.bat
  appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/xjc
  appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/xjc.bat
  nucleus/admin/cli/pom.xml
  nucleus/featuresets/atomic/pom.xml
  nucleus/parent/pom.xml
Labels: ee10-component

#23719 Round 2 of basic cleaning for JTA code
  appserver/transaction/jts/pom.xml
  appserver/transaction/jts/src/main/java/com/sun/enterprise/transaction/jts/JavaEETransactionManagerJTSDelegate.java
  appserver/transaction/jts/src/main/java/com/sun/enterprise/transaction/jts/ResourceRecoveryManagerImpl.java
  appserver/transaction/jts/src/main/java/com/sun/enterprise/transaction/jts/api/DelegatedTransactionRecoveryFence.java
  appserver/transaction/jts/src/main/java/com/sun/enterprise/transaction/jts/api/TransactionRecoveryFence.java
  appserver/transaction/jts/src/main/java/com/sun/enterprise/transaction/jts/iiop/TransactionClientInterceptor.java
  appserver/transaction/jts/src/main/java/com/sun/enterprise/transaction/jts/iiop/TransactionIIOPInterceptorFactory.java
  appserver/transaction/jts/src/main/java/com/sun/enterprise/transaction/jts/iiop/TransactionInterceptorFactory.java
  appserver/transaction/jts/src/main/java/com/sun/enterprise/transaction/jts/iiop/TransactionServerInterceptor.java
  appserver/transaction/jts/src/main/java/com/sun/enterprise/transaction/jts/iiop/TxIORInterceptor.java
  appserver/transaction/jts/src/main/java/com/sun/enterprise/transaction/jts/recovery/GMSCallBack.java
  appserver/transaction/jts/src/main/java/com/sun/enterprise/transaction/jts/recovery/OracleXAResource.java
  appserver/transaction/jts/src/main/java/com/sun/enterprise/transaction/jts/recovery/RecoveryLockFile.java
  appserver/transaction/jts/src/main/java/com/sun/enterprise/transaction/jts/recovery/SybaseXAResource.java
Labels: code cleaning

#23720 Cleaning of code in the CLI optional package (mostly DB commands)
  appserver/admin/cli-optional/src/main/java/com/sun/enterprise/admin/cli/optional/BackupCommands.java
  appserver/admin/cli-optional/src/main/java/com/sun/enterprise/admin/cli/optional/BackupDomainCommand.java
  appserver/admin/cli-optional/src/main/java/com/sun/enterprise/admin/cli/optional/DatabaseCommand.java
  appserver/admin/cli-optional/src/main/java/com/sun/enterprise/admin/cli/optional/DerbyControl.java
  appserver/admin/cli-optional/src/main/java/com/sun/enterprise/admin/cli/optional/ListBackupsCommand.java
  appserver/admin/cli-optional/src/main/java/com/sun/enterprise/admin/cli/optional/RestoreDomainCommand.java
  appserver/admin/cli-optional/src/main/java/com/sun/enterprise/admin/cli/optional/StartDatabaseCommand.java
  appserver/admin/cli-optional/src/main/java/com/sun/enterprise/admin/cli/optional/StopDatabaseCommand.java
Labels: code cleaning

#23723 #23722 Allow Derby to start on JDK 18
  appserver/admin/cli-optional/src/main/java/com/sun/enterprise/admin/cli/optional/DerbyControl.java
Labels: bug

#23725 Integrate eclipselink.asm 9.2.0, for JDK 18 compatibility
  appserver/pom.xml
Labels: component upgrade
