Repository eclipse-ee4j/glassfish, pull requests merged in 2022-09, with the labels that each got.

#24100 Integrate EclipseLink 4.0.0-RC1
  appserver/pom.xml
Labels: component upgrade, ee10-component

#24107 Update various component versions in pom
  appserver/pom.xml
  nucleus/parent/pom.xml
Labels: component upgrade, ee10-component

#24109 Update MVC/Krazo to final
  appserver/pom.xml
Labels: component upgrade

#24110 Update pom for REST TCK to latest EE 10 version
  appserver/tests/tck/rest/pom.xml
  appserver/tests/tck/rest/src/test/resources/j2ee.pass
  appserver/tests/tck/rest/src/test/resources/javajoe.pass
  appserver/tests/tck/tck-download/jakarta-rest-tck/pom.xml
Labels: ee10-tck

#24111 Update Nimbus to 9.25, javassist to 3.29.2, webconsole to 4.8.4
  appserver/pom.xml
  nucleus/parent/pom.xml
Labels: component upgrade

#24112 Fixes and updates based on playing with external Jenkins builds with TCK
  appserver/tests/tck/faces/pom.xml
  appserver/tests/tck/tck-download/jakarta-faces-tck/pom.xml
  appserver/tests/tck/tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/tests/EjbITest.java
  appserver/tests/tck/tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/tests/ServletITest.java
  appserver/tests/tck/tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/tests/WebsocketITest.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/handler/LogCollectorHandler.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/handler/LoggingPrintStream.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/handler/LoggingPrintStreamTest.java
Labels: build and test improvement

#24113 Fixes for the TCK
  appserver/common/annotation-framework/src/main/java/org/glassfish/apf/impl/ComponentDefinition.java
  appserver/tests/tck/tck-runner/pom.xml
  appserver/tests/tck/tck-runner/src/main/java/org/glassfish/main/tests/tck/ant/TckRunner.java
  appserver/tests/tck/tck-runner/src/main/java/org/glassfish/main/tests/tck/ant/xml/TimestampAdapter.java
  appserver/tests/tck/tck-runner/src/main/resources/junit-results.xjb
  appserver/tests/tck/tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/xml/TimestampAdapterTest.java
Labels: bug

#24114 Fixed remaining tz tests
  appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/descriptor/ScheduledTimerDescriptor.java
  appserver/tests/tck/tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/tests/CustomITest.java
Labels: bug
