Repository eclipse-ee4j/glassfish, pull requests merged in 2022-03, with the labels that each got.

#23839 Integrate Authentication 3.0.0-RC2
  appserver/pom.xml
  appserver/security/jaspic-provider-framework/src/main/java/com/sun/jaspic/config/factory/BaseAuthConfigFactory.java
  appserver/security/jaspic-provider-framework/src/test/java/test/com/sun/jaspic/config/FactoryTest.java
Labels: component upgrade, ee10-component

#23840 Bump OpenMQ version
  appserver/pom.xml
Labels: component upgrade, ee10-component

#23841 Implementation of new Jakarta Authentication methods
  appserver/security/jaspic-provider-framework/src/main/java/com/sun/jaspic/config/factory/BaseAuthConfigFactory.java
  appserver/security/jaspic-provider-framework/src/main/java/com/sun/jaspic/config/factory/singlemodule/DefaultAuthConfigProvider.java
  appserver/security/jaspic-provider-framework/src/main/java/com/sun/jaspic/config/factory/singlemodule/DefaultServerAuthConfig.java
  appserver/security/jaspic-provider-framework/src/main/java/com/sun/jaspic/config/factory/singlemodule/DefaultServerAuthContext.java
  appserver/security/jaspic-provider-framework/src/test/java/test/com/sun/jaspic/config/FactoryTest.java
Labels: ee10-component

#23844 Integrate Jakarta Security 3.0.0-RC1
  appserver/featuresets/debug/pom.xml
  appserver/featuresets/web/pom.xml
  appserver/pom.xml
Labels: component upgrade, ee10-component

#23846 Restore JSON support for REST
  appserver/featuresets/web/pom.xml
  appserver/pom.xml
Labels: bug

#23847 Update Jakarta Tags API & IMPL to 3.0.0
  appserver/pom.xml
Labels: component upgrade, ee10-component

#23848 Integrate Soteria 3.0.0-M2
  appserver/pom.xml
Labels: component upgrade, ee10-component

#23849 Integrate Jakarta Authentication 3.0.0
  appserver/pom.xml
Labels: component upgrade, ee10-component

#23850 Integrate Jakarta Authorization 2.1.0
  appserver/pom.xml
Labels: component upgrade, ee10-component

#23858 Integrate Jakarta Security 3.0.0-RC3/Soteria M4
  appserver/pom.xml
Labels: component upgrade, ee10-component

#23859 Integrate Tyrus 2.1.0-M2
  appserver/pom.xml
Labels: component upgrade, ee10-component

#23860 Integrate Eclipse Link 4.0.0-M3
  appserver/pom.xml
Labels: component upgrade, ee10-component

#23863 Integrate jaxb-impl 4.0.0-M4
  nucleus/parent/pom.xml
Labels: component upgrade, ee10-component

#23865 Fixes 16587 - support custom principal in Jakarta Authentication
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/jmac/callback/BaseContainerCallbackHandler.java
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/web/integration/WebPrincipal.java
  appserver/security/webintegration/src/main/java/com/sun/web/security/RealmAdapter.java
  appserver/web/web-core/src/main/java/org/apache/catalina/connector/RequestFacade.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/SecurityContext.java
Labels: bug

#23867 Using grizzly 4.0.0-M1 instead of a snapshot
  nucleus/parent/pom.xml
  snapshots/grizzly/pom.xml
  snapshots/pom.xml
Labels: ee10-component

#23870 Updates for Felix components
  appserver/pom.xml
  nucleus/parent/pom.xml
Labels: component upgrade

#23874 Integrate Shoal 3.0.0-M1
  nucleus/parent/pom.xml
  snapshots/pom.xml
  snapshots/shoal/pom.xml
Labels: component upgrade, ee10-component

#23876 Integrate Jersey 3.1.0-M4
  appserver/distributions/glassfish/pom.xml
  appserver/distributions/glassfish/src/main/patches/jersey-hk2/META-INF/MANIFEST.MF
  appserver/distributions/web/pom.xml
  appserver/distributions/web/src/main/patches/jersey-hk2/META-INF/MANIFEST.MF
  nucleus/parent/pom.xml
  snapshots/jersey/pom.xml
  snapshots/pom.xml
Labels: component upgrade, ee10-component

#23877 Patch for jersey-hk2.jar to fix OSGi error
  appserver/distributions/glassfish/pom.xml
  appserver/distributions/glassfish/src/main/patches/jersey-hk2/META-INF/MANIFEST.MF
Labels: bug

#23879 Jna511
  appserver/libpam4j/pom.xml
  appserver/libpam4j/src/main/java/org/jvnet/libpam/PAM.java
  appserver/libpam4j/src/main/java/org/jvnet/libpam/PAMException.java
  appserver/libpam4j/src/main/java/org/jvnet/libpam/UnixUser.java
  appserver/libpam4j/src/main/java/org/jvnet/libpam/impl/BSDCLibrary.java
  appserver/libpam4j/src/main/java/org/jvnet/libpam/impl/BSDPasswd.java
  appserver/libpam4j/src/main/java/org/jvnet/libpam/impl/CLibrary.java
  appserver/libpam4j/src/main/java/org/jvnet/libpam/impl/FreeBSDCLibrary.java
  appserver/libpam4j/src/main/java/org/jvnet/libpam/impl/FreeBSDPasswd.java
  appserver/libpam4j/src/main/java/org/jvnet/libpam/impl/LinuxCLibrary.java
  appserver/libpam4j/src/main/java/org/jvnet/libpam/impl/LinuxPasswd.java
  appserver/libpam4j/src/main/java/org/jvnet/libpam/impl/PAMLibrary.java
  appserver/libpam4j/src/main/java/org/jvnet/libpam/impl/SolarisCLibrary.java
  appserver/libpam4j/src/main/java/org/jvnet/libpam/impl/SolarisPasswd.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/FelixPrettyPrinter.java
Labels: component upgrade, code cleaning
