Repository eclipse-ee4j/glassfish, pull requests merged in 2022-05, with the labels that each got.

#23928 Update various versions
  appserver/pom.xml
  nucleus/parent/pom.xml
Labels: component upgrade

#23929 switch from obsolete jsonp-jaxrs to parsson media
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/web/pom.xml
  appserver/featuresets/web/pom.xml
  appserver/pom.xml
  appserver/tests/tck/rest/pom.xml
Labels: component upgrade

#23930 Upgrade jbatch to v2.1.0
  appserver/pom.xml
Labels: component upgrade, ee10-component

#23932 Integrate WaSP 3.1.0-M4
  appserver/pom.xml
Labels: component upgrade, ee10-component, ee10-tck

#23934 Fix #23933 by adding a proxy for the Policy when Security Managed used
  appserver/featuresets/debug/pom.xml
  appserver/pom.xml
  appserver/tests/tck/authorization/pom.xml
  nucleus/security/core/pom.xml
  nucleus/security/core/src/main/java/com/sun/enterprise/security/PolicyLoader.java
Labels: ee10-tck

#23935 Integrate WaSP 3.1.0-M5 and update pages TCK runner
  appserver/pom.xml
  appserver/tests/tck/pages/pom.xml
Labels: component upgrade, ee10-component

#23936 Maven Bundle Plugin updated to 5.1.6
  appserver/featuresets/web/pom.xml
  appserver/pom.xml
  nucleus/core/kernel/osgi.bundle
  nucleus/parent/pom.xml
Labels: build and test improvement, dependencies

#23937 Upgrade jbatch to v2.1.1
  appserver/pom.xml
Labels: component upgrade, ee10-component

#23942 update concurrent API jars to 3.0.0
  appserver/pom.xml
Labels: component upgrade

#23938 Add pom and code for running CDI TCK
  appserver/tests/tck/cdi/pom.xml
  appserver/tests/tck/cdi/src/test/java/org/jboss/weld/tck/glassfish/GlassFishDeploymentExceptionTransformer.java
  appserver/tests/tck/cdi/src/test/java/org/jboss/weld/tck/glassfish/GlassFishExtension.java
  appserver/tests/tck/cdi/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  appserver/tests/tck/cdi/src/test/resources/log4j.xml
  appserver/tests/tck/cdi/src/test/resources/password.txt
  appserver/tests/tck/pom.xml
Labels: build and test improvement

#23943 Issue #23892 Fixed rules for overriding resources by deployed applications
  appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/ACCClassLoader.java
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/ASURLClassLoader.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/ResourceLocator.java
Labels: ee10-tck

#23944 Fix Weld processing a beans.xml, e.g. enabling interceptors
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/RootBeanDeploymentArchive.java
  appserver/web/weld-integration/src/test/java/org/glassfish/weld/RootBeanDeploymentArchiveTest.java
Labels: ee10-tck

#23946 CDI API + Weldconnector service file and refactoring
  appserver/pom.xml
  appserver/tests/tck/cdi/src/test/java/org/jboss/weld/tck/glassfish/GlassFishDeploymentExceptionTransformer.java
  appserver/web/cdi-api-fragment/pom.xml
  appserver/web/cdi-api-fragment/src/main/resources/META-INF/services/jakarta.enterprise.inject.build.compatible.spi.BuildServices
  appserver/web/gf-weld-connector/src/main/java/org/glassfish/weld/connector/WeldSniffer.java
  appserver/web/gf-weld-connector/src/main/java/org/glassfish/weld/connector/WeldUtils.java
Labels: ee10-tck

#23951 Update several dependencies to updated versions
  appserver/pom.xml
  nucleus/parent/pom.xml
Labels: component upgrade
