Repository eclipse-ee4j/glassfish, pull requests merged in 2022-08, with the labels that each got.

#24072 Update of the documentation related to latest changes in logging
  docs/add-on-component-development-guide/src/main/asciidoc/adding-container-capabilities.adoc
  docs/administration-guide/src/main/asciidoc/asadmin-subcommands.adoc
  docs/administration-guide/src/main/asciidoc/batch.adoc
  docs/administration-guide/src/main/asciidoc/concurrent.adoc
  docs/administration-guide/src/main/asciidoc/connectors.adoc
  docs/administration-guide/src/main/asciidoc/domains.adoc
  docs/administration-guide/src/main/asciidoc/general-administration.adoc
  docs/administration-guide/src/main/asciidoc/http_https.adoc
  docs/administration-guide/src/main/asciidoc/javamail.adoc
  docs/administration-guide/src/main/asciidoc/jdbc.adoc
  docs/administration-guide/src/main/asciidoc/jms.adoc
  docs/administration-guide/src/main/asciidoc/jndi.adoc
  docs/administration-guide/src/main/asciidoc/jvm.adoc
  docs/administration-guide/src/main/asciidoc/lifecycle-modules.adoc
  docs/administration-guide/src/main/asciidoc/loe.adoc
  docs/administration-guide/src/main/asciidoc/lof.adoc
  docs/administration-guide/src/main/asciidoc/logging.adoc
  docs/administration-guide/src/main/asciidoc/lot.adoc
  docs/administration-guide/src/main/asciidoc/monitoring.adoc
  docs/administration-guide/src/main/asciidoc/overview.adoc
  docs/administration-guide/src/main/asciidoc/part-appendixes.adoc
  docs/administration-guide/src/main/asciidoc/preface.adoc
  docs/administration-guide/src/main/asciidoc/title.adoc
  docs/administration-guide/src/main/asciidoc/transactions.adoc
  docs/administration-guide/src/main/asciidoc/webapps.adoc
  docs/application-development-guide/src/main/asciidoc/debugging-apps.adoc
  docs/application-development-guide/src/main/asciidoc/setting-up-dev-env.adoc
  docs/deployment-planning-guide/src/main/asciidoc/checklist.adoc
  docs/embedded-server-guide/src/main/asciidoc/embedded-server-guide.adoc
  docs/error-messages-reference/src/main/asciidoc/error-messages.adoc
  docs/parent/pom.xml
  docs/performance-tuning-guide/src/main/asciidoc/tuning-glassfish.adoc
  docs/pom.xml
  docs/reference-manual/src/main/asciidoc/collect-log-files.adoc
  docs/reference-manual/src/main/asciidoc/instance.adoc
  docs/reference-manual/src/main/asciidoc/list-log-attributes.adoc
  docs/reference-manual/src/main/asciidoc/list-log-levels.adoc
  docs/reference-manual/src/main/asciidoc/list-loggers.adoc
  docs/reference-manual/src/main/asciidoc/logging.adoc
  docs/reference-manual/src/main/asciidoc/rotate-log.adoc
  docs/reference-manual/src/main/asciidoc/set-log-attributes.adoc
  docs/reference-manual/src/main/asciidoc/set-log-file-format.adoc
  docs/reference-manual/src/main/asciidoc/set-log-levels.adoc
  docs/troubleshooting-guide/src/main/asciidoc/overview.adoc
  nucleus/core/logging/src/main/manpages/com/sun/enterprise/server/logging/commands/list-log-attributes.1
  nucleus/core/logging/src/main/manpages/com/sun/enterprise/server/logging/commands/set-log-file-format.1
Labels: Documentation

#24073 Integrate Expressly 5.0.0
  nucleus/parent/pom.xml
Labels: component upgrade, ee10-component

#24075 Fixed typo in read-uncommited
  appserver/connectors/connectors-internal-api/src/main/java/com/sun/appserv/connectors/internal/api/ConnectorsUtil.java
Labels: bug

#24076 More robust solution for Helidon
  README.md
  appserver/featuresets/glassfish/pom.xml
  appserver/microprofile/config/pom.xml
  appserver/microprofile/connectors/pom.xml
  appserver/pom.xml
  appserver/tests/tck/microprofile/config/pom.xml
  appserver/web/weld-integration/src/main/java/org/glassfish/cdi/CDILoggerInfo.java
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/BeanDeploymentArchiveImpl.java
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/DeploymentImpl.java
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/FilteringClassLoader.java
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/JavaVersion.java
  nucleus/common/common-util/src/test/java/com/sun/enterprise/util/JavaVersionTest.java
Labels: bug

#24078 Integrate Hibernate Validator 8.0.0.CR3
  nucleus/parent/pom.xml
Labels: component upgrade, ee10-component

#24093 More tolerant test - there may be more server.log files
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/rest/LoggingRestITest.java
Labels: build and test improvement

#24094 Integrate helidon-config 3.0.1 and Nimbus 9.24.2
  appserver/pom.xml
Labels: component upgrade

#24095 TCK results for Web Profile 10
  docs/website/src/main/resources/certifications/jakarta-web-profile/10/TCK-Results-7.0.0-M8.md
Labels: Documentation
