Repository eclipse-ee4j/glassfish, pull requests merged in 2022-02, with the labels that each got.

#23778 Add project to anchor remote debugger to.
  appserver/featuresets/debug/pom.xml
  appserver/featuresets/debug/src/main/java/org/glassfish/main/debug/Debug.java
  appserver/featuresets/debug/src/test/java/org/glassfish/debug/DebugTest.java
  appserver/featuresets/pom.xml
  nucleus/parent/pom.xml
Labels: build and test improvement

#23780 Small amount of cleanup for JDBC code
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/common/DataSourceObjectBuilder.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/common/DataSourceSpec.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/monitoring/JdbcRAConstants.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/monitoring/JdbcStatsProvider.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/CPManagedConnectionFactory.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/ConnectionManagerImplementation.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/ConnectionRequestInfoImpl.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/DMManagedConnectionFactory.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/DSManagedConnectionFactory.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/JdbcObjectsFactory.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/LocalTransactionImpl.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/ManagedConnectionFactoryImpl.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/ManagedConnectionImpl.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/ManagedConnectionMetaDataImpl.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/ResourceAdapterImpl.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/XAManagedConnectionFactory.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/XAResourceImpl.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/base/AbstractDataSource.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/base/CacheObjectKey.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/base/CallableStatementWrapper.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/base/ConnectionHolder.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/base/ConnectionWrapper.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/base/DatabaseMetaDataWrapper.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/base/PreparedStatementWrapper.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/base/ResultSetWrapper.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/base/StatementWrapper.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/base/datastructure/Cache.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/base/datastructure/CacheFactory.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/base/datastructure/FIXEDCacheImpl.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/base/datastructure/LRUCacheImpl.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/util/MethodExecutor.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/util/ResultSetClosedEventListener.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/util/SQLTrace.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/util/SQLTraceCache.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/util/SQLTraceDelegator.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/util/SQLTraceLogger.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/util/SQLTraceTimerTask.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/util/SecurityUtils.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/util/StatementLeakDetector.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/util/StatementLeakListener.java
  appserver/jdbc/jdbc-ra/jdbc40/src/main/java/com/sun/gjc/spi/jdbc40/CallableStatementWrapper40.java
  appserver/jdbc/jdbc-ra/jdbc40/src/main/java/com/sun/gjc/spi/jdbc40/ConnectionHolder40.java
  appserver/jdbc/jdbc-ra/jdbc40/src/main/java/com/sun/gjc/spi/jdbc40/ConnectionWrapper40.java
  appserver/jdbc/jdbc-ra/jdbc40/src/main/java/com/sun/gjc/spi/jdbc40/DataSource40.java
  appserver/jdbc/jdbc-ra/jdbc40/src/main/java/com/sun/gjc/spi/jdbc40/DatabaseMetaDataWrapper40.java
  appserver/jdbc/jdbc-ra/jdbc40/src/main/java/com/sun/gjc/spi/jdbc40/Jdbc40ObjectsFactory.java
  appserver/jdbc/jdbc-ra/jdbc40/src/main/java/com/sun/gjc/spi/jdbc40/PreparedStatementWrapper40.java
  appserver/jdbc/jdbc-ra/jdbc40/src/main/java/com/sun/gjc/spi/jdbc40/ProfiledConnectionWrapper40.java
  appserver/jdbc/jdbc-ra/jdbc40/src/main/java/com/sun/gjc/spi/jdbc40/ResultSetWrapper40.java
  appserver/jdbc/jdbc-ra/jdbc40/src/main/java/com/sun/gjc/spi/jdbc40/StatementWrapper40.java
Labels: code cleaning

#23783 Integrate Tags 3.0.0-RC1/M1.
  appserver/pom.xml
  snapshots/pom.xml
  snapshots/tags/pom.xml
Labels: component upgrade, ee10-component

#23784 Fix #23772 The create-file-user subcommand with passwordfile option i…
  nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/embeddable/CommandExecutorImpl.java
Labels: bug

#23785 Integrate hibernate validator 7.0.2.
  nucleus/parent/pom.xml
Labels: component upgrade

#23786 Integrate yasson 2.0.4
  appserver/pom.xml
Labels: component upgrade

#23787 Integrate Tyrus 2.0.2
  appserver/pom.xml
Labels: component upgrade

#23789 Update various maven plugins
  nucleus/parent/pom.xml
Labels: build and test improvement

#23790 Jackson2131
  nucleus/parent/pom.xml
Labels: component upgrade

#23794 #23507 Removed console devtests
  appserver/admingui/devtests/README.txt
  appserver/admingui/devtests/hudson.xml
  appserver/admingui/devtests/pom.xml
  appserver/admingui/devtests/run_test.sh
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/AdminObjectTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/AdminServiceTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/AppScopedResourcesTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/ApplicationTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/AvailabilityServiceTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/BaseSeleniumTestClass.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/ClusterTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/ConfigTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/ConnectorServiceTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/ConnectorsTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/EjbContainerTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/EnterpriseServerTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/GMSTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/HttpServiceTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/IiopListenerTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/JVMReportTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/JavaMailTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/JavaMessageServiceTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/JdbcTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/JmsResourcesTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/JndiTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/JsonUtilTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/JvmSettingsTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/LifecycleModulesTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/LogViewerTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/LoggerSettingsTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/MonitoringTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/MsgSecurityTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/NetworkConfigTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/NodeTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/RegistrationTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/ResourceAdapterConfigsTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/RestResponseTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/RestSessionTimeoutTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/SecurityTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/SpecificTestRule.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/StandaloneTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/ThreadPoolsTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/TransactionServiceTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/VirtualServerTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/WaitForLoadCallBack.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/WebContainerTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/WorkSecurityMapTest.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/util/ElementFinder.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/util/SeleniumHelper.java
  appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/util/SeleniumWrapper.java
  appserver/admingui/devtests/src/test/resources/JavaEEApp.ear
  appserver/admingui/devtests/src/test/resources/ejb-ejb30-hello-sessionApp.ear
  appserver/admingui/devtests/src/test/resources/ejb-timer-sessiontimerApp.ear
  appserver/admingui/devtests/src/test/resources/firefoxProfile/prefs.js
  appserver/admingui/devtests/src/test/resources/test.war
Labels: build and test improvement

#23795 Small amount of cleanup for JPA (Persistence) container
  appserver/persistence/jpa-container/src/main/java/org/glassfish/persistence/jpa/EmbeddedProviderContainerContractInfo.java
  appserver/persistence/jpa-container/src/main/java/org/glassfish/persistence/jpa/JPAContainer.java
  appserver/persistence/jpa-container/src/main/java/org/glassfish/persistence/jpa/JPADeployer.java
  appserver/persistence/jpa-container/src/main/java/org/glassfish/persistence/jpa/JPApplicationContainer.java
  appserver/persistence/jpa-container/src/main/java/org/glassfish/persistence/jpa/PersistenceUnitInfoImpl.java
  appserver/persistence/jpa-container/src/main/java/org/glassfish/persistence/jpa/PersistenceUnitLoader.java
  appserver/persistence/jpa-container/src/main/java/org/glassfish/persistence/jpa/ProviderContainerContractInfo.java
  appserver/persistence/jpa-container/src/main/java/org/glassfish/persistence/jpa/ProviderContainerContractInfoBase.java
  appserver/persistence/jpa-container/src/main/java/org/glassfish/persistence/jpa/ServerProviderContainerContractInfo.java
  appserver/persistence/jpa-container/src/main/java/org/glassfish/persistence/jpa/schemageneration/EclipseLinkSchemaGenerationProcessor.java
  appserver/persistence/jpa-container/src/main/java/org/glassfish/persistence/jpa/schemageneration/JPAStandardSchemaGenerationProcessor.java
  appserver/persistence/jpa-container/src/main/java/org/glassfish/persistence/jpa/schemageneration/SchemaGenerationProcessor.java
  appserver/persistence/jpa-container/src/main/java/org/glassfish/persistence/jpa/schemageneration/SchemaGenerationProcessorFactory.java
Labels: code cleaning

#23797 JDBC cleaning 2
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/common/DataSourceObjectBuilder.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/DMManagedConnectionFactory.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/JdbcObjectsFactory.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/ManagedConnectionFactoryImpl.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/base/PreparedStatementWrapper.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/base/StatementWrapper.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/util/MethodExecutor.java
  appserver/jdbc/jdbc-ra/jdbc40/src/main/java/com/sun/gjc/spi/jdbc40/CallableStatementWrapper40.java
  appserver/jdbc/jdbc-ra/jdbc40/src/main/java/com/sun/gjc/spi/jdbc40/ConnectionHolder40.java
  appserver/jdbc/jdbc-ra/jdbc40/src/main/java/com/sun/gjc/spi/jdbc40/DataSource40.java
  appserver/jdbc/jdbc-ra/jdbc40/src/main/java/com/sun/gjc/spi/jdbc40/DatabaseMetaDataWrapper40.java
  appserver/jdbc/jdbc-ra/jdbc40/src/main/java/com/sun/gjc/spi/jdbc40/ResultSetWrapper40.java
Labels: code cleaning

#23801 #23628 Fixed TCK tests - issues with the SecurityManager
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/ClassGenerator.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/Generator.java
Labels: bug

#23811 Intergate WebSocket API 2.1.0
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/shell/glassfish-embedded-static-shell/pom.xml
  appserver/extras/embedded/web/pom.xml
  appserver/extras/javaee/manifest-jar/pom.xml
  appserver/featuresets/web/pom.xml
  appserver/pom.xml
Labels: component upgrade, ee10-component

#23814 Update various maven plug-ins
  nucleus/parent/pom.xml
  nucleus/pom.xml
Labels: dependencies

#23817 Organise nucleus pom
  appserver/pom.xml
  nucleus/parent/pom.xml
Labels: code cleaning

#23824 Fixed nightly and weekly builds which use gfbuild.sh
  gfbuild.sh
Labels: build and test improvement

#23823 Integrate Faces 4.0.0-M3
  appserver/pom.xml
Labels: component upgrade, ee10-component

#23825 Update Jakarta dependencies
  appserver/pom.xml
  snapshots/hibernate-validator/pom.xml
  snapshots/jbatch/pom.xml
  snapshots/pom.xml
Labels: component upgrade, ee10-component

#23826 Jakarta update3
  appserver/pom.xml
  nucleus/parent/pom.xml
Labels: component upgrade, ee10-component
