Repository eclipse-ee4j/glassfish, pull requests merged in 2022-10, with the labels that each got.

#24118 Fix #24115 Reason phrase is not printed in the validation error message
  nucleus/hk2/hk2-config/src/main/java/org/jvnet/hk2/config/MessageInterpolatorImpl.java
Labels: bug

#24123 Update NOTICE.md
  NOTICE.md
Labels: Documentation

#24127 Update various versions
  appserver/pom.xml
  nucleus/parent/pom.xml
Labels: component upgrade, ee10-component

#24134 Small amount of cleaning for connector related code
  appserver/common/container-common/src/main/java/org/glassfish/javaee/services/JMSCFResourcePMProxy.java
  appserver/connectors/connectors-internal-api/src/main/java/com/sun/appserv/connectors/internal/api/ConnectorRuntime.java
  appserver/connectors/connectors-internal-api/src/main/java/com/sun/appserv/connectors/internal/api/ConnectorsUtil.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/ConnectionManagerImpl.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/ConnectorRuntime.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/deployer/ConnectorResourceDeployer.java
Labels: code cleaning
