Repository eclipse-ee4j/glassfish, pull requests merged in 2022-06, with the labels that each got.

#23964 Reverting Jersey back to M5 as the update broke 4 TCK tests
  nucleus/parent/pom.xml
Labels: ee10-component, ee10-tck

#23966 Integrate Mojarra 4.0.0
  appserver/pom.xml
Labels: component upgrade, ee10-component

#23965 Test bean attributes for session bean
  appserver/tests/tck/cdi/pom.xml
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java
Labels: ee10-tck

#23967 Integrate WaSP 3.1.0-M6
  appserver/pom.xml
Labels: component upgrade, ee10-component, ee10-tck

#23968 Add EE 10 schemas from https://jakarta.ee/xml/ns/jakartaee/#10
  appserver/deployment/schemas/src/main/resources/glassfish/lib/schemas/connector_2_1.xsd
  appserver/deployment/schemas/src/main/resources/glassfish/lib/schemas/jsp_3_1.xsd
  appserver/deployment/schemas/src/main/resources/glassfish/lib/schemas/web-app_6_0.xsd
  appserver/deployment/schemas/src/main/resources/glassfish/lib/schemas/web-common_6_0.xsd
  appserver/deployment/schemas/src/main/resources/glassfish/lib/schemas/web-fragment_6_0.xsd
Labels: ee10-component

#23970 Try to eager load Servlets at startup.
  appserver/web/web-core/src/main/java/org/apache/catalina/Wrapper.java
  appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.java
  appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardWrapper.java
Labels: bug, ee10-tck

#23974 Set required system property for the CDI TCK, passing 1 more test
  appserver/tests/tck/cdi/pom.xml
Labels: ee10-tck

#23978 Updated Weld to 5.0.0.SP2
  appserver/pom.xml
Labels: component upgrade, ee10-component, ee10-tck

#23994 Integrate Grizzly 4.0.0
  nucleus/parent/pom.xml
Labels: component upgrade

#24000 Helidon Config - CDI TCK Fix 2
  appserver/microprofile/config/src/main/java/io/helidon/microprofile/config/ConfigCdiExtension.java
Labels: ee10-tck

#24005 Integrate WaSP 3.1.0-M7
  appserver/pom.xml
Labels: component upgrade, ee10-component, ee10-tck

#24010 Integrate OmniConcurrent RC3
  appserver/pom.xml
Labels: component upgrade, ee10-component, ee10-tck

#24013 Make bind exception more clear
  appserver/common/glassfish-naming/src/main/java/com/sun/enterprise/naming/impl/TransientContext.java
Labels: code cleaning, build and test improvement

#24015 Added excludes for challenged Concurrency TCK tests and corrected header
  appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/node/ManagedScheduledExecutorDefinitionNode.java
  appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/node/ManagedThreadFactoryDefinitionNode.java
  appserver/tests/tck/concurrency/suite.xml
Labels: ee10-tck

#24016 Update concurrency runner and domain.xml to execute sigtest on server
  appserver/admin/template/src/main/resources/config/domain.xml
  appserver/tests/tck/concurrency/pom.xml
Labels: ee10-tck

#24023 Add TCK runner for Jakarta Validation
  appserver/tests/tck/pom.xml
  appserver/tests/tck/validation/pom.xml
  appserver/tests/tck/validation/suite.xml
  nucleus/parent/pom.xml
Labels: ee10-tck

#24022 Exclude jboss audit dependencies. There are problematic for CIs.
  appserver/tests/tck/concurrency/pom.xml
Labels: ee10-tck

#24025 Integrate concurrent rc4
  appserver/pom.xml
Labels: ee10-tck

#24026 appclient container needs 2.1.1 Jakarta Annotation ManagedBean - alt
  appserver/distributions/glassfish/pom.xml
Labels: ee10-tck

#24028 Correct classifier for CDI TCK signature test
  appserver/tests/tck/cdi/pom.xml
Labels: ee10-tck

#24029 Comment out MVC temporarily to have CDI TCK passing again
  appserver/featuresets/web/pom.xml
Labels: ee10-tck

#24031 Integrate command security 1.0.15
  nucleus/parent/pom.xml
Labels: build and test improvement, dependencies

#24032 Exclude challenged concurrency TCK test
  appserver/tests/tck/concurrency/suite.xml
Labels: ee10-tck

#24034 Use excluded groups property for CDI TCK
  appserver/tests/tck/cdi/pom.xml
Labels: ee10-tck
