Repository eclipse-ee4j/glassfish, pull requests merged in 2022-04, with the labels that each got.

#23880 Latest updates
  Jenkinsfile
  appserver/distributions/glassfish/pom.xml
  appserver/distributions/glassfish/src/main/patches/jersey-hk2/META-INF/MANIFEST.MF
  appserver/extras/embedded/common/bootstrap/pom.xml
  appserver/featuresets/debug/pom.xml
  appserver/osgi-platforms/felix-webconsole-extension/pom.xml
  appserver/osgi-platforms/felix-webconsole-extension/src/main/java/org/glassfish/osgi/felixwebconsoleextension/FelixWebConsoleExtensionActivator.java
  docs/pom.xml
  etc/docker-jdk17/Dockerfile
  etc/docker-jdk17/Makefile
  etc/docker-jdk17/entrypoint.sh
  nucleus/common/common-util/pom.xml
  nucleus/core/bootstrap/pom.xml
  nucleus/core/kernel/osgi.bundle
  nucleus/distributions/nucleus-common/src/main/resources/config/osgi.properties
  nucleus/distributions/nucleus/src/main/assembly/nucleus-new.xml
  nucleus/featuresets/atomic/pom.xml
  nucleus/hk2/hk2-config/pom.xml
  nucleus/osgi-platforms/osgi-cli-interactive/pom.xml
  nucleus/osgi-platforms/osgi-cli-interactive/src/main/java/org/glassfish/osgi/cli/interactive/LocalOSGiShellCommand.java
  nucleus/parent/pom.xml
  snapshots/hibernate-validator/pom.xml
  snapshots/pom.xml
Labels: component upgrade

#23881 Update various version in pom.xml
  appserver/pom.xml
  appserver/tests/pom.xml
  nucleus/parent/pom.xml
  pom.xml
Labels: component upgrade

#23883 Using released hibernate-validator 8.0.0.Alpha3
  nucleus/parent/pom.xml
  snapshots/hibernate-validator/pom.xml
  snapshots/pom.xml
Labels: component upgrade

#23885 Integrate Metro 4.0.0-M4
  appserver/tests/appserv-tests/devtests/webservice/annotations/jaxwstools.xml
  appserver/tests/appserv-tests/devtests/webservice/annotations/mappedname/build.xml
  appserver/tests/appserv-tests/devtests/webservice/annotations/msgctxt/build.xml
  appserver/tests/appserv-tests/devtests/webservice/annotations/noname/build.xml
  appserver/tests/appserv-tests/devtests/webservice/annotations/noname2/build.xml
  appserver/tests/appserv-tests/devtests/webservice/annotations/oneway/build.xml
  appserver/tests/appserv-tests/devtests/webservice/annotations/postconstruct/build.xml
  appserver/tests/appserv-tests/devtests/webservice/annotations/webserviceref-cobundle/build.xml
  appserver/tests/appserv-tests/devtests/webservice/annotations/webserviceref-lookup/build.xml
  appserver/tests/appserv-tests/devtests/webservice/annotations/webservices13-addressing-2/build.xml
  appserver/tests/appserv-tests/devtests/webservice/annotations/webservices13-addressing-appclient/build.xml
  appserver/tests/appserv-tests/devtests/webservice/annotations/webservices13-addressing/build.xml
  appserver/tests/appserv-tests/devtests/webservice/annotations/webservices13-clientdds/build.xml
  appserver/tests/appserv-tests/devtests/webservice/annotations/webservices13-respectbinding/build.xml
  appserver/tests/appserv-tests/devtests/webservice/annotations/wsctxt/build.xml
  appserver/tests/appserv-tests/devtests/webservice/ejb_annotations/libdependent/build.xml
  appserver/tests/appserv-tests/devtests/webservice/ejb_annotations/singleton/build.xml
  appserver/tests/appserv-tests/devtests/webservice/ejb_annotations/wsRef-webservice-features/build.xml
  nucleus/parent/pom.xml
  snapshots/metro/pom.xml
  snapshots/pom.xml
Labels: component upgrade, ee10-component

#23887 Change the dependency on jackson-module-jaxb-annotations to jackson-module-jakarta-xmlbind-annotations
  appserver/admingui/jackson-jaxb/pom.xml
  appserver/admingui/pom.xml
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/shell/glassfish-embedded-static-shell/pom.xml
  appserver/extras/embedded/web/pom.xml
  nucleus/featuresets/atomic/pom.xml
  nucleus/parent/pom.xml
Labels: component upgrade

#23886 Integrate Jersey 3.0.4
  appserver/admingui/jackson-jaxb/pom.xml
  appserver/admingui/pom.xml
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/shell/glassfish-embedded-static-shell/pom.xml
  appserver/extras/embedded/web/pom.xml
  nucleus/featuresets/atomic/pom.xml
  nucleus/parent/pom.xml
Labels: component upgrade

#23890 Fixed compatibility of OpenDJ with JDK17
  appserver/tests/appserv-tests/devtests/security/run_test.sh
Labels: build and test improvement

#23894 Integrate WaSP 3.1.0-M2
  appserver/pom.xml
Labels: component upgrade, ee10-component, ee10-tck

#23896 Fix remaining Servlet 6 TCK failures
  appserver/featuresets/debug/pom.xml
  appserver/tests/tck/servlet/pom.xml
  appserver/tests/tck/tck-download/jakarta-servlet-tck/pom.xml
  appserver/web/web-core/src/main/java/com/sun/enterprise/web/connector/grizzly/CoyoteConnectorLauncher.java
  appserver/web/web-core/src/main/java/com/sun/enterprise/web/connector/grizzly/DummyConnectorLauncher.java
  appserver/web/web-core/src/main/java/org/apache/catalina/connector/ClientAbortException.java
  appserver/web/web-core/src/main/java/org/apache/catalina/connector/Connector.java
  appserver/web/web-core/src/main/java/org/apache/catalina/connector/CoyoteAdapter.java
  appserver/web/web-core/src/main/java/org/apache/catalina/connector/CoyotePrincipal.java
  appserver/web/web-core/src/main/java/org/apache/catalina/connector/CoyoteWriter.java
  appserver/web/web-core/src/main/java/org/apache/catalina/connector/Request.java
  appserver/web/web-core/src/main/java/org/apache/catalina/connector/Response.java
  appserver/web/web-core/src/main/java/org/apache/catalina/connector/ResponseFacade.java
  appserver/web/web-core/src/main/java/org/apache/catalina/core/ApplicationContext.java
  appserver/web/web-core/src/main/java/org/apache/catalina/core/ApplicationDispatcher.java
  appserver/web/web-core/src/main/java/org/apache/catalina/core/ApplicationPushBuilder.java
  appserver/web/web-core/src/main/java/org/apache/catalina/core/SessionCookieConfigImpl.java
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/VirtualServer.java
  nucleus/parent/pom.xml
Labels: ee10-tck

#23897 Enable the CDI Lite LiteExtensionTranslator
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/DeploymentImpl.java
Labels: ee10-tck

#23898 Implement getRequestId() and related
  appserver/security/webintegration/src/main/java/com/sun/web/security/HttpRequestWrapper.java
  appserver/web/web-core/src/main/java/org/apache/catalina/connector/Request.java
  appserver/web/web-core/src/main/java/org/apache/catalina/connector/RequestFacade.java
  appserver/web/web-core/src/main/java/org/apache/catalina/core/DummyRequest.java
Labels: enhancement

#23903 #23745: jakarta.enterprise.cdi-api not reachable through javaee.jar
  appserver/extras/javaee/manifest-jar/pom.xml
  appserver/tests/tck/faces/pom.xml
Labels: build and test improvement

#23905 Integrate Expressly 5.0.0-M2 + TCK tests for it.
  appserver/featuresets/debug/pom.xml
  appserver/pom.xml
  appserver/tests/tck/expression_language/pom.xml
  appserver/tests/tck/expression_language/src/test/java/com/sun/ts/run/StandaloneRunnerITest.java
  appserver/tests/tck/pom.xml
  appserver/tests/tck/tck-download/jakarta-expression-language-tck/pom.xml
  appserver/tests/tck/tck-download/pom.xml
  nucleus/parent/pom.xml
Labels: component upgrade, build and test improvement, ee10-component

#23911 Felix jdk17 fix - able to start with the Security Manager enabled
  appserver/featuresets/debug/pom.xml
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/GlassFishMain.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/osgi/OSGiGlassFishRuntimeBuilder.java
  nucleus/parent/pom.xml
  snapshots/felix-framework/pom.xml
  snapshots/felix-main/pom.xml
  snapshots/pom.xml
Labels: bug

#23916 Issue 23914 - jsp:plugin noop, which removes ieClassId
  appserver/admin/template/src/main/resources/config/default-web.xml
  appserver/pom.xml
  appserver/tests/appserv-tests/devtests/web/jspServletOverride/WebTest.java
  appserver/tests/appserv-tests/devtests/web/jspServletOverride/descriptor/web.xml
  appserver/tests/appserv-tests/devtests/web/jspServletOverride/docroot/jsp/overrideIeClassId.jsp
  appserver/tests/embedded/web/web-api/src/main/resources/org/glassfish/tests/webapi/my-default-web.xml
  appserver/tests/tck/tck-download/jakarta-pages-tck/pom.xml
  appserver/web/web-embed/api/src/main/resources/org/glassfish/web/embed/default-web.xml
  appserver/web/web-glue/src/main/java/org/glassfish/web/jsp/JSPCompiler.java
  docs/application-deployment-guide/src/main/asciidoc/dd-elements.adoc
Labels: component upgrade, ee10-component, ee10-tck

#23918 Bump OpenMQ version
  appserver/pom.xml
Labels: component upgrade
