Repository eclipse-ee4j/glassfish, pull requests merged in 2022-07, with the labels that each got.

#24040 Add execution of the CDI Lang Model TCK
  appserver/tests/tck/cdi/cdi-full/pom.xml
  appserver/tests/tck/cdi/cdi-full/src/test/java/org/jboss/weld/tck/glassfish/GlassFishBeansImpl.java
  appserver/tests/tck/cdi/cdi-full/src/test/java/org/jboss/weld/tck/glassfish/GlassFishContextImpl.java
  appserver/tests/tck/cdi/cdi-full/src/test/java/org/jboss/weld/tck/glassfish/GlassFishDeploymentExceptionTransformer.java
  appserver/tests/tck/cdi/cdi-full/src/test/java/org/jboss/weld/tck/glassfish/GlassFishELImpl.java
  appserver/tests/tck/cdi/cdi-full/src/test/java/org/jboss/weld/tck/glassfish/GlassFishExtension.java
  appserver/tests/tck/cdi/cdi-full/src/test/resources/META-INF/cdi-tck.properties
  appserver/tests/tck/cdi/cdi-full/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  appserver/tests/tck/cdi/cdi-full/src/test/resources/log4j.xml
  appserver/tests/tck/cdi/cdi-full/src/test/resources/password.txt
  appserver/tests/tck/cdi/cdi-model/pom.xml
  appserver/tests/tck/cdi/cdi-model/src/test/java/org/glassfish/tck/cdi/lang/model/CDILangModelTCKRunner.java
  appserver/tests/tck/cdi/cdi-model/src/test/java/org/glassfish/tck/cdi/lang/model/CleanupExtension.java
  appserver/tests/tck/cdi/cdi-model/src/test/java/org/glassfish/tck/cdi/lang/model/LangModelVerifierBuildCompatibleExtension.java
  appserver/tests/tck/cdi/pom.xml
Labels: ee10-tck

#24041 Update TCK link and SHA for Jakarta Activation
  docs/website/src/main/resources/certifications/jakarta-platform/10/TCK-Results-7.0.md
Labels: Documentation

#24042 Move all links to final versions, update a wrong SHA and name.
  docs/website/src/main/resources/certifications/jakarta-platform/10/TCK-Results-7.0.md
Labels: Documentation

#24043 Integrate Exousia 2.1.0
  appserver/pom.xml
Labels: component upgrade, ee10-component

#24051 Logging fixes
  appserver/distributions/glassfish-common/src/main/resources/glassfish/config/branding/glassfish-version.properties
  appserver/pom.xml
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/LoggingITest.java
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/rest/LoggingRestITest.java
  nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/CLICommand.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/logviewer/LogRecord.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/custom/StructuredLogViewerResource.java
  nucleus/common/common-util/src/main/java/com/sun/appserv/server/util/Version.java
  nucleus/common/glassfish-api/src/main/java/org/glassfish/api/VersionInfo.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/LogFacade.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/osgi/EmbeddedOSGiGlassFishImpl.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/logviewer/backend/LogFile.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/parser/LogParser.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/parser/ODLLogParser.java
  nucleus/core/logging/src/test/java/com/sun/enterprise/server/logging/parser/LogParserTest.java
  nucleus/core/logging/src/test/resources/com/sun/enterprise/server/logging/parser/odl-server.log
  nucleus/core/logging/src/test/resources/com/sun/enterprise/server/logging/parser/uniform-server.log
  nucleus/deployment/common/src/test/java/com/sun/enterprise/deploy/shared/FileArchiveTest.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/formatter/LogFormatDetector.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/formatter/ODLLogFormatter.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/formatter/UniformLogFormatter.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/handler/LogCollectorHandler.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/handler/Syslog.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/handler/SyslogHandler.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/GlassFishLogManagerLifeCycleTest.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/handler/HandlerConfigurationHelperTest.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/rotation/LogFileManagerTest.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/rotation/MeteredStreamTest.java
Labels: bug

#24053 Update Concurrency TCK runner for 3.0.2
  appserver/tests/tck/concurrency/pom.xml
  appserver/tests/tck/concurrency/suite-web.xml
Labels: ee10-tck
