Repository eclipse-ee4j/glassfish, pull requests merged in 2023-05, with the labels that each got.

#24398 Fix collected log files retrieval
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/ClusterITest.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/commands/CollectLogFiles.java
Labels: bug

#24402 Optimize the Monitoring Service
  nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/MonitoringService.java
Labels: code cleaning

#24403 Some Jenkins nodes are really slow - higher timeout values
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/AsadminLoggingITest.java
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/ClusterITest.java
Labels: build and test improvement

#24407 Webpage update for 7.0.4
  docs/website/src/main/resources/download.md
  docs/website/src/main/resources/download_gf7.md
Labels: Documentation

#24404 Fix ConcurrentModificationException in jdbc connection pool
  appserver/connectors/connectors-runtime/pom.xml
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/ResourceHandle.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/datastructure/RWLockDataStructure.java
  appserver/connectors/connectors-runtime/src/main/resources/com/sun/logging/enterprise/resource/resourceadapter/LogStrings.properties
  appserver/connectors/connectors-runtime/src/test/java/com/sun/enterprise/resource/pool/datastructure/RWLockDataStructureTest.java
Labels: bug

#24405 Trivial fixes of logging
  appserver/connectors/connectors-internal-api/src/main/java/com/sun/appserv/connectors/internal/ConnectorResourceManagerLifecycleListener.java
  appserver/connectors/connectors-internal-api/src/main/java/com/sun/appserv/connectors/internal/api/AppSpecificConnectorClassLoaderUtil.java
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/AsadminLoggingITest.java
  nucleus/cluster/gms-bootstrap/src/main/java/org/glassfish/gms/bootstrap/GMSAdapterService.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/admin/cli/SecureAdminConfigMonitor.java
Labels: bug

#24406 Fix login again after logout
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/web/integration/WebSecurityManager.java
  appserver/security/webintegration/src/main/java/com/sun/web/security/RealmAdapter.java
  appserver/security/webservices.security/src/main/java/com/sun/enterprise/security/webservices/SecurityServiceImpl.java
  appserver/web/web-core/src/main/java/org/apache/catalina/Realm.java
  appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/AuthenticatorBase.java
  appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/BasicAuthenticator.java
  appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/FormAuthenticator.java
  appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/SSLAuthenticator.java
  appserver/web/web-core/src/main/java/org/apache/catalina/realm/RealmBase.java
Labels: bug

#24408 Add support for running single tests to webservice and suspend
  appserver/tests/appserv-tests/devtests/webservice/build.xml
  appserver/tests/appserv-tests/devtests/webservice/ejb_annotations/build.xml
  appserver/tests/appserv-tests/devtests/webservice/run_test.sh
  runtests.sh
Labels: build and test improvement

#24409 Add servlet TCK to pom modules
  appserver/tests/tck/pom.xml
  appserver/tests/tck/tck-download/pom.xml
Labels: build and test improvement

#24412 Small amount of cleanups for the security code
  appserver/security/webservices.security/src/main/java/com/sun/enterprise/security/webservices/CommonServerSecurityPipe.java
  appserver/security/webservices.security/src/main/java/com/sun/enterprise/security/webservices/CommonServerSecurityTube.java
  appserver/security/webservices.security/src/main/java/com/sun/enterprise/security/webservices/GFServerPipeCreator.java
  appserver/security/webservices.security/src/main/java/com/sun/enterprise/security/webservices/SecurityServiceImpl.java
  appserver/security/webservices.security/src/main/java/com/sun/enterprise/security/webservices/WebServicesDelegateImpl.java
  appserver/tests/appserv-tests/devtests/webservice/ejb_annotations/security/roles/build.xml
  appserver/tests/appserv-tests/devtests/webservice/ejb_annotations/security/roles/client/Client.java
  appserver/tests/appserv-tests/devtests/webservice/ejb_annotations/security/roles/endpoint/HelloImpl.java
  appserver/tests/appserv-tests/devtests/webservice/ejb_annotations/security/roles/endpoint/sun-ejb-jar.xml
  appserver/web/web-core/src/main/java/org/apache/catalina/realm/Constants.java
  appserver/web/web-core/src/main/java/org/apache/catalina/realm/GenericPrincipal.java
  appserver/web/web-core/src/main/java/org/apache/catalina/realm/JAASCallbackHandler.java
  appserver/web/web-core/src/main/java/org/apache/catalina/realm/JAASRealm.java
  appserver/web/web-core/src/main/java/org/apache/catalina/realm/RealmBase.java
Labels: code cleaning

#24416 Integrate Jakarta JSONP 2.1.2
  appserver/pom.xml
Labels: component upgrade, ee10-component

#24418 Integrate Jersey 3.1.2
  nucleus/parent/pom.xml
Labels: component upgrade, ee10-component

#24419 Add integration test for collect logs from instance belongs to cluster
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/ClusterITest.java
Labels: build and test improvement

#24423 Fix resetting security context if principal is the same
  appserver/web/web-glue/src/main/java/com/sun/web/server/J2EEInstanceListener.java
Labels: bug

#24422 Fix redirections after deployment in Admin Console
  appserver/admingui/common/src/main/resources/removeFrame.jsf
Labels: bug

#24426 Integrate Jackson 2.15.1
  nucleus/parent/pom.xml
Labels: component upgrade

#24427 Integrate commons-io 2.12.0
  nucleus/parent/pom.xml
Labels: component upgrade

#24428 Removed unused assembly plugin configuration: useProjectArtifact
  appserver/admin/template/pom.xml
  appserver/distributions/pom.xml
  nucleus/distributions/pom.xml
Labels: build and test improvement

#24429 Fixes #24223 Make PrincipalCallback Serializable & prevent JMX exception
  nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/AdminLoginModule.java
Labels: bug

#24424 Integration tests for cluster deployment
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/ClusterITest.java
Labels: build and test improvement

#24432 Admin Console: Update instance status asynchronously
  appserver/admingui/cluster/src/main/resources/cluster/clusterInstances.jsf
  appserver/admingui/cluster/src/main/resources/cluster/clusters.jsf
  appserver/admingui/cluster/src/main/resources/node/nodes.jsf
  appserver/admingui/cluster/src/main/resources/shared/instanceStatus.jsf
  appserver/admingui/cluster/src/main/resources/shared/instancesTable.inc
  appserver/admingui/cluster/src/main/resources/standalone/standaloneInstances.jsf
  appserver/admingui/common/src/main/resources/org/glassfish/common/admingui/Strings.properties
Labels: enhancement

#24433 Fix a deployment-time recursive bytecode preprocessing in the WebappClassLoader
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
Labels: bug

#24438 Admin console: ignore standalone instance status for app details
  appserver/admingui/cluster/src/main/resources/standalone/standaloneTreeNode.jsf
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/TargetUtil.java
Labels: enhancement, New feature

#24430 Feature: allow using @Inject instead of @Context for simple injection
  appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/embedded/EJBContainerProviderImpl.java
  appserver/featuresets/web/pom.xml
  appserver/tests/tck/pom.xml
  appserver/tests/tck/rest_cdi/pom.xml
  appserver/tests/tck/rest_cdi/src/main/java/org/glassfish/tests/tck/rest/cdi/ApplicationConfig.java
  appserver/tests/tck/rest_cdi/src/main/java/org/glassfish/tests/tck/rest/cdi/ExampleResource.java
  appserver/tests/tck/rest_cdi/src/main/java/org/glassfish/tests/tck/rest/cdi/ExampleResources.java
  appserver/tests/tck/rest_cdi/src/test/java/org/glassfish/tests/tck/rest/cdi/RestCdiIT.java
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/DeploymentImpl.java
Labels: enhancement

#24441 Add ability for EJB embedded tests to be run individually and debug.
  appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/embedded/EJBContainerProviderImpl.java
  appserver/tests/appserv-tests/devtests/ejb/build.xml
  appserver/tests/appserv-tests/devtests/ejb/ejb31/embedded/basic/build.xml
  appserver/tests/appserv-tests/devtests/ejb/ejb31/embedded/build.xml
  appserver/tests/appserv-tests/devtests/ejb/ejb31/embedded/datasourcedef/build.xml
  appserver/tests/appserv-tests/devtests/ejb/ejb31/embedded/ejbandwar/build.xml
  appserver/tests/appserv-tests/devtests/ejb/ejb31/embedded/embedasync/build.xml
  appserver/tests/appserv-tests/devtests/ejb/ejb31/embedded/jaxrs/build.xml
  appserver/tests/appserv-tests/devtests/ejb/ejb31/embedded/manifestonly/build.xml
  appserver/tests/appserv-tests/devtests/ejb/ejb31/embedded/mdb/build.xml
  appserver/tests/appserv-tests/devtests/ejb/ejb31/embedded/modulewithappname/build.xml
  appserver/tests/appserv-tests/devtests/ejb/ejb31/embedded/modulewithinheritance/build.xml
  appserver/tests/appserv-tests/devtests/ejb/ejb31/embedded/modulewithlibs/build.xml
  appserver/tests/appserv-tests/devtests/ejb/ejb31/embedded/modulewithmanifest/build.xml
  appserver/tests/appserv-tests/devtests/ejb/ejb31/embedded/profile/build.xml
  appserver/tests/appserv-tests/devtests/ejb/ejb31/embedded/remote/build.xml
  appserver/tests/appserv-tests/devtests/ejb/ejb31/embedded/testclose/build.xml
  appserver/tests/appserv-tests/devtests/ejb/ejb31/embedded/timertest/build.xml
  appserver/tests/appserv-tests/devtests/ejb/ejb31/embedded/twocontainers/build.xml
  appserver/tests/appserv-tests/devtests/ejb/ejb31/embedded/twomodules/build.xml
  appserver/tests/appserv-tests/devtests/ejb/ejb31/embedded/twomoduleswithlibs/build.xml
  appserver/tests/appserv-tests/devtests/ejb/ejb32/embedded/autoclose/build.xml
  appserver/tests/appserv-tests/devtests/ejb/ejb32/embedded/build.xml
Labels: build and test improvement
