Repository eclipse-ee4j/glassfish, pull requests merged in 2023-01, with the labels that each got.

#24229 Integrate Angus Mail 1.1.0
  nucleus/parent/pom.xml
Labels: component upgrade, ee10-component

#24226 GlassfishUrlClassloader and toString
  appserver/appclient/client/acc-standalone/src/main/java/org/glassfish/appclient/client/acc/agent/ACCAgentClassLoader.java
  appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/AppClientFacade.java
  appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/ACCClassLoader.java
  appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/AppClientContainer.java
  appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/AppClientContainerBuilder.java
  appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/JWSACCClassLoader.java
  appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/ProviderContainerContractInfoImpl.java
  appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/jws/boot/ClassPathManager.java
  appserver/appclient/server/core/src/main/java/org/glassfish/appclient/server/core/AppClientServerApplication.java
  appserver/appclient/server/core/src/main/java/org/glassfish/appclient/server/core/CarHandler.java
  appserver/connectors/connectors-internal-api/src/main/java/com/sun/appserv/connectors/internal/api/ConnectorClassFinder.java
  appserver/connectors/connectors-internal-api/src/main/java/com/sun/appserv/connectors/internal/api/ConnectorsClassLoaderUtil.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/util/ConnectorClassLoader.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/util/DriverLoader.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/util/RARUtils.java
  appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/EjbJarHandler.java
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/ServletContainerInitializerUtil.java
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
  appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.java
  appserver/web/web-core/src/main/java/org/apache/catalina/session/StandardManager.java
  appserver/web/web-core/src/main/java/org/apache/catalina/util/StringManager.java
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/BeanDeploymentArchiveImpl.java
  appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/WebServicesDeployer.java
  appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/monitoring/WebServiceTesterServlet.java
  nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/DirectoryClassLoader.java
  nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/modularity/customization/CustomizationTokensProvider.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/VerifyDomainXmlCommand.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/ASURLClassLoader.java
  nucleus/common/common-util/src/main/java/org/glassfish/common/util/GlassfishUrlClassLoader.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/ClassPathBuilder.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/GlassfishBootstrapClassLoader.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/GlassfishUrlClassLoader.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/MainHelper.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/StaticGlassFishRuntimeBuilder.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/osgi/EmbeddedOSGiGlassFishRuntime.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/AppLibClassLoaderServiceImpl.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/CommonClassLoaderServiceImpl.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ServerLifecycleModule.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LoggerInfoMetadataService.java
  pom.xml
Labels: enhancement

#24230 Integrate Nimbus 9.28
  appserver/pom.xml
Labels: component upgrade

#24231 Integrate Jettison 1.5.3
  nucleus/parent/pom.xml
Labels: component upgrade

#24234 Updated concurrency tck versions
  appserver/tests/tck/concurrency/pom.xml
Labels: build and test improvement

#24242 Integrate Woodstox 6.5.0
  appserver/pom.xml
Labels: component upgrade

#24244 Use command security 1.0.16
  nucleus/parent/pom.xml
Labels: build and test improvement

#24246 Issue #24228 Fixed shutdown monitoring
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/StopDomainCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/StopInstanceInstanceCommand.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/process/ProcessUtils.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/osgi/OSGiGlassFishRuntimeBuilder.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/StopDomainCommand.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/StopServer.java
Labels: bug

#24243 Classloader updates
  appserver/appclient/client/acc-standalone/src/main/java/org/glassfish/appclient/client/acc/agent/ACCAgentClassLoader.java
  appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/ACCClassLoader.java
  appserver/web/war-util/pom.xml
  appserver/web/war-util/src/main/java/com/sun/enterprise/glassfish/web/WarHandler.java
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/JarFileManager.java
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/JdbcLeakPrevention.java
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/LogFacade.java
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/ReferenceCleaner.java
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/Reloader.java
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/RepositoryManager.java
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/ResourceEntry.java
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
  appserver/web/war-util/src/test/java/org/glassfish/web/loader/WebappClassLoaderTest.java
  appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.java
  appserver/web/web-core/src/main/java/org/apache/catalina/loader/StandardClassLoader.java
  appserver/web/web-core/src/main/java/org/apache/catalina/loader/WebappLoader.java
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/VirtualServer.java
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModule.java
  appserver/web/web-naming/src/main/java/org/apache/naming/resources/JarFileResourcesProvider.java
  appserver/web/web-naming/src/main/java/org/apache/naming/resources/WebDirContext.java
  nucleus/common/common-util/src/main/java/org/glassfish/common/util/GlassfishUrlClassLoader.java
  nucleus/common/common-util/src/test/java/org/glassfish/common/util/GlassfishUrlClassLoaderTest.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/GlassfishBootstrapClassLoader.java
  nucleus/deployment/common/src/main/java/org/glassfish/deployment/common/DeploymentContextImpl.java
Labels: enhancement

#24248 Security fix: regexp catastrophic backtracking fix
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/parser/ODLLogParser.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/GlassFishLogManager.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/cfg/ConfigurationHelper.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/formatter/LogFormatDetector.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/cfg/ConfigurationHelperTest.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/cfg/LoggingPropertiesTest.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/formatter/LogFormatDetectorTest.java
  nucleus/glassfish-jul-extension/src/test/resources/logging.properties
Labels: security fix

#24247 Classloader security - the fixed package.policy parameter
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
  appserver/web/web-core/src/main/java/org/apache/catalina/core/ApplicationContextFacade.java
  appserver/web/web-core/src/main/java/org/apache/catalina/loader/WebappLoader.java
  appserver/web/web-core/src/main/java/org/apache/catalina/security/SecurityConfig.java
  appserver/web/web-core/src/main/java/org/apache/catalina/security/SecurityUtil.java
  nucleus/admin/template/src/main/resources/config/logging.properties
Labels: security fix

#24253 Integrate Angus 2.0.0
  nucleus/parent/pom.xml
Labels: component upgrade, ee10-component

#24251 Fixed dependency on LANG env property in QL tests
  gftest.sh
Labels: build and test improvement

#24254 Integrate Jboss Class file writer 1.3.0
  appserver/pom.xml
  nucleus/distributions/nucleus-common/src/main/resources/config/osgi.properties
  nucleus/osgi-platforms/felix/src/main/resources/config/osgi.properties
Labels: component upgrade

#24256 Integrate JNA 5.13.0
  appserver/libpam4j/pom.xml
Labels: component upgrade

#24264 Integrate Soteria 3.0.2
  appserver/pom.xml
Labels: component upgrade, ee10-component

#24260 Uberjar compilable again
  appserver/extras/embedded/common/bootstrap/src/main/java/com/sun/enterprise/glassfish/.gitkeep_empty_dir
  appserver/extras/embedded/common/bootstrap/src/main/java/org/glassfish/uberjar/UberJarMain.java
  appserver/extras/embedded/common/bootstrap/src/main/java/org/glassfish/uberjar/activator/UberJarGlassFishActivator.java
  appserver/extras/embedded/common/bootstrap/src/main/java/org/glassfish/uberjar/bootstrap/UberJarOSGiGlassFishRuntimeBuilder.java
  appserver/extras/embedded/common/installroot-builder/pom.xml
  appserver/extras/embedded/common/instanceroot-builder/pom.xml
  appserver/extras/embedded/pom.xml
  appserver/extras/pom.xml
  nucleus/common/simple-glassfish-api/src/main/java/org/glassfish/embeddable/BootstrapProperties.java
  nucleus/common/simple-glassfish-api/src/main/java/org/glassfish/embeddable/GlassFishProperties.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/osgi/OSGiGlassFishRuntimeBuilder.java
  nucleus/core/kernel/src/main/java/org/glassfish/kernel/embedded/EmbeddedDomainXml.java
Labels: bug

#24266 Integrate Helidon Config 3.1.0
  appserver/pom.xml
Labels: component upgrade

#24268 New Docker image
  appserver/distributions/docker/pom.xml
  appserver/distributions/docker/src/main/docker/Dockerfile
  appserver/distributions/docker/src/main/docker/run-glassfish.sh
  appserver/distributions/pom.xml
  etc/docker-jdk17/Dockerfile
  etc/docker-jdk17/Makefile
  etc/docker-jdk17/entrypoint.sh
  etc/docker/.dockerignore
  etc/docker/.gitignore
  etc/docker/Dockerfile
  etc/docker/Makefile
  etc/docker/entrypoint.sh
Labels: enhancement

#24269 Several small tooling updates
  nucleus/parent/pom.xml
Labels: build and test improvement, dependencies

#24270 Add runtime dependencies for embedded jars
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/web/pom.xml
Labels: bug

#24271 Fixed error messages in logs
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/ReferenceCleaner.java
Labels: bug

#24273 Fix for servlet tck - updated ApplicationContextFacade
  appserver/web/web-core/src/main/java/org/apache/catalina/core/ApplicationContextFacade.java
  appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.java
  appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardWrapper.java
  appserver/web/web-core/src/main/java/org/apache/catalina/security/SecurityUtil.java
Labels: bug

#24275 Unpack glassfish-jar type for embedded-web
  appserver/extras/embedded/web/pom.xml
  appserver/extras/embedded/web/src/assembly/package.xml
Labels: bug

#24279 Code cleanup, which may fix Faces TCK WebSocket test
  appserver/web/web-core/src/main/java/org/apache/catalina/core/ApplicationContext.java
  appserver/web/web-core/src/main/java/org/apache/catalina/core/ApplicationContextFacade.java
  appserver/web/web-core/src/main/java/org/apache/catalina/core/ContainerBase.java
  appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.java
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/ContextFacade.java
Labels: bug, code cleaning

#24285 Integrate Jersey 3.1.1
  nucleus/parent/pom.xml
Labels: component upgrade, ee10-component

#24286 Integrate Nimbus 9.30
  appserver/pom.xml
Labels: component upgrade
