Repository eclipse-ee4j/glassfish, pull requests merged in 2023-10, with the labels that each got.

#24617 Fixed dependency on OS settings of java
  appserver/itest-tools/src/main/java/org/glassfish/main/itest/tools/asadmin/Asadmin.java
Labels: bug

#24605 Using glassfishbuild-maven-plugin 4.0.0 + fixes
  Jenkinsfile
  README.md
  appserver/distributions/glassfish-common/pom.xml
  appserver/distributions/glassfish-common/src/main/assembly/glassfish-common.xml
  appserver/distributions/glassfish/pom.xml
  appserver/distributions/glassfish/src/main/assembly/glassfish.xml
  appserver/distributions/pom.xml
  appserver/distributions/web/pom.xml
  appserver/distributions/web/src/main/assembly/web.xml
  nucleus/distributions/atomic/pom.xml
  nucleus/distributions/atomic/src/main/assembly/atomic.xml
  nucleus/distributions/nucleus-common/pom.xml
  nucleus/distributions/nucleus/pom.xml
  nucleus/distributions/pom.xml
  nucleus/osgi-platforms/felix/pom.xml
  nucleus/osgi-platforms/felix/src/main/resources/glassfish/config/.gitkeep_empty_dir
  nucleus/osgi-platforms/felix/src/main/resources/glassfish/modules/autostart/.gitkeep_empty_dir
  nucleus/osgi-platforms/felix/src/main/resources/glassfish/osgi/felix/conf/.gitkeep_empty_dir
  nucleus/parent/pom.xml
  nucleus/pom.xml
  pom.xml
Labels: build and test improvement

#24606 Fixing builds on Windows
  appserver/extras/embedded/tests/src/test/java/org/glassfish/main/extras/embedded/test/all/StartupITest.java
  appserver/itest-tools/src/main/java/org/glassfish/main/itest/tools/asadmin/DetachedTerseAsadminResult.java
  appserver/itest-tools/src/test/java/org/glassfish/main/admin/test/tool/StartStopITest.java
  appserver/libpam4j/src/test/java/org/jvnet/libpam/UnixUserTest.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/web/jsp/JspReloadGeneratedServletIfUpdatedTest.java
  nucleus/admin/launcher/src/test/java/com/sun/enterprise/admin/launcher/GFLauncherTest.java
  nucleus/common/common-util/src/test/java/org/glassfish/common/util/admin/locking/FileLockTest.java
  nucleus/deployment/common/src/test/java/com/sun/enterprise/deploy/shared/FileArchiveTest.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/formatter/ODLLogFormatter.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/GlassFishLogManagerLifeCycleTest.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/formatter/ODLLogFormatterTest.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/formatter/OneLineFormatterTest.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/formatter/UniformLogFormatterTest.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/handler/HandlerConfigurationHelperTest.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/handler/SimpleLogHandlerTest.java
  nucleus/parent/pom.xml
Labels: bug, build and test improvement

#24623 Disable lockAndRenameTest on Mac. The OS just doesn't guarantee this.
  nucleus/common/common-util/src/test/java/org/glassfish/common/util/admin/locking/FileLockTest.java
Labels: build and test improvement

#24624 Integrate WaSP 3.2.1
  appserver/pom.xml
Labels: component upgrade, ee10-component

#24625 Deprecated XMLInputFactory.newInstance replaced by newFactory
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/RestResponse.java
  appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/embedded/DomainXmlTransformer.java
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/perms/PermissionXMLParser.java
  nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/modularity/parser/ModuleXMLConfigurationFileParser.java
  nucleus/admin/config-api/src/main/java/org/glassfish/config/support/DefaultConfigUpgrade.java
  nucleus/admin/config-api/src/test/java/org/glassfish/config/support/DomainXmlPreParserTest.java
  nucleus/admin/rest/rest-client/src/main/java/org/glassfish/admin/rest/client/utils/MarshallingUtils.java
  nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/ImportSyncBundleCommand.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/xml/XmlParserHelper.java
  nucleus/common/internal-api/src/main/java/org/glassfish/internal/deployment/GenericSniffer.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/StAXParserFactory.java
  nucleus/deployment/common/src/main/java/com/sun/enterprise/deploy/shared/AbstractArchiveHandler.java
  nucleus/flashlight/framework/src/main/java/org/glassfish/flashlight/xml/StaxParser.java
  nucleus/hk2-config-generator/src/main/java/org/jvnet/hk2/config/ConfigParser.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/embedded/EmbeddedSecurityUtil.java
Labels: code cleaning

#24627 Fixed NPE - the unusedJarsCheck is sometimes null
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/JarFileManager.java
Labels: bug

#24628 Fix `list-persistence-types` asadmin command
  appserver/common/container-common/src/main/java/org/glassfish/ha/commands/ListPersistenceTypesCommand.java
Labels: bug

#24629 Docs pushed to the end of the build
  Jenkinsfile
  pom.xml
Labels: build and test improvement

#24620 Integrate HK2 3.0.5 and ASM 9.6
  nucleus/parent/pom.xml
Labels: component upgrade, dependencies

#24631 Fix instance synchronization
  appserver/tests/application/src/main/resources/org/glassfish/main/test/app/synchronize/index.html
  appserver/tests/application/src/main/resources/org/glassfish/main/test/app/synchronize/sample.json
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/synchronize/SynchronizeStandaloneInstanceTest.java
  nucleus/common/common-util/src/main/java/org/glassfish/admin/payload/PayloadImpl.java
Labels: bug, build and test improvement

#24633 Integrate Stax 2 API 4.2.2
  appserver/pom.xml
Labels: component upgrade

#24634 Integrate Weld 5.1.2
  appserver/pom.xml
  appserver/tests/tck/cdi/cdi-full/pom.xml
Labels: component upgrade, ee10-component

#24635 Refactor and clean login modules
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/auth/realm/pam/PamRealm.java
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/auth/login/DigestLoginModule.java
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/auth/login/JDBCDigestLoginModule.java
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/auth/login/JDBCLoginModule.java
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/auth/login/PamLoginModule.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/BasePasswordLoginModule.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/login/ClientCertificateLoginModule.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/login/ClientPasswordLoginModule.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/login/DigestCredentials.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/login/DistinguishedPrincipalCredential.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/login/FileLoginModule.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/login/LDAPLoginModule.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/login/PasswordLoginModule.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/login/SolarisLoginModule.java
Labels: build and test improvement

#24639 Fix the startserv script for Mac OS
  appserver/distributions/glassfish-common/src/main/resources/bin/startserv
  nucleus/distributions/nucleus-common/src/main/resources/bin/startserv
Labels: bug

#24225 New XmlSec4 without mandatory SLF4J
  appserver/distributions/glassfish/pom.xml
  appserver/distributions/glassfish/src/main/patches/webservices-api-osgi/META-INF/MANIFEST.MF
  appserver/distributions/glassfish/src/main/patches/webservices-extra-xmlsec/META-INF/MANIFEST.MF
  appserver/distributions/glassfish/src/main/patches/webservices-osgi/META-INF/MANIFEST.MF
  appserver/distributions/glassfish/src/main/patches/xmlsec/META-INF/MANIFEST.MF
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/shell/glassfish-embedded-static-shell/pom.xml
  appserver/featuresets/glassfish/pom.xml
  appserver/pom.xml
  appserver/security/webservices.security/pom.xml
  appserver/security/webservices.security/src/test/java/org/glassfish/main/security/webservices/WSServletContainerInitializerITest.java
  nucleus/parent/pom.xml
Labels: enhancement, build and test improvement

#24648 Integrate EclipseLink ASM 9.6.0
  appserver/pom.xml
Labels: component upgrade

#24372 disable date in hk2 generated files
  nucleus/parent/pom.xml
Labels: build and test improvement

#24649 Integrate Jakarta SOAP (XMLWSAPI) 4.0.1 and JAXB implementation 4.0.4
  nucleus/parent/pom.xml
Labels: component upgrade, ee10-component

#24650 Integrate Jakarta JSON-P 2.1.3 and implementation Parsson 1.1.5
  appserver/pom.xml
Labels: component upgrade, ee10-component

#24651 Integrate Commons IO 2.14.0
  nucleus/parent/pom.xml
Labels: component upgrade

#24652 Integrate Classmate 1.6.0
  nucleus/parent/pom.xml
Labels: component upgrade

#24653 Legacy classes can remain in old package - already deprecated for removal
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/jacc/provider/SimplePolicyConfigurationFactory.java
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/jacc/provider/SimplePolicyProvider.java
Labels: ee10-tck

#24654 Integrate Nimbus Jose JWT 9.37
  appserver/pom.xml
Labels: component upgrade

#24655 Avoid protocol relative redirects
  appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/FormAuthenticator.java
Labels: security fix

#24656 Update test tools checkstyle and jacoco
  appserver/tests/appserv-tests/devtests/security/jaccApi/prog-auth/common/pom.xml
  appserver/tests/embedded/inplanted/pom.xml
  appserver/tests/embedded/web/autodelete/pom.xml
  nucleus/parent/pom.xml
  pom.xml
Labels: build and test improvement

#24657 Update pom.xml EE4J parent to 1.0.9
  pom.xml
Labels: build and test improvement

#24658 Integrate JLine 3.23
  nucleus/parent/pom.xml
Labels: component upgrade

#24659 Integrate Commons IO 2.15
  nucleus/parent/pom.xml
Labels: component upgrade

#24660 Integrate JSCH 0.2.12
  appserver/pom.xml
  nucleus/parent/pom.xml
Labels: component upgrade

#24661 Use GlassFish Build Maven plugin 4.0.0
  nucleus/parent/pom.xml
Labels: build and test improvement

#24663 Webpage update for 7.0.10
  docs/website/src/main/resources/README.md
  docs/website/src/main/resources/download.md
  docs/website/src/main/resources/download_gf7.md
Labels: Documentation

#24638 Fixes naming context propagation in `ContextSetupProviderImpl`
  appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java
  nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/ComponentInvocation.java
Labels: bug

#24666 Updated glassfish.version.7x to 7.0.10
  docs/pom.xml
Labels: Documentation

#24667 Documentation artifact was not deployed for 7.0.10
  Jenkinsfile
  README.md
  appserver/tests/pom.xml
  docs/pom.xml
  pom.xml
Labels: bug, build and test improvement

#24668 Add runner for Activation TCK
  appserver/tests/tck/activation/pom.xml
  appserver/tests/tck/pom.xml
  appserver/tests/tck/tck-download/jakarta-activation-tck/pom.xml
  appserver/tests/tck/tck-download/pom.xml
Labels: build and test improvement
