Repository eclipse-ee4j/glassfish, pull requests merged in 2023-08, with the labels that each got.

#24528 Fix #24527 Admin Console behavior when admin user changes password to empty has changed compared to before
  appserver/admingui/common/src/main/resources/js/adminjsf.js
Labels: bug

#24531 Fixed unit test compatibility with JDK21
  nucleus/core/bootstrap/src/test/java/com/sun/enterprise/glassfish/bootstrap/MainHelperTest.java
Labels: build and test improvement

#24535 Fixed ElementStarITest and TokenAuthenticationITest
  nucleus/core/kernel/pom.xml
Labels: bug

#24533 Optimize CDI extensions to reduce unnecessary PAT handler calls
  appserver/jms/gf-jms-injection/src/main/java/org/glassfish/jms/injection/JMSCDIExtension.java
  appserver/web/web-sse/src/main/java/org/glassfish/sse/impl/ServerSentEventCdiExtension.java
  appserver/web/weld-integration/src/main/java/org/glassfish/cdi/rest/RestExtension.java
Labels: enhancement

#24530 Fix webapp Multi-Release JAR processing
  appserver/tests/application/pom.xml
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/web/mrjar/MultiReleaseApplication.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/web/mrjar/MultiReleaseResource.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/web/mrjar/MultiReleaseServlet.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/web/mrjar/MultiReleaseServletContainerInitializer.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/web/mrjar/Version.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/web/mrjar/VersionImpl.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/web/mrjar/MultiReleaseServletContainerInitializerTest.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/web/mrjar/MultiReleaseTestBase.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/web/mrjar/MultiReleaseWebApplicationTest.java
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/JarFileManager.java
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/ServletContainerInitializerUtil.java
Labels: bug, build and test improvement

#24538 Fix Java 11 compatibility issue in RWLockDataStructureTest
  appserver/connectors/connectors-runtime/src/test/java/com/sun/enterprise/resource/pool/datastructure/RWLockDataStructureTest.java
Labels: bug

#24542 Add no-interface view Enterprise Bean application test
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/ejb/NoInterfaceViewApplication.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/ejb/NoInterfaceViewEJB.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/ejb/NoInterfaceViewResource.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/ejb/NoInterfaceViewEJBTest.java
Labels: build and test improvement

#24536 Add MicroProfile Rest Client TCK
  appserver/tests/tck/microprofile/config/pom.xml
  appserver/tests/tck/microprofile/pom.xml
  appserver/tests/tck/microprofile/rest-client/pom.xml
  appserver/tests/tck/microprofile/rest-client/src/main/java/org/glassfish/microprofile/rest/client/tck/RestClientArquillianExtension.java
  appserver/tests/tck/microprofile/rest-client/src/main/java/org/glassfish/microprofile/rest/client/tck/client/BeansXmlTransformer.java
  appserver/tests/tck/microprofile/rest-client/src/main/java/org/glassfish/microprofile/rest/client/tck/client/MicroprofileConfigPropertiesIncluder.java
  appserver/tests/tck/microprofile/rest-client/src/main/java/org/glassfish/microprofile/rest/client/tck/client/WireMockLibraryIncluder.java
  appserver/tests/tck/microprofile/rest-client/src/main/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  appserver/tests/tck/microprofile/rest-client/src/main/resources/beans.xml
  appserver/tests/tck/microprofile/rest-client/tck-suite.xml
Labels: build and test improvement

#24549 Build GlassFish Embedded artifacts as Multi-Release JARs
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/nucleus/pom.xml
  appserver/extras/embedded/web/pom.xml
Labels: bug, build and test improvement

#24550 Update Arquillian artifacts in MicroProfile TCK
  appserver/tests/tck/microprofile/pom.xml
Labels: component upgrade, build and test improvement

#24553 Integrate Parsson 1.1.4
  appserver/pom.xml
Labels: component upgrade, ee10-component

#24544 Propagate JNDI context if none exists
  appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java
  appserver/tests/tck/concurrency/pom.xml
  nucleus/common/glassfish-api/src/main/java/org/glassfish/api/invocation/ComponentInvocation.java
Labels: bug

#24554 Fix processing of the Multi-Release libraries in EAR application
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/mrjar/Version.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/mrjar/VersionImpl.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/mrjar/servlet/MultiReleaseServlet.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/mrjar/servlet/MultiReleaseServletContainerInitializer.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/mrjar/webapp/MultiReleaseApplication.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/mrjar/webapp/MultiReleaseResource.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/mrjar/MultiReleaseTestBase.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/mrjar/ear/MultiReleaseEnterpriseApplicationLibraryTest.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/mrjar/servlet/MultiReleaseServletContainerInitializerTest.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/mrjar/webapp/MultiReleaseWebApplicationTest.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/ASURLClassLoader.java
Labels: bug

#24547 Startserv script - support help argument, fix handling errors
  appserver/distributions/glassfish-common/src/main/resources/bin/startserv
  nucleus/distributions/nucleus-common/src/main/resources/bin/startserv
Labels: bug

#24555 Add runners for the standalone Connectors TCK
  appserver/tests/tck/connectors/pom.xml
  appserver/tests/tck/pom.xml
  appserver/tests/tck/tck-download/jakarta-connectors-tck/pom.xml
  appserver/tests/tck/tck-download/pom.xml
Labels: build and test improvement

#24557 Add missing JSON-P API to `glassfish-embedded-*.jar`s
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/web/pom.xml
Labels: bug

#24556 Integrate Mojarra 4.0.3
  appserver/pom.xml
Labels: component upgrade, ee10-component

#24559 Update test dependencies (junit, jmh, checkstyle)
  nucleus/parent/pom.xml
Labels: build and test improvement, dependencies

#24563 Integrate Felix webconsole 4.8.12
  nucleus/parent/pom.xml
Labels: component upgrade

#24565 Webpage update for 7.0.8
  docs/website/src/main/resources/README.md
  docs/website/src/main/resources/download.md
  docs/website/src/main/resources/download_gf7.md
Labels: Documentation

#24567 More stable ProgressStatusComplexITest
  appserver/tests/admin/admin-extension/src/main/java/com/sun/enterprise/tests/progress/ProgressComplexCommand.java
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/progress/ProgressStatusComplexITest.java
  nucleus/common/glassfish-api/src/main/java/org/glassfish/api/admin/ProgressStatus.java
Labels: build and test improvement

#24566 Fixes generated EJB remote interfaces loading in Embedded GlassFish
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/EJBUtils.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/AsmSerializableBeanGenerator.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/ClassGenerator.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/Generator.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/Remote30WrapperGenerator.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/RemoteGenerator.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/ServiceInterfaceGenerator.java
  appserver/extras/embedded/tests/pom.xml
  appserver/extras/embedded/tests/src/main/java/org/glassfish/main/extras/embedded/test/app/ejb/RemoteBean.java
  appserver/extras/embedded/tests/src/main/java/org/glassfish/main/extras/embedded/test/app/ejb/RemoteInterface.java
  appserver/extras/embedded/tests/src/test/java/org/glassfish/main/extras/embedded/test/all/StartupITest.java
  appserver/extras/embedded/tests/src/test/java/org/glassfish/main/extras/embedded/test/all/deployment/RemoteDeploymentITestBase.java
  appserver/extras/embedded/tests/src/test/java/org/glassfish/main/extras/embedded/test/all/deployment/ear/RemoteEarDeploymentITest.java
  appserver/extras/embedded/tests/src/test/java/org/glassfish/main/extras/embedded/test/all/deployment/ejb/RemoteEjbJarDeploymentITest.java
  appserver/extras/embedded/tests/src/test/java/org/glassfish/main/extras/embedded/test/all/deployment/webapp/RemoteWebAppDeploymentITest.java
  nucleus/test-utils/src/main/java/org/glassfish/tests/utils/ServerUtils.java
Labels: bug
