Repository eclipse-ee4j/glassfish, pull requests merged in 2023-06, with the labels that each got.

#24442 Integrate Jackson 2.15.2
  nucleus/parent/pom.xml
Labels: component upgrade

#24443 Integrate JSFTemplating 4.0.2 and Woodstock 6.0.1
  appserver/pom.xml
Labels: component upgrade

#24444 More timeouts in admin commands and Admin Console
  appserver/admingui/cluster/src/main/resources/shared/handlers.inc
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/ClusterHandler.java
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/CommonHandlers.java
  appserver/admingui/common/src/main/resources/shared/commonHandlers.inc
  nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/ClusterOperationUtil.java
  nucleus/cluster/common/src/main/java/com/sun/enterprise/util/cluster/InstanceInfo.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/SystemPropertyConstants.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/net/NetUtils.java
Labels: enhancement

#24449 Fix OSGiShellCommand Test Error
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/OSGiCommandsITest.java
Labels: build and test improvement

#24447 Update latest docs to 7.0.5 on the website
  RELEASE.md
  docs/pom.xml
  docs/publish/pom.xml
Labels: Documentation

#24446 Refactor ProcessManager to Use ProcessBuilder
  appserver/itest-tools/src/main/java/org/glassfish/main/itest/tools/asadmin/Asadmin.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/process/ProcessManager.java
  nucleus/common/common-util/src/test/java/com/sun/enterprise/universal/process/ProcessManagerTest.java
Labels: code cleaning, build and test improvement

#24451 Add fine-grained bytecode preprocessing tracking in WebappClassLoader
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
Labels: bug, code cleaning

#24452 Integrate Soteria 3.0.3
  appserver/pom.xml
Labels: component upgrade, ee10-component

#24448 Fix bytecode transformation in the ASURLClassLoader
  nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/ASURLClassLoader.java
Labels: bug

#24453 Remove com.sun.enterprise.util.ProcessExecutor
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/KeystoreManager.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/services/SMFService.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/process/ProcessManager.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/ProcessExecutor.java
Labels: code cleaning

#24454 Updated several dependencies
  appserver/pom.xml
  appserver/tests/tck/rest_cdi/pom.xml
  nucleus/parent/pom.xml
  pom.xml
Labels: dependencies

#24460 Attempt to delete JDBC resource ref only if it exists
  appserver/jdbc/admin/src/main/java/org/glassfish/jdbc/admin/cli/JDBCResourceManager.java
  appserver/jdbc/admin/src/main/java/org/glassfish/jdbc/admin/cli/LocalStrings.properties
Labels: bug

#24456 Add docs distribution artifact to mvn deploy plugin for Jenkins.
  docs/distribution/pom.xml
  docs/pom.xml
  pom.xml
Labels: Documentation

#24468 Suppress printing to console in the ProcessManagerTest
  nucleus/common/common-util/src/test/java/com/sun/enterprise/universal/process/ProcessManagerTest.java
Labels: build and test improvement

#24465 Jenkinsfile and StartStopITest
  Jenkinsfile
  appserver/itest-tools/src/main/java/org/glassfish/main/itest/tools/GlassFishTestEnvironment.java
  appserver/itest-tools/src/main/java/org/glassfish/main/itest/tools/asadmin/Asadmin.java
Labels: build and test improvement

#24467 General cleaning after removal the ProcessExecutor
  appserver/tests/paas/ext-shared-service-enable-disable-test/src/test/java/org/glassfish/tests/paas/enabledisable/ExtSharedServiceEnableDisableTest.java
  appserver/tests/paas/external-and-shared-service/src/test/java/org/glassfish/tests/paas/external_and_shared_service/SharedAndExternalServiceTest.java
  appserver/tests/paas/multiple-spe-test/mydb-plugin/src/main/java/org/glassfish/paas/mydbplugin/MyDBPlugin.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/RepositoryManager.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/services/SMFService.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/ExecException.java
Labels: code cleaning

#24466 Drop timestamp from version string/product id info
  appserver/distributions/glassfish-common/src/main/resources/glassfish/config/branding/glassfish-version.properties
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/AsadminVersionITest.java
  docs/add-on-component-development-guide/src/main/asciidoc/extending-asadmin.adoc
  nucleus/common/common-util/src/main/java/com/sun/appserv/server/util/Version.java
  nucleus/common/common-util/src/test/java/com/sun/appserv/server/util/VersionTest.java
  nucleus/common/common-util/src/test/resources/config/branding/test-branding.properties
  nucleus/parent/pom.xml
Labels: code cleaning

#24455 Switch to a fork of jsch (com.github.mwiede) and upgrade to 0.2.9
  appserver/extras/embedded/shell/glassfish-embedded-static-shell/pom.xml
  appserver/extras/embedded/web/pom.xml
  nucleus/admin/template/src/main/resources/config/logging.properties
  nucleus/cluster/ssh/pom.xml
  nucleus/cluster/ssh/src/main/java/org/glassfish/cluster/ssh/launcher/JavaSystemJschLogger.java
  nucleus/cluster/ssh/src/main/java/org/glassfish/cluster/ssh/launcher/SSHLauncher.java
  nucleus/featuresets/nucleus/pom.xml
  nucleus/parent/pom.xml
Labels: component upgrade

#24470 MicroProfile Rest Client 3.0 (via jersey-mp-rest-client)
  appserver/distributions/glassfish/pom.xml
  appserver/distributions/glassfish/src/main/patches/microprofile-rest-client-api/META-INF/MANIFEST.MF
  appserver/featuresets/glassfish/pom.xml
  appserver/pom.xml
Labels: enhancement

#24472 In fastest mode (-Pfastest) we don't need to build the docs
  nucleus/parent/pom.xml
  pom.xml
Labels: build and test improvement

#24473 Fix for botched #24472
  nucleus/parent/pom.xml
  pom.xml
Labels: bug

#24474 Integrate EclipseLink 4.0.2
  appserver/pom.xml
Labels: component upgrade, ee10-component

#24475 OSGI vs Java 11+
  appserver/appclient/server/core/src/main/java/org/glassfish/appclient/server/core/jws/AppClientHTTPAdapter.java
  appserver/appclient/server/core/src/main/java/org/glassfish/appclient/server/core/jws/LoaderConfigContent.java
  appserver/distributions/glassfish/pom.xml
  appserver/distributions/glassfish/src/main/patches/jaxb-osgi/META-INF/MANIFEST.MF
  appserver/distributions/web/pom.xml
  appserver/distributions/web/src/main/patches/jaxb-osgi/META-INF/MANIFEST.MF
  appserver/extras/embedded/common/bootstrap/osgi.bundle
  appserver/extras/embedded/common/bootstrap/pom.xml
  appserver/extras/embedded/common/bootstrap/src/main/java/org/glassfish/uberjar/bootstrap/UberJarOSGiGlassFishRuntimeBuilder.java
  nucleus/common/simple-glassfish-api/osgi.bundle
  nucleus/core/bootstrap/osgi.bundle
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/MainHelper.java
  nucleus/distributions/nucleus-common/pom.xml
  nucleus/distributions/nucleus-common/src/main/resources/config/osgi.properties
  nucleus/osgi-platforms/felix/pom.xml
  nucleus/osgi-platforms/felix/src/main/resources/config/osgi.properties
Labels: bug, code cleaning

#24476 Fix for TCK failure after implementing #24049
  appserver/featuresets/web/pom.xml
  appserver/web/weld-integration/pom.xml
  appserver/web/weld-integration/src/main/java/org/glassfish/cdi/rest/RestExtension.java
  appserver/web/weld-integration/src/main/resources/META-INF/services/jakarta.enterprise.inject.spi.Extension
Labels: bug, ee10-tck

#24477 Integrate CDI TCK 4.0.10 in TCK test
  appserver/tests/tck/cdi/cdi-full/pom.xml
  appserver/tests/tck/cdi/cdi-full/src/test/java/org/jboss/weld/tck/glassfish/GlassFishDeploymentExceptionTransformer.java
  appserver/tests/tck/cdi/cdi-model/pom.xml
Labels: build and test improvement

#24481 Webpage update for 7.0.6
  docs/website/src/main/resources/README.md
  docs/website/src/main/resources/download.md
  docs/website/src/main/resources/download_gf7.md
Labels: Documentation
