Repository eclipse-ee4j/glassfish, pull requests merged in 2023-12, with the labels that each got.

#24697 Fix auto login admin ui by accidentally changed constant
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/cli/SecurityUtil.java
Labels: bug

#24700 Fixed several possible issues with rolling log files
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/rotation/LogFileManager.java
Labels: bug

#24702 fix cmtTimeoutInSeconds config, it can't take effect when set value 0 in admin UI.
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBContainerTransactionManager.java
  appserver/transaction/internal-api/src/main/java/com/sun/enterprise/transaction/config/TransactionService.java
Labels: bug

#24706 Integrate Jersey 3.1.5
  nucleus/parent/pom.xml
Labels: component upgrade, ee10-component

#24707 Fix for the RecoveryManager's Resync Timeout
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBContainerTransactionManager.java
  appserver/transaction/internal-api/src/main/java/com/sun/enterprise/transaction/config/TransactionService.java
  appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/RecoveryManager.java
  appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/TransactionFactoryImpl.java
Labels: bug

#24711 Integrate Jackson 2.16.0
  nucleus/parent/pom.xml
Labels: component upgrade

#24709 Fix: The startserv script didn't report errors correctly
  appserver/distributions/glassfish-common/src/main/resources/bin/asadmin
  appserver/distributions/glassfish-common/src/main/resources/bin/startserv
  appserver/distributions/glassfish-common/src/main/resources/glassfish/bin/asadmin
  nucleus/distributions/nucleus-common/src/main/resources/bin/startserv
Labels: bug

#24713 Integrate Grizzly 4.0.2
  nucleus/parent/pom.xml
Labels: component upgrade
