Repository eclipse-ee4j/glassfish, pull requests merged in 2023-02, with the labels that each got.

#24287 Integrate Web Services 4.0.2 (SOAP)
  nucleus/parent/pom.xml
Labels: component upgrade, ee10-component

#24289 Update website for 7.0.1 release
  docs/website/src/main/resources/README.md
  docs/website/src/main/resources/download_gf7.md
Labels: Documentation

#24290 Integrate Mojarra 4.0.1
  appserver/pom.xml
Labels: component upgrade, ee10-component

#24291 Add TCK runner for Pages Tags TCK
  appserver/tests/tck/pages_tags/pom.xml
  appserver/tests/tck/pom.xml
  appserver/tests/tck/tck-download/jakarta-pages-tags-tck/pom.xml
  appserver/tests/tck/tck-download/pom.xml
Labels: build and test improvement

#24292 Integrate WaSP 3.2.0
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/shell/glassfish-embedded-static-shell/pom.xml
  appserver/extras/embedded/web/pom.xml
  appserver/featuresets/web/pom.xml
  appserver/pom.xml
  appserver/tests/tck/pages/pom.xml
  appserver/tests/v2-tests/appserv-tests/sqetests/jsfcomponents/src/demo/taglib/EscapeHtmlTag.java
  appserver/web/jsf-connector/src/main/java/org/glassfish/faces/integration/GlassFishTldProvider.java
  appserver/web/jstl-connector/pom.xml
  appserver/web/jstl-connector/src/main/java/org/glassfish/jstl/integration/GlassFishTldProvider.java
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
Labels: component upgrade, ee10-component

#24293 Integrate eclipselink:4.0.1-RC1
  appserver/pom.xml
Labels: component upgrade, ee10-component

#24294 Integrate Angus Mail 2.0.1
  nucleus/parent/pom.xml
Labels: component upgrade, ee10-component

#24295 Increase timeout from 2_000_000d to 3_000_000d.
  appserver/ejb/ejb-container/src/test/java/com/sun/ejb/EjbClassGeneratorFactoryBenchmarkTest.java
Labels: build and test improvement

#24299 Integrate Tyrus 2.1.3
  appserver/pom.xml
Labels: component upgrade, ee10-component

#24300 Fixed #24297: getResource for a directory
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/RepositoryManager.java
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
  appserver/web/war-util/src/test/java/org/glassfish/web/loader/WebappClassLoaderTest.java
  appserver/web/web-naming/src/main/java/org/apache/naming/resources/FileDirContext.java
  appserver/web/web-naming/src/main/java/org/apache/naming/resources/WebDirContext.java
Labels: bug

#24302 Setup config for the versions plug-in to ignore OLDER versions.
  nucleus/parent/pom.xml
Labels: build and test improvement

#24306 Integrate checkstyle 10.7.0
  nucleus/parent/pom.xml
Labels: build and test improvement

#24309 GlassFishLogManagerLifeCycleTest stabilized
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/GlassFishLogManagerLifeCycleTest.java
Labels: build and test improvement

#24311 Integrate Eclipselink 4.0.1-RC2
  appserver/pom.xml
Labels: component upgrade, ee10-component

#24252 Jenkinsfile maintenance
  Jenkinsfile
Labels: build and test improvement

#24315 Initial document detailing the release instructions for GlassFish
  RELEASE.md
Labels: build and test improvement

#24316 Issue #24284 Fixed git.build.time
  nucleus/parent/pom.xml
Labels: bug

#24320 Reorganized jenkinsfile
  Jenkinsfile
Labels: build and test improvement

#24325 Update website for 7.0.2 release
  docs/website/src/main/resources/README.md
  docs/website/src/main/resources/download_gf7.md
Labels: Documentation

#24319 Updated maven plugins
  appserver/pom.xml
  appserver/tests/jakartaee/concurrency/pom.xml
  appserver/tests/tck/concurrency/pom.xml
  appserver/tests/tck/microprofile/config/pom.xml
  appserver/tests/tck/microprofile/config/src/main/java/org/glassfish/microprofile/config/tck/client/LibraryIncluder.java
  appserver/tests/tck/microprofile/pom.xml
  nucleus/parent/pom.xml
  pom.xml
Labels: build and test improvement

#24321 Fixed StackOverflow in WebappClassLoader.getURLs + removed workaround
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/ReferenceCleaner.java
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
  appserver/web/war-util/src/test/java/org/glassfish/web/loader/WebappClassLoaderTest.java
Labels: bug

#24322 Revisited glassfish-version.properties and Version class
  appserver/admin/backup/src/main/java/com/sun/enterprise/backup/Status.java
  appserver/distributions/glassfish-common/pom.xml
  appserver/distributions/glassfish-common/src/main/resources/glassfish/config/branding/glassfish-version.properties
  appserver/pom.xml
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/AsadminUptimeITest.java
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/AsadminVersionITest.java
  appserver/tests/appserv-tests/devtests/admin/cli/src/admin/DomainTest.java
  appserver/tests/v2-tests/appserv-tests/devtests/admin/VersionPrinter.java
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebContainer.java
  docs/add-on-component-development-guide/src/main/asciidoc/extending-asadmin.adoc
  nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/CLICommand.java
  nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/VersionCommand.java
  nucleus/admin/config-api/src/main/java/org/glassfish/config/support/DefaultConfigUpgrade.java
  nucleus/admin/config-api/src/main/java/org/glassfish/config/support/GlassFishDocument.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/provider/ProviderUtil.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/CreateDomainCommand.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/domain/DomainBuilder.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/domain/SubstitutableTokens.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/impl/mbean/DomainRootImpl.java
  nucleus/common/common-util/src/main/java/com/sun/appserv/server/util/Version.java
  nucleus/common/common-util/src/main/java/com/sun/appserv/server/util/VersionInfoImpl.java
  nucleus/common/common-util/src/test/java/com/sun/appserv/server/util/VersionTest.java
  nucleus/common/common-util/src/test/resources/config/branding/test-branding.properties
  nucleus/common/glassfish-api/src/main/java/org/glassfish/api/VersionInfo.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/VersionCommand.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/adapter/AdminConsoleAdapter.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/AppServerStartup.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/SystemTasksImpl.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/GlassfishErrorPageGenerator.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/GlassfishNetworkListener.java
  nucleus/core/kernel/src/main/java/org/glassfish/kernel/KernelLoggerInfo.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java
  nucleus/parent/pom.xml
Labels: enhancement
