Repository eclipse-ee4j/glassfish, pull requests merged in 2023-09, with the labels that each got.

#24574 Add application tests for classloading-time bytecode preprocessing
  appserver/tests/application/pom.xml
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/persistence/transform/ejb/ClassTransformerBean.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/persistence/transform/provider/ClassTransformerImpl.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/persistence/transform/provider/Enhancer.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/persistence/transform/provider/EnhancerContext.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/persistence/transform/provider/EntityManagerFactoryImpl.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/persistence/transform/provider/EntityManagerImpl.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/persistence/transform/provider/PersistenceProviderImpl.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/persistence/transform/webapp/ClassTransformerApplication.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/persistence/transform/webapp/ClassTransformerResource.java
  appserver/tests/application/src/main/resources/org/glassfish/main/test/app/persistence/transform/persistence.xml
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/persistence/transform/ClassTransformerEjbWebAppTest.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/persistence/transform/ClassTransformerTestBase.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/persistence/transform/ClassTransformerWebAppTest.java
Labels: build and test improvement

#24569 Replace deprecated `isAccessible` method in all places
  appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/managedbean/ManagedBeanManagerImpl.java
  appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/util/InjectionManagerImpl.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/EJBUtils.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/BaseContainer.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EjbContainerServicesImpl.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/StatefulSessionContainer.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/interceptors/InterceptorManager.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/interceptors/SystemInterceptorProxy.java
  appserver/web/jsf-connector/src/main/java/org/glassfish/faces/integration/GlassFishInjectionProvider.java
  appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/WsUtil.java
  nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/PostConstructRunner.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/RuntimeInfo.java
Labels: deprecation

#24577 Enable GF Embedded test suite - part 2 (also fixes a NullPointerException in VirtualServer.java)
  appserver/tests/embedded/pom.xml
  appserver/tests/embedded/utils/pom.xml
  appserver/tests/embedded/web/autodelete/pom.xml
  appserver/tests/embedded/web/autodelete/src/main/java/deletion/HelloWorld.java
  appserver/tests/embedded/web/autodelete/src/test/java/org/glassfish/tests/embedded/web/autodelete/ServletMain.java
  appserver/tests/embedded/web/pom.xml
  appserver/tests/embedded/web/servlet/pom.xml
  appserver/tests/embedded/web/servlet/src/main/java/test/HelloWorld.java
  appserver/tests/embedded/web/web-all/pom.xml
  appserver/tests/embedded/web/web-all/src/test/java/org/glassfish/tests/weball/WebAllTest.java
  appserver/tests/embedded/web/web-api/pom.xml
  appserver/tests/embedded/web/web-api/src/main/java/org/glassfish/tests/embedded/web/TestCacaoList.java
  appserver/tests/embedded/web/web-api/src/main/java/org/glassfish/tests/webapi/TestListener.java
  appserver/tests/embedded/web/web-api/src/main/java/org/glassfish/tests/webapi/TestServlet.java
  appserver/tests/embedded/web/web-api/src/main/resources/embedded-webapi-tests.war
  appserver/tests/embedded/web/web-api/src/main/webapp/WEB-INF/web.xml
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/EmbeddedAddContextTest.java
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/EmbeddedAddHttpsListenerTest.java
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/EmbeddedAddListenerDefaultVSTest.java
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/EmbeddedAddServletAndFilterByClassNameTest.java
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/EmbeddedAddServletAndFilterByClassTest.java
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/EmbeddedAddServletDefaultVSTest.java
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/EmbeddedAddServletTest.java
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/EmbeddedAddWebListenerTest.java
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/EmbeddedClassLoaderTest.java
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/EmbeddedCreateContextTest.java
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/EmbeddedCreateServletAndFilterTest.java
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/EmbeddedCreateVirtualServerTest.java
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/EmbeddedGetContextsTest.java
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/EmbeddedJSPTest.java
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/EmbeddedRedeployTest.java
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/EmbeddedRemoveContextTest.java
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/EmbeddedRestartTest.java
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/EmbeddedSetConfigurationTest.java
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/EmbeddedSetDefaultWebXmlTest.java
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/EmbeddedSetDocRootTest.java
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/EmbeddedSetSecurityTest.java
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/EmbeddedVirtualServerHostNameTest.java
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/EmbeddedWebAPIDefaultStartTest.java
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/EmbeddedWebAPITest.java
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/EmbeddedWebTest.java
  appserver/tests/embedded/web/web-api/src/test/java/org/glassfish/tests/embedded/web/TestConfiguration.java
  appserver/tests/embedded/web/web-war/pom.xml
  appserver/tests/embedded/web/web-war/test/pom.xml
  appserver/tests/embedded/web/web-war/test/src/test/java/org/glassfish/tests/embedded/webwar/EmbeddedTest.java
  appserver/tests/embedded/web/web-war/war/pom.xml
  appserver/tests/embedded/web/web-war/web-fragment1/pom.xml
  appserver/tests/embedded/web/web-war/web-fragment2/pom.xml
  appserver/tests/embedded/web/web-war/web-fragment3/pom.xml
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/VirtualServer.java
Labels: build and test improvement

#24561 Log stacktrace only in FINE level when MANIFEST not found in deployed JAR
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/FilteringClassLoader.java
Labels: bug

#24580 Integrate Jakarta Concurrency API 3.0.3
  appserver/pom.xml
Labels: component upgrade, ee10-component

#24583 Integrate Mojarra 4.0.4
  appserver/pom.xml
Labels: component upgrade, ee10-component, ee10-tck

#24585 Update several maven plugins
  nucleus/parent/pom.xml
Labels: build and test improvement

#24590 Integrate Windows Service Wrapper 2.12.0
  docs/reference-manual/src/main/asciidoc/create-service.adoc
  nucleus/admin/server-mgmt/pom.xml
  nucleus/admin/server-mgmt/src/main/manpages/com/sun/enterprise/admin/servermgmt/cli/create-service.1
  nucleus/admin/server-mgmt/src/main/resources/lib/winsw.exe
Labels: bug, component upgrade

#24591 Fixes `stop-local-instance` command
  nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/process/ProcessUtils.java
Labels: bug

#24594 Fix #24593 Error message is not displayed when Undeploy fails in Admin Console.
  appserver/admingui/common/src/main/resources/applications/deployTableButtons.inc
Labels: bug

#24597 Integrate Exousia 2.1.1
  appserver/pom.xml
Labels: bug, component upgrade, ee10-component

#24598 Properly close deployment `WebappClassLoader`
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
Labels: bug

#24599 Integrate Nimbus 9.35
  appserver/pom.xml
Labels: component upgrade

#24601 Add application test for deployment on multiple virtual servers
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/deploy/SimpleApplication.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/deploy/SimpleResource.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/deploy/DeployOnVirtualServersTest.java
Labels: build and test improvement

#24602 Fix `list-virtual-servers` command description in Administration Guide
  docs/administration-guide/src/main/asciidoc/http_https.adoc
Labels: Documentation

#24603 Integrate ORB 4.2.5
  nucleus/parent/pom.xml
Labels: dependencies

#24610 Fixes `osgi-shell` asadmin command
  nucleus/osgi-platforms/osgi-cli-interactive/src/main/java/org/glassfish/osgi/cli/interactive/LocalOSGiShellCommand.java
Labels: bug

#24614 Integrate Grizzly 4.0.1
  Jenkinsfile
  appserver/tests/gftest.sh
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/SSLConfigurator.java
  nucleus/parent/pom.xml
Labels: component upgrade

#24611 Improve GlassFish process runtime type detection
  nucleus/common/common-util/src/main/java/org/glassfish/server/ServerEnvironmentImpl.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/StaticGlassFishRuntime.java
Labels: bug
