Repository eclipse-ee4j/glassfish, pull requests merged in 2023-11, with the labels that each got.

#24665 Clean unhandled messages in admingui
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/RestResponse.java
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/RestUtil.java
  appserver/admingui/core/src/main/java/org/glassfish/admingui/handlers/TableHandlers.java
  appserver/admingui/jms-plugin/src/main/java/org/glassfish/admingui/plugin/jms/JMXUtil.java
  appserver/admingui/jms-plugin/src/main/java/org/glassfish/admingui/plugin/jms/JmsHandlers.java
  appserver/admingui/plugin-service/src/main/java/org/glassfish/admingui/plugin/ConsolePluginService.java
Labels: enhancement

#24670 Make sure Activation TCK build fails when tests fails
  appserver/tests/tck/activation/pom.xml
Labels: build and test improvement

#24674 Added Pages Debug (aka DSOL) TCK
  appserver/tests/tck/pages_debugging/pom.xml
  appserver/tests/tck/pom.xml
  appserver/tests/tck/tck-download/jakarta-pages-debugging-tck/pom.xml
  appserver/tests/tck/tck-download/pom.xml
Labels: build and test improvement

#24671 Rename TCK "ant-based" to "platform"
  appserver/tests/tck/platform-tck-runner/pom.xml
  appserver/tests/tck/platform-tck-runner/src/main/java/org/glassfish/main/tests/tck/ant/TckConfiguration.java
  appserver/tests/tck/platform-tck-runner/src/main/java/org/glassfish/main/tests/tck/ant/TckRunner.java
  appserver/tests/tck/platform-tck-runner/src/main/java/org/glassfish/main/tests/tck/ant/io/ZipResolver.java
  appserver/tests/tck/platform-tck-runner/src/main/java/org/glassfish/main/tests/tck/ant/xml/JUnitResultsParser.java
  appserver/tests/tck/platform-tck-runner/src/main/java/org/glassfish/main/tests/tck/ant/xml/TimestampAdapter.java
  appserver/tests/tck/platform-tck-runner/src/main/resources/junit-results.xjb
  appserver/tests/tck/platform-tck-runner/src/main/resources/junit-results.xsd
  appserver/tests/tck/platform-tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/junit/TckTestExtension.java
  appserver/tests/tck/platform-tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/tests/ApplicationClientITest.java
  appserver/tests/tck/platform-tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/tests/AuthorizationITest.java
  appserver/tests/tck/platform-tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/tests/ConnectorITest.java
  appserver/tests/tck/platform-tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/tests/CustomITest.java
  appserver/tests/tck/platform-tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/tests/EjbITest.java
  appserver/tests/tck/platform-tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/tests/ExpressionLanguageITest.java
  appserver/tests/tck/platform-tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/tests/IntegrationITest.java
  appserver/tests/tck/platform-tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/tests/JSONITest.java
  appserver/tests/tck/platform-tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/tests/JdbcITest.java
  appserver/tests/tck/platform-tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/tests/MailITest.java
  appserver/tests/tck/platform-tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/tests/MessagingITest.java
  appserver/tests/tck/platform-tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/tests/PersistenceITest.java
  appserver/tests/tck/platform-tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/tests/RestfulWebservicesITest.java
  appserver/tests/tck/platform-tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/tests/ServerPagesITest.java
  appserver/tests/tck/platform-tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/tests/ServletITest.java
  appserver/tests/tck/platform-tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/tests/StandardTagLibraryITest.java
  appserver/tests/tck/platform-tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/tests/TransactionsITest.java
  appserver/tests/tck/platform-tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/tests/WebservicesITest.java
  appserver/tests/tck/platform-tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/tests/WebsocketITest.java
  appserver/tests/tck/platform-tck-runner/src/test/java/org/glassfish/main/tests/tck/ant/xml/TimestampAdapterTest.java
  appserver/tests/tck/platform-tck-runner/src/test/resources/client-logging.properties
  appserver/tests/tck/platform-tck-runner/src/test/resources/server-logging.properties
  appserver/tests/tck/platform-tck-runner/src/test/resources/settings.xml
  appserver/tests/tck/platform-tck-runner/src/test/resources/tck.properties
  appserver/tests/tck/pom.xml
  appserver/tests/tck/tck-download/jakarta-platform-tck/pom.xml
  appserver/tests/tck/tck-download/pom.xml
  nucleus/pom.xml
Labels: build and test improvement

#24673 Build of documentation revisited
  docs/add-on-component-development-guide/pom.xml
  docs/administration-guide/pom.xml
  docs/application-deployment-guide/pom.xml
  docs/application-development-guide/pom.xml
  docs/deployment-planning-guide/pom.xml
  docs/distribution/pom.xml
  docs/embedded-server-guide/pom.xml
  docs/error-messages-reference/pom.xml
  docs/ha-administration-guide/pom.xml
  docs/installation-guide/pom.xml
  docs/parent/pom.xml
  docs/performance-tuning-guide/pom.xml
  docs/pom.xml
  docs/publish/pom.xml
  docs/quick-start-guide/pom.xml
  docs/reference-manual/pom.xml
  docs/release-notes/pom.xml
  docs/security-guide/pom.xml
  docs/troubleshooting-guide/pom.xml
  docs/upgrade-guide/pom.xml
  docs/website/pom.xml
Labels: bug, build and test improvement

#24676 Integrate Tyrus 2.1.4
  appserver/pom.xml
Labels: component upgrade

#24678 The set-version-id profile updated to respect the current reactor
  pom.xml
  updateVersion.sh
Labels: build and test improvement

#24679 Fix an error message with unnecessary pattern string
  appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/annotation/impl/ModuleScanner.java
Labels: bug

#24680 Update various build-plugins to latest version
  nucleus/parent/pom.xml
  nucleus/pom.xml
Labels: build and test improvement

#24682 Integrate Mojarra 4.0.5
  appserver/pom.xml
  appserver/tests/tck/faces/pom.xml
  appserver/tests/tck/tck-download/jakarta-faces-tck/pom.xml
  appserver/web/jsf-connector/src/main/java/org/glassfish/faces/integration/GlassFishInjectionProvider.java
Labels: component upgrade, ee10-component

#24684 Integrate WaSP 3.2.2
  appserver/pom.xml
Labels: bug, component upgrade, ee10-component

#24685 Fixes in logging
  nucleus/admin/template/src/main/resources/config/logging.properties
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/handler/GlassFishLogHandler.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/rotation/LogFileManager.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/rotation/LogFileManagerTest.java
Labels: bug

#24687 Fix #24686 "Properties specific to this Class" is not displayed in Edit Realm Page
  appserver/admingui/common/src/main/resources/security/realms/realmjs.inc
  appserver/admingui/full/src/main/resources/jndijs.inc
  appserver/admingui/jca/src/main/resources/connectorConnectionPoolAdvance.jsf
  appserver/admingui/jca/src/main/resources/connectorSecurityMapjs.inc
  appserver/admingui/jca/src/main/resources/securityMapjs.inc
  appserver/admingui/jdbc/src/main/resources/jdbcConnectionPoolAdvanceJS.inc
  appserver/admingui/jdbc/src/main/resources/lazyConnectionJS.inc
Labels: bug

#24688 Integrate Helidon MicroProfile Config 3.2.3
  appserver/pom.xml
Labels: component upgrade

#24691 Fix WebSocket not working for default web module applications.
  appserver/web/web-core/src/main/java/org/apache/catalina/core/ApplicationContextFacade.java
  appserver/web/web-core/src/main/java/org/apache/catalina/core/DummyFilterRegistrationDynamic.java
  appserver/web/web-core/src/main/java/org/apache/catalina/core/WebSocketFilterWrapper.java
Labels: bug

#24692 Minor Fixes and Improvements in AdminGUI
  appserver/admingui/cluster/src/main/resources/cluster/clusterNew.jsf
  appserver/admingui/cluster/src/main/resources/cluster/clusterResources.jsf
  appserver/admingui/common/src/main/resources/applications/fileComponent.jsf
  appserver/admingui/common/src/main/resources/resourceNode/targetResourceTableButtons.inc
Labels: bug, enhancement

#24695 Integrate Jersey 3.1.4
  nucleus/parent/pom.xml
Labels: component upgrade, ee10-component
