Repository eclipse-ee4j/glassfish, pull requests merged in 2023-04, with the labels that each got.

#24363 Refactor the Enterprise Beans no-interface view bytecode generation
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/AsmSerializableBeanGenerator.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/BeanGeneratorBase.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/EjbOptionalIntfGenerator.java
  appserver/ejb/ejb-full-container/src/main/java/org/glassfish/ejb/mdb/MessageBeanInterfaceGenerator.java
Labels: code cleaning

#24370 API usage improvement to JDK11 in ASURLClassLoader
  nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/ASURLClassLoader.java
Labels: code cleaning

#24366 enable reproducible builds
  appserver/pom.xml
  nucleus/parent/pom.xml
  pom.xml
Labels: build and test improvement

#24374 Improved ClusterITest - don't remove instances and logs if it failed.
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/ClusterITest.java
Labels: build and test improvement

#24371 Refactor around REST resources related to server logs
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/logviewer/LogRecord.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/provider/JsonStringReaderWriter.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/custom/LogNamesResource.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/custom/StructuredLogViewerResource.java
Labels: bug, enhancement

#24377 Methods to build classpath of ScatteredArchive from the current classpath
  nucleus/common/scattered-archive-api/pom.xml
  nucleus/common/scattered-archive-api/src/main/java/org/glassfish/embeddable/archive/ScatteredArchive.java
  nucleus/common/scattered-archive-api/src/test/java/org/glassfish/embeddable/archive/ScatteredArchiveTest.java
Labels: enhancement

#24378 Integrate EclipseLink ASM 9.5.0
  appserver/pom.xml
Labels: component upgrade

#24361 Cleanups in connectors logging
  appserver/connectors/connectors-runtime/pom.xml
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/ConnectionManagerImpl.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/service/ConnectorConnectionPoolAdminServiceImpl.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/allocator/AbstractConnectorAllocator.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/allocator/ConnectorAllocator.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/allocator/LocalTxConnectorAllocator.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/allocator/NoTxConnectorAllocator.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/ConnectionLeakDetector.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/ConnectionPool.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/PoolManagerImpl.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/PoolSize.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/UnpooledResource.java
  appserver/connectors/connectors-runtime/src/main/resources/com/sun/enterprise/connectors/LocalStrings.properties
  appserver/connectors/connectors-runtime/src/main/resources/com/sun/enterprise/connectors/service/LocalStrings.properties
  appserver/connectors/connectors-runtime/src/main/resources/com/sun/enterprise/resource/pool/LocalStrings.properties
  appserver/connectors/connectors-runtime/src/main/resources/com/sun/logging/enterprise/resource/resourceadapter/LogStrings.properties
  appserver/connectors/connectors-runtime/src/test/java/com/sun/enterprise/resource/pool/PoolSizeTest.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/common/DataSourceObjectBuilder.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/base/AbstractDataSource.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/resources/com/sun/gjc/spi/LogStrings.properties
  appserver/tests/appserv-tests/cciblackbox-tx/src/main/java/com/sun/connector/cciblackbox/CciConnectionMetaDataImpl.java
  appserver/tests/appserv-tests/cciblackbox-tx/src/main/java/com/sun/connector/cciblackbox/CciLocalTxManagedConnectionFactory.java
  appserver/tests/appserv-tests/cciblackbox-tx/src/main/java/com/sun/connector/cciblackbox/CciManagedConnection.java
  appserver/tests/appserv-tests/cciblackbox-tx/src/main/java/com/sun/connector/cciblackbox/CciManagedConnectionMetaDataImpl.java
  appserver/tests/appserv-tests/cciblackbox-tx/src/main/java/com/sun/connector/cciblackbox/CciNoTxManagedConnectionFactory.java
  appserver/tests/appserv-tests/cciblackbox-tx/src/main/java/com/sun/connector/cciblackbox/TransactionImpl.java
  appserver/tests/appserv-tests/devtests/connector/embeddedweb-resourcesxml-defaultconnpool/ra/src/com/sun/jdbcra/spi/DataSource.java
  appserver/tests/appserv-tests/devtests/connector/nonstringmcfproperties/ra/src/com/sun/jdbcra/spi/DataSource.java
  appserver/tests/appserv-tests/devtests/connector/txlevelswitch/ra/src/com/sun/jdbcra/spi/DataSource.java
  appserver/tests/appserv-tests/devtests/connector/v3/embeddedweb-resources-xml/ra/src/com/sun/jdbcra/spi/DataSource.java
  appserver/tests/appserv-tests/devtests/connector/v3/nonstringmcfproperties/ra/src/com/sun/jdbcra/spi/DataSource.java
  appserver/tests/appserv-tests/devtests/jdbc/switchoffACCconnpooling/client/Client.java
  nucleus/core/kernel/src/main/java/org/glassfish/kernel/KernelLoggerInfo.java
Labels: code cleaning

#24380 Integrate Nimbus Jose JWT 9.31
  appserver/pom.xml
Labels: component upgrade

#24376 Removal of SentinelInputStream
  appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/StandAloneAppClientInfo.java
  appserver/connectors/connectors-internal-api/src/main/java/com/sun/appserv/connectors/internal/api/ConnectorsClassLoaderUtil.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/ASURLClassLoader.java
Labels: deprecation

#24386 Integrate Jackson 2.15.0
  nucleus/parent/pom.xml
Labels: component upgrade

#24387 Integrate Yasson 3.0.3
  appserver/pom.xml
Labels: component upgrade, ee10-component

#24389 Integrate Woodstox 6.5.1
  appserver/pom.xml
Labels: component upgrade

#24388 Fix config model initialization for interface annotated @Configured
  nucleus/hk2/hk2-config/src/main/java/org/jvnet/hk2/config/DomDocument.java
Labels: bug

#24390 Integrate JSF Template 4.0.1
  appserver/pom.xml
Labels: component upgrade

#24392 Some modest cleanups for the security code
  appserver/web/web-core/src/main/java/org/apache/catalina/Authenticator.java
  appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/AuthenticatorBase.java
  appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/BasicAuthenticator.java
  appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/Constants.java
  appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/DigestAuthenticator.java
  appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/FormAuthenticator.java
  appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/NonLoginAuthenticator.java
  appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/SSLAuthenticator.java
  appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/SavedRequest.java
  appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/SingleSignOn.java
  appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/SingleSignOnEntry.java
  nucleus/common/internal-api/src/main/java/org/glassfish/internal/api/Globals.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/login/ClientCertificateLoginModule.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/login/ClientPasswordLoginModule.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/GroupMapper.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/GroupNotEmptyException.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/InvalidOperationException.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/NoSuchUserException.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/Realm.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/RealmConfig.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/RealmsManager.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/User.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/certificate/CertificateRealm.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/file/FileRealm.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/file/FileRealmUser.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/ldap/CustomSocketFactory.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/ldap/LDAPRealm.java
Labels: code cleaning

#24397 JMX server should not accept an arbitrary object as credentials
  nucleus/common/mbeanserver/src/main/java/org/glassfish/admin/mbeanserver/RMIConnectorStarter.java
Labels: security fix

#24396 Fix data race in the MonitoringService
  nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/serverbeans/MonitoringService.java
Labels: bug
