Repository eclipse-ee4j/glassfish, pull requests merged in 2023-07, with the labels that each got.

#24485 Admin Console: Fix Resource Adapter Config creation
  appserver/admingui/jca/src/main/resources/resourceAdapterConfigAttr.inc
  appserver/admingui/jca/src/main/resources/resourceAdapterConfigNew.jsf
Labels: bug

#24487 Integate JBoss Logging 3.5.2
  nucleus/parent/pom.xml
Labels: component upgrade

#24489 Integrate Hibernate Validator 8.0.1
  appserver/tests/tck/validation/pom.xml
  nucleus/parent/pom.xml
Labels: component upgrade, ee10-component, ee10-tck

#24490 Fix Enterprise Beans business method generation
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/EjbOptionalIntfGenerator.java
Labels: bug

#24491 Integrate Commons IO 2.13.0
  nucleus/parent/pom.xml
Labels: component upgrade

#24493 Integrate jakarta.websocket-api 2.1.1
  appserver/pom.xml
Labels: component upgrade, ee10-component

#24494 Integrate jsftemplating 4.0.3
  appserver/pom.xml
Labels: bug, component upgrade

#24498 Integrate Weld 5.1.1.SP1
  appserver/pom.xml
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/services/CDIServiceImpl.java
  nucleus/parent/pom.xml
Labels: component upgrade, ee10-component

#24499 Update command-security plugin to 1.0.17
  nucleus/parent/pom.xml
Labels: build and test improvement

#24497 Fix remote EJB access issue in glassfish-naming by updating osgi.bundle
  appserver/common/glassfish-naming/osgi.bundle
Labels: bug

#24503 Integrate MicroProfile API 3.0.3 and Helidon implementation 3.2.2
  appserver/pom.xml
Labels: component upgrade

#24504 Removed two files which were copy pasted in web_jsp tests
  appserver/web/web-glue/src/main/java/org/apache/jsp/jsp/test_jsp.java
  appserver/web/web-glue/src/main/java/org/apache/jsp/nullErrorPage_jsp.java
Labels: code cleaning

#24502 Fix of a few links in docs
  docs/administration-guide/src/main/asciidoc/transactions.adoc
  docs/application-deployment-guide/src/main/asciidoc/overview.adoc
Labels: Documentation

#24505 Integrate Parsson 1.1.3
  appserver/pom.xml
Labels: component upgrade, ee10-component

#24506 Integrate REST Client 3.0.1 API
  appserver/pom.xml
Labels: component upgrade

#24507 Integrate MicroProfile JWT 2.1 API and implementation OmniFaces 2.0.2
  appserver/pom.xml
  appserver/tests/tck/jwt/pom.xml
Labels: component upgrade

#24508 Instructions how to preview glassfish.org website locally
  docs/README.md
Labels: Documentation

#24509 Update Maven plugins
  docs/parent/pom.xml
  docs/pom.xml
  nucleus/parent/pom.xml
Labels: build and test improvement

#24510 Fix for JSR 109 WSDL generation when using JDK 21
  nucleus/admin/template/src/main/resources/config/server.policy
Labels: bug, jdk21

#24511 Add a top menu in the glassfish.org page
  docs/website/src/main/resources/CONTRIBUTING.md
  docs/website/src/main/resources/README.md
  docs/website/src/main/resources/_includes/topnav.html
  docs/website/src/main/resources/_layouts/default.html
  docs/website/src/main/resources/assets/css/style.scss
  docs/website/src/main/resources/documentation.md
  docs/website/src/main/resources/faq.md
  docs/website/src/main/resources/img/book.svg
  docs/website/src/main/resources/img/download.svg
  docs/website/src/main/resources/img/life-ring.svg
  docs/website/src/main/resources/img/people-line.svg
  docs/website/src/main/resources/support.md
Labels: Documentation

#24513 Add MicroProfile docs to docs page in the glassfish.org site.
  docs/website/src/main/resources/documentation.md
Labels: Documentation

#24512 Removed Util class in weld-integration
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/ACLSingletonProvider.java
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldActivator.java
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/jsf/WeldApplication.java
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/util/Util.java
Labels: code cleaning

#24515 The EJB Security module (iiop) logging revisited and detached from security-core
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/AlternateSecurityInterceptorFactory.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/CSIV2TaggedComponentInfo.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/ConnectionContext.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/ConnectionExecutionContext.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/GSSUPToken.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/GSSUtils.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/GSSUtilsService.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/IIOPSSLUtilImpl.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/IORToSocketInfoImpl.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/InvalidIdentityTokenException.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/InvalidMechanismException.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/Lookups.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/SecClientRequestInterceptor.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/SecIORInterceptor.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/SecServerRequestInterceptor.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/SecurityContextUtil.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/SecurityIIOPInterceptorFactory.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/SecurityMechanismException.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/SecurityMechanismSelector.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/ServerConnectionContext.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/SvcContextUtils.java
  appserver/security/ejb.security/src/main/resources/com/sun/logging/.gitkeep_empty_dir
  nucleus/security/core/src/main/resources/com/sun/logging/enterprise/system/core/security/LogStrings.properties
Labels: code cleaning

#24516 Security logging - another step of cleanup
  appserver/security/appclient.security/src/main/java/com/sun/enterprise/security/appclient/AppClientSecurityInfoImpl.java
  appserver/security/appclient.security/src/main/java/com/sun/enterprise/security/appclient/AppclientIIOPInterceptorFactory.java
  appserver/security/appclient.security/src/main/java/com/sun/enterprise/security/appclient/ConfigXMLParser.java
  appserver/security/appclient.security/src/main/java/com/sun/enterprise/security/appclient/integration/AppClientSecurityInfo.java
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/jmac/config/ConfigDomainParser.java
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/jmac/config/GFServerConfigProvider.java
  appserver/security/jaspic-provider-framework/pom.xml
  appserver/security/jaspic-provider-framework/src/main/java/com/sun/jaspic/config/delegate/MessagePolicyDelegate.java
  appserver/security/jaspic-provider-framework/src/main/java/com/sun/jaspic/config/factory/AuthConfigFileFactory.java
  appserver/security/jaspic-provider-framework/src/main/java/com/sun/jaspic/config/factory/BaseAuthConfigFactory.java
  appserver/security/jaspic-provider-framework/src/main/java/com/sun/jaspic/config/factory/RegStoreFileParser.java
  appserver/security/jaspic-provider-framework/src/main/java/com/sun/jaspic/config/helper/JASPICLogManager.java
  appserver/security/jaspic-provider-framework/src/main/java/com/sun/jaspic/config/jaas/ExtendedConfigFile.java
  appserver/security/jaspic-provider-framework/src/main/resources/com/sun/logging/enterprise/system/jaspic/security/LogStrings.properties
  appserver/security/webintegration/src/main/java/com/sun/web/security/CNonceCacheImpl.java
  appserver/security/webintegration/src/main/java/com/sun/web/security/RealmAdapter.java
  appserver/security/webintegration/src/main/java/com/sun/web/security/SSLSocketFactory.java
  appserver/security/webintegration/src/main/java/com/sun/web/security/WebProgrammaticLoginImpl.java
  appserver/security/webintegration/src/main/java/com/sun/web/security/WebSecurityResourceBundle.java
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/AsadminLoggingITest.java
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/LogFacade.java
  appserver/web/war-util/src/main/resources/com/sun/logging/enterprise/system/container/web/LogStrings.properties
  appserver/web/web-core/src/main/resources/org/apache/catalina/realm/LocalStrings.properties
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/RuntimeInfo.java
  nucleus/security/core/src/main/resources/com/sun/logging/enterprise/system/core/security/LogStrings.properties
Labels: code cleaning

#24518 Integrate Jersey 3.1.3
  nucleus/parent/pom.xml
Labels: component upgrade, ee10-component

#24520 Admin Console: Fixes New Admin Object Resource creation
  appserver/admingui/jca/src/main/resources/adminObjectNew.jsf
Labels: bug

#24517 Refactor connector connection pool RWLockDataStructure
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/ResourceHandle.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/datastructure/DataStructure.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/datastructure/ListDataStructure.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/datastructure/RWLockDataStructure.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/resizer/AssocWithThreadPoolResizer.java
  appserver/connectors/connectors-runtime/src/test/java/com/sun/enterprise/resource/pool/datastructure/RWLockDataStructureTest.java
Labels: code cleaning
