Repository eclipse-ee4j/glassfish, pull requests merged in 2023-03, with the labels that each got.

#24327 Fix #19580 IIOP Listeners (SSL) port is listening after SSL.enabled is set to false
  appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/GlassFishORBManager.java
  appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/PEORBConfigurator.java
Labels: bug

#24330 Update the Download page for the 7.0.2 release
  docs/website/src/main/resources/download.md
Labels: Documentation

#24331 Reverted update of glassfishbuild-maven-plugin
  nucleus/parent/pom.xml
Labels: bug

#24328 Get the timeout for CMT from TransactionService
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBContainerTransactionManager.java
Labels: bug

#24335 Cargotracker discoveries part one
  appserver/connectors/connectors-internal-api/src/main/java/com/sun/appserv/connectors/internal/api/ConnectorRuntime.java
  appserver/connectors/connectors-internal-api/src/main/java/com/sun/appserv/connectors/internal/api/ConnectorRuntimeException.java
  appserver/connectors/connectors-internal-api/src/main/java/com/sun/appserv/connectors/internal/api/ConnectorsUtil.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/ActiveOutboundResourceAdapter.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/ConnectorRuntime.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/service/ConnectorService.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/BaseContainer.java
Labels: bug

#24338 Make ASM API version and bytecode level consistent with used ASM library and minimal requred Java version
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/EjbOptionalIntfGenerator.java
  nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/schemadoc/AttributeMethodVisitor.java
  nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/schemadoc/DocClassVisitor.java
  nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/schemadoc/EmptyVisitor.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/composite/CompositeUtil.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/generator/ASMClassWriter.java
  nucleus/deployment/common/src/main/java/org/glassfish/deployment/common/GenericAnnotationDetector.java
  nucleus/deployment/common/src/main/java/org/glassfish/deployment/common/NodeInfo.java
  nucleus/flashlight/framework/src/main/java/org/glassfish/flashlight/impl/client/BtraceClientGenerator.java
  nucleus/flashlight/framework/src/main/java/org/glassfish/flashlight/impl/client/ProbeProviderClassFileTransformer.java
  nucleus/flashlight/framework/src/main/java/org/glassfish/flashlight/impl/core/ProviderImplGenerator.java
  nucleus/flashlight/framework/src/main/java/org/glassfish/flashlight/impl/core/ProviderSubClassImplGenerator.java
  nucleus/test-utils/src/main/java/org/glassfish/tests/utils/junit/HK2ClasssVisitor.java
Labels: component upgrade

#24340 Updated dependency on old TCK
  appserver/tests/tck/tck-download/jakarta-ant-based-tck/pom.xml
Labels: build and test improvement

#24341 Refactor logging admin integration tests
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/AsadminLoggingITest.java
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/rest/LoggingRestITest.java
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/rest/RestTestBase.java
Labels: build and test improvement

#24342 Integrate Mojarra 4.0.2 and associated Faces TCK 4.0.2
  appserver/pom.xml
  appserver/tests/tck/faces/pom.xml
  appserver/tests/tck/tck-download/jakarta-faces-tck/pom.xml
Labels: component upgrade, ee10-component, ee10-tck

#24343 Resolve set-log-attributes asadmin command issue
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java
Labels: bug

#24344 Refactor securing REST Admin interface integration test
  appserver/itest-tools/src/main/java/org/glassfish/main/itest/tools/DomainAdminRestClient.java
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/rest/BasicAuthenticationITest.java
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/rest/RestTestBase.java
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/rest/SecuredRestTestBase.java
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/rest/TokenAuthenticationITest.java
  docs/administration-guide/src/main/asciidoc/general-administration.adoc
Labels: build and test improvement

#24347 Removed sleeps from Ant tests
  appserver/tests/appserv-tests/config/common.xml
  appserver/tests/appserv-tests/devtests/cdi/osgi-cdi/common.xml
  appserver/tests/appserv-tests/devtests/cdi/smoke-tests/simple-wab-with-cdi/common.xml
  appserver/tests/appserv-tests/devtests/jdbc/JdbcCommon.xml
  appserver/tests/quicklook/gfproject/v3-targets.xml
  appserver/tests/v2-tests/appserv-tests/config/common.xml
Labels: build and test improvement

#24346 Fix creation of JavaMail session via Admin Console and REST Admin interface
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/rest/MailITest.java
  appserver/tests/appserv-tests/devtests/admin/cli/src/admin/JavaMailResourceTest.java
  docs/administration-guide/src/main/asciidoc/asadmin-subcommands.adoc
  docs/administration-guide/src/main/asciidoc/general-administration.adoc
  docs/administration-guide/src/main/asciidoc/jakarta-mail.adoc
  docs/administration-guide/src/main/asciidoc/jms.adoc
  docs/administration-guide/src/main/asciidoc/jndi.adoc
  docs/administration-guide/src/main/asciidoc/loe.adoc
  docs/administration-guide/src/main/asciidoc/orb.adoc
  docs/administration-guide/src/main/asciidoc/overview.adoc
  docs/application-deployment-guide/src/main/asciidoc/deploying-applications.adoc
  docs/application-development-guide/src/main/asciidoc/ejb.adoc
  docs/application-development-guide/src/main/asciidoc/jndi.adoc
  docs/application-development-guide/src/main/asciidoc/mail.adoc
  docs/application-development-guide/src/main/asciidoc/webapps.adoc
  docs/deployment-planning-guide/src/main/asciidoc/concepts.adoc
  docs/ha-administration-guide/src/main/asciidoc/session-persistence-and-failover.adoc
  docs/installation-guide/src/main/asciidoc/installing.adoc
  docs/reference-manual/src/main/asciidoc/add-resources.adoc
  docs/reference-manual/src/main/asciidoc/create-jacc-provider.adoc
  docs/reference-manual/src/main/asciidoc/create-jdbc-connection-pool.adoc
  docs/reference-manual/src/main/asciidoc/create-local-instance.adoc
  docs/reference-manual/src/main/asciidoc/create-mail-resource.adoc
  docs/reference-manual/src/main/asciidoc/create-managed-executor-service.adoc
  docs/reference-manual/src/main/asciidoc/delete-jacc-provider.adoc
  docs/reference-manual/src/main/asciidoc/delete-jdbc-connection-pool.adoc
  docs/reference-manual/src/main/asciidoc/delete-local-instance.adoc
  docs/reference-manual/src/main/asciidoc/delete-mail-resource.adoc
  docs/reference-manual/src/main/asciidoc/delete-managed-executor-service.adoc
  docs/reference-manual/src/main/asciidoc/list-commands.adoc
  docs/reference-manual/src/main/asciidoc/list-jacc-providers.adoc
  docs/reference-manual/src/main/asciidoc/list-jdbc-connection-pools.adoc
  docs/reference-manual/src/main/asciidoc/list-log-levels.adoc
  docs/reference-manual/src/main/asciidoc/list-mail-resources.adoc
  docs/reference-manual/src/main/asciidoc/list-managed-executor-services.adoc
  docs/release-notes/src/main/asciidoc/release-notes.adoc
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/generator/ResourcesGeneratorBase.java
Labels: bug

#24349 Integrate Jettison 1.5.4
  nucleus/parent/pom.xml
Labels: component upgrade

#24351 Integrate EclipseLink 4.0.1
  appserver/pom.xml
Labels: component upgrade, ee10-component

#24352 Integrate helidon-config 3.2.0
  appserver/pom.xml
Labels: component upgrade

#24356 Integrate ASM 9.5
  nucleus/parent/pom.xml
Labels: component upgrade

#24355 Fix Enterprise Beans deployment error
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/AsmSerializableBeanGenerator.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/EjbOptionalIntfGenerator.java
Labels: bug

#24357 Removed hk2.version from bundle plugin config
  appserver/web/jersey-ejb-component-provider/pom.xml
Labels: build and test improvement

#24360 Fix sporadic error in view log REST integration test
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/rest/LoggingRestITest.java
Labels: build and test improvement

#24362 Integrate hk2 3.0.4
  nucleus/parent/pom.xml
Labels: component upgrade

#24365 Update website for 7.0.3 release
  docs/website/src/main/resources/README.md
  docs/website/src/main/resources/download.md
  docs/website/src/main/resources/download_gf7.md
Labels: Documentation
