Repository eclipse-ee4j/glassfish, pull requests merged in 2024-11, with the labels that each got.

#25201 Update RELEASE.md for 7.0.19
  RELEASE.md
Labels: Documentation

#25205 Updated domain.xml file management + CI for windows
  .github/workflows/build-windows.yml
  appserver/ant-tasks/src/main/java/org/glassfish/ant/embedded/tasks/Util.java
  appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/embedded/EJBContainerProviderImpl.java
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/OSGiCommandsITest.java
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/StartServITest.java
  appserver/tests/embedded/basic/config/src/test/java/org/glassfish/tests/embedded/basic/config/ConfigTest.java
  nucleus/admin/config-api/src/main/java/org/glassfish/config/support/ConfigurationAccess.java
  nucleus/admin/config-api/src/main/java/org/glassfish/config/support/DasReaderFilter.java
  nucleus/admin/config-api/src/main/java/org/glassfish/config/support/DomainXml.java
  nucleus/admin/config-api/src/main/java/org/glassfish/config/support/InstanceReaderFilter.java
  nucleus/admin/config-api/src/main/java/org/glassfish/config/support/LocalStrings.properties
  nucleus/admin/config-api/src/main/java/org/glassfish/config/support/ServerReaderFilter.java
  nucleus/admin/config-api/src/main/java/org/glassfish/config/support/XMLStreamReaderFilter.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/CULoggerInfo.java
  nucleus/common/common-util/src/main/java/org/glassfish/common/util/admin/ManagedFile.java
  nucleus/common/common-util/src/test/java/org/glassfish/common/util/admin/locking/FileLockTest.java
  nucleus/common/common-util/src/test/java/org/glassfish/common/util/admin/locking/ReadLockTest.java
  nucleus/common/simple-glassfish-api/pom.xml
  nucleus/common/simple-glassfish-api/src/main/java/org/glassfish/embeddable/GlassFishProperties.java
  nucleus/common/simple-glassfish-api/src/test/java/org/glassfish/embeddable/GlassFishPropertiesTest.java
  nucleus/common/simple-glassfish-api/src/test/resources/domain.xml
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/embedded/EmbeddedGlassFishRuntime.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/DomainXmlPersistence.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/LocalStrings.properties
  nucleus/core/kernel/src/main/java/org/glassfish/kernel/embedded/EmbeddedDomainPersistence.java
  nucleus/core/kernel/src/main/java/org/glassfish/kernel/embedded/EmbeddedDomainXml.java
  nucleus/core/kernel/src/main/java/org/glassfish/runnablejar/commandline/Option.java
  nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/AddLibraryCommand.java
  nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/DeployCommand.java
  nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/DeploymentCommandUtils.java
  nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/InstanceDeployCommand.java
  nucleus/hk2-config-generator/src/main/java/org/jvnet/hk2/config/DelegatingXMLStreamWriter.java
  nucleus/hk2-config-generator/src/main/java/org/jvnet/hk2/config/IndentingXMLStreamWriter.java
Labels: bug, code cleaning, build and test improvement

#25215 Fix #25214 Services are not initialized in a concurrent way at GlassFish startup
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/GlassFishMain.java
Labels: bug

#25217 Fix #25216 Redirection does not work after session timeout in Admin Console
  appserver/admingui/war/src/main/java/org/glassfish/admingui/common/AdminGuiExceptionHandler.java
  appserver/admingui/war/src/main/java/org/glassfish/admingui/common/AdminGuiExceptionHandlerFactory.java
  appserver/admingui/war/src/main/webapp/WEB-INF/faces-config.xml
Labels: bug

#25221 Fix #25220 The number of Logging pump threads grows infinitely
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/handler/GlassFishLogHandler.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/handler/LoggingOutputStream.java
Labels: bug

#25223 Fix target argument in create-jms-resource
  appserver/jms/admin/src/main/java/org/glassfish/jms/admin/cli/CreateJMSResource.java
Labels: bug

#25224 Integrate Jackson 2.18.1
  nucleus/parent/pom.xml
Labels: component upgrade

#25229 Fixed checkstyle in naming tests
  appserver/tests/appserv-tests/devtests/naming/naming2/context/src/main/java/test/TestBean.java
  appserver/tests/appserv-tests/devtests/naming/naming2/context/src/test/java/test/ContextTest.java
  appserver/tests/appserv-tests/devtests/naming/naming2/context/src/test/java/test/ReportWatcher.java
Labels: build and test improvement

#25227 Fixes and cleanup around IMQ startup and shutdown
  appserver/connectors/connectors-inbound-runtime/src/main/java/com/sun/enterprise/connectors/inbound/ActiveInboundResourceAdapterImpl.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/ActiveOutboundResourceAdapter.java
  appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/node/runtime/connector/ResourceAdapterNode.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/EJBUtils.java
  appserver/jms/jms-core/src/main/java/com/sun/enterprise/connectors/jms/JMSLoggerInfo.java
  appserver/jms/jms-core/src/main/java/com/sun/enterprise/connectors/jms/system/ActiveJmsResourceAdapter.java
  appserver/jms/jms-core/src/main/java/com/sun/enterprise/connectors/jms/system/JMSConfigListener.java
Labels: bug

#25226 Fixed RarHandler - non-absolute URL to File conversion
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/module/RarHandler.java
Labels: bug

#25231 Update various maven plugins and associated test dependencies
  nucleus/parent/pom.xml
  pom.xml
Labels: build and test improvement

#25233 Integrate commons lang3 3.17.0
  nucleus/parent/pom.xml
Labels: component upgrade

#25235 Integrate XMLsec 4.0.3
  appserver/pom.xml
Labels: component upgrade

#25234 Integrate Felix Webconsole 5.0.8
  nucleus/parent/pom.xml
Labels: component upgrade

#25236 Integrate ASM 9.7.1
  nucleus/parent/pom.xml
Labels: component upgrade

#25239 Integrate Nimbus-JOSE-JWT 9.47
  appserver/pom.xml
Labels: component upgrade

#25238 Integrate JNA 5.15.0
  appserver/libpam4j/pom.xml
Labels: component upgrade

#25241 Update build / test plugins, and ignore EE 11 versions
  appserver/pom.xml
  appserver/tests/appserv-tests/lib/pom.xml
  appserver/tests/embedded/web/pom.xml
  docs/parent/pom.xml
  nucleus/parent/pom.xml
  pom.xml
  qa/pom.xml
Labels: build and test improvement

#25243 Integrate EclipseLink 4.0.4
  appserver/pom.xml
Labels: component upgrade, ee10-component

#25242 Integrate Jersey 3.1.9
  nucleus/parent/pom.xml
Labels: component upgrade

#25244 Integrate Mojarra 4.0.9
  appserver/pom.xml
Labels: component upgrade, ee10-component

#25245 Integrate Weld 5.1.3
  appserver/pom.xml
  nucleus/parent/pom.xml
Labels: component upgrade, ee10-component

#25247 Integrate Helidon Config 3.2.11 and update API to 3.1
  appserver/pom.xml
Labels: component upgrade

#25248 Integrate Jakarta Concurrency API 3.0.4
  appserver/pom.xml
Labels: component upgrade, ee10-component

#25246 Add some more exclusions for EE 11 dependencies
  nucleus/parent/pom.xml
Labels: build and test improvement

#25249 Integrate Jakarta Tags API 3.0.2
  appserver/pom.xml
Labels: component upgrade, ee10-component

#25250 Integrate Jakarta XML Web Services API 4.0.2
  nucleus/parent/pom.xml
Labels: component upgrade, ee10-component

#25251 Integrate OpenMQ 6.5.0
  appserver/pom.xml
Labels: component upgrade, ee10-component

#25252 EntityManagerFactoryWrapper quick cleanup
  appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/EntityManagerFactoryWrapper.java
Labels: code cleaning

#25253 Update build tools
  nucleus/parent/pom.xml
Labels: build and test improvement
