Repository eclipse-ee4j/glassfish, pull requests merged in 2024-03, with the labels that each got.

#24839 Update documentation page for 7.0.13
  docs/pom.xml
Labels: Documentation

#24841 Fixed dependencies of concurrency TCK
  appserver/tests/tck/concurrency/pom.xml
Labels: bug

#24844 Fixes issue #24843 log a warning in the rare case the Resource handle
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/ConnectorRuntime.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/ConnectionPool.java
  appserver/connectors/connectors-runtime/src/test/java/com/sun/enterprise/resource/pool/ConnectionPoolTest.java
Labels: bug

#24847 SSL Configurator fix - CertificateRequest not being made in SSL mutual authentication
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/SSLConfigurator.java
Labels: bug

#24848 Integrate JSch 0.2.17
  nucleus/parent/pom.xml
Labels: component upgrade

#24853 Fixed dependencies of the REST TCK
  appserver/tests/tck/rest/pom.xml
Labels: build and test improvement

#24852 Fixed report.dir in the Authentication TCK execution
  appserver/tests/tck/authentication/pom.xml
Labels: build and test improvement

#24850 Fixes command progress status
  nucleus/admin/util/src/main/java/com/sun/enterprise/admin/progress/CommandProgressImpl.java
Labels: bug

#24855 The secureResponse can return just SEND_* states (based on javadoc)
  appserver/security/webintegration/src/main/java/com/sun/web/security/RealmAdapter.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/security/jmac/https/HttpsTestAuthModule.java
Labels: bug

#24851 Fixes issue #24849 make relevant methods synchronized in LocalTxConnectionEventListener
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/ConnectorXAResource.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/ResourceHandle.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/listener/LocalTxConnectionEventListener.java
  appserver/connectors/connectors-runtime/src/test/java/com/sun/enterprise/resource/listener/LocalTxConnectionEventListenerTest.java
Labels: bug

#24771 Updated Maven in Jenkinsfile
  Jenkinsfile
Labels: build and test improvement

#24859 Make `@RestrictTo` annotation repeatable
  nucleus/common/glassfish-api/src/main/java/org/glassfish/api/event/RestrictTo.java
  nucleus/core/kernel/src/main/java/org/glassfish/kernel/event/EventsImpl.java
  nucleus/core/kernel/src/test/java/org/glassfish/tests/kernel/deployment/EventFilteringTest.java
Labels: enhancement

#24862 Latest 8.0 updates and commits from master
  appserver/pom.xml
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/security/defaultp2r/DefaultP2RAuthTest.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/security/jmac/http/servlet/basic/HttpServletBasicAuthTest.java
  nucleus/parent/pom.xml
Labels: 8.0-M3

#24864 Remove unnecessary exports from MicroProfile Config bundle
  appserver/microprofile/config/pom.xml
Labels: code cleaning

#24866 Integrate Jakarta Concurrency TCK 3.0.3
  appserver/tests/tck/concurrency/pom.xml
Labels: build and test improvement

#24873 Integrate Shrinkwrap Resolvers 3.3.0
  nucleus/parent/pom.xml
Labels: build and test improvement

#24876 Integrate CDI TCK 4.0.13
  appserver/tests/tck/cdi/cdi-full/pom.xml
  appserver/tests/tck/cdi/cdi-model/pom.xml
Labels: build and test improvement

#24880 Integrate OW2 ASM 9.7
  nucleus/parent/pom.xml
Labels: component upgrade

#24877 Fixed JmacHttpsTest - certificate authentication
  appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/node/runtime/common/DescriptorPrincipalName.java
  appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/runtime/common/PrincipalNameDescriptor.java
  appserver/itest-tools/src/main/java/org/glassfish/main/itest/tools/TestUtilities.java
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/acl/RoleMapper.java
  appserver/security/webintegration/src/main/java/com/sun/web/security/RealmAdapter.java
  appserver/tests/application/src/main/resources/org/glassfish/main/test/app/security/jmac/https/glassfish-web.xml
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/security/defaultp2r/DefaultP2RAuthTest.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/security/http/method/HttpMethodAuthTest.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/security/jmac/http/servlet/basic/HttpServletBasicAuthTest.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/security/jmac/http/servlet/challenge/HttpServletChallengeAuthTest.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/security/jmac/https/JmacHttpsTest.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/security/jsp2sful/JspToStatefulAuthTest.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/security/multirolemapping/MultiRoleMappingTest.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/security/simplemultirolemapping/SimpleMultiRoleMappingTest.java
  appserver/web/web-core/src/main/java/org/apache/catalina/Realm.java
  appserver/web/web-core/src/main/java/org/apache/catalina/realm/JAASRealm.java
  appserver/web/web-core/src/main/java/org/apache/catalina/realm/RealmBase.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/security/integration/RealmInitializer.java
  nucleus/common/common-util/src/main/java/com/sun/logging/LogCleanerUtil.java
  nucleus/deployment/common/src/main/resources/com/sun/logging/enterprise/system/tools/deployment/LogStrings.properties
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/login/LoginContextDriver.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/login/common/LoginException.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/certificate/CertificateRealm.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/ssl/GlassfishSSLSupport.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/ssl/J2EEKeyManager.java
Labels: bug, code cleaning

#24881 Fixed ejb_group_embedded tests
  appserver/microprofile/config/pom.xml
Labels: bug

#24883 Added staging repo to runtests.sh + archiving rotated server.log files on jenkins
  Jenkinsfile
  runtests.sh
Labels: build and test improvement

#24882 Fixed runtests.sh script
  runtests.sh
Labels: build and test improvement

#24879 Fixes #23483 Add lock, add notifyWaitingThreads call for better max pool size logic.
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/ConnectionPool.java
  appserver/connectors/connectors-runtime/src/test/java/com/sun/enterprise/resource/pool/ConnectionPoolTest.java
Labels: bug, code cleaning
