Repository eclipse-ee4j/glassfish, pull requests merged in 2024-01, with the labels that each got.

#24723 Integrate Javassist 3.30.2
  nucleus/parent/pom.xml
Labels: component upgrade

#24724 Integrate JLine 3.25.0
  nucleus/parent/pom.xml
Labels: component upgrade

#24727 Integrate ClassMate 1.7.0
  nucleus/parent/pom.xml
Labels: component upgrade

#24725 Integrate commons-lang3 3.14.0
  nucleus/parent/pom.xml
Labels: component upgrade

#24726 Integrate Commons IO 2.15.1
  nucleus/parent/pom.xml
Labels: component upgrade

#24731 Integrate Helidon MicroProfile Config 3.2.5
  appserver/pom.xml
Labels: component upgrade

#24729 Integrate JSch 0.2.16
  nucleus/parent/pom.xml
Labels: component upgrade

#24730 Refactor deployment-time bytecode preprocessing
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/ASURLClassLoader.java
  nucleus/common/internal-api/src/main/java/org/glassfish/internal/deployment/ExtendedDeploymentContext.java
  nucleus/deployment/common/src/main/java/org/glassfish/deployment/common/DeploymentContextImpl.java
Labels: code cleaning

#24738 Replace JMockit mock framework with EasyMock
  nucleus/core/context-propagation/pom.xml
  nucleus/core/context-propagation/src/test/java/org/glassfish/contextpropagation/internal/ContextMapPropagatorTest.java
  nucleus/diagnostics/context/pom.xml
  nucleus/diagnostics/context/src/test/java/org/glassfish/diagnostics/context/impl/ContextImplUnitTest.java
  nucleus/parent/pom.xml
Labels: build and test improvement

#24740 Give authentication modules masked request
  appserver/security/webintegration/src/main/java/com/sun/web/security/RealmAdapter.java
  appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/FormAuthenticator.java
Labels: bug

#24742 Update JaCoCo to 0.8.11 in nucleus parent POM
  nucleus/parent/pom.xml
Labels: component upgrade

#24743 Fixes around logging
  nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncher.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/LocalStrings.properties
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/StopDomainCommand.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogFacade.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LogManagerService.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/handler/GlassFishLogHandler.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/rotation/LogFileArchiver.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/rotation/LogFileManager.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/rotation/MeteredFileWriter.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/handler/GlassFishLogHandlerTest.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/rotation/LogFileManagerTest.java
Labels: bug

#24741 Integrate EasyMock 5.2.0
  nucleus/parent/pom.xml
Labels: component upgrade

#24744 Add debug option to start-cluster, to start all instances in debug mode
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ClusterCommandHelper.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/StartClusterCommand.java
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/StopClusterCommand.java
  nucleus/cluster/admin/src/main/manpages/com/sun/enterprise/v3/admin/cluster/start-cluster.1
Labels: New feature

#24745 Fixes `ConcurrentModificationException` in context map propagator
  nucleus/core/context-propagation/src/main/java/org/glassfish/contextpropagation/internal/Utils.java
  nucleus/core/context-propagation/src/test/java/org/glassfish/contextpropagation/internal/ContextMapPropagatorTest.java
Labels: bug

#24753 Try the application classloader to restore the Principal for HA.
  appserver/web/web-core/src/main/java/org/apache/catalina/authenticator/SingleSignOn.java
  appserver/web/web-glue/src/main/java/com/sun/enterprise/security/web/GlassFishSingleSignOn.java
  appserver/web/web-ha/src/main/java/org/glassfish/web/ha/authenticator/HASingleSignOn.java
  appserver/web/web-ha/src/main/java/org/glassfish/web/ha/authenticator/HASingleSignOnEntry.java
Labels: bug

#24755 Integrate Tyrus 2.1.5
  appserver/pom.xml
Labels: component upgrade, ee10-component

#24754 Use standard proxy default method invocation handler
  nucleus/hk2-config-generator/src/main/java/org/jvnet/hk2/config/Dom.java
  nucleus/hk2-config-generator/src/main/java/org/jvnet/hk2/config/ProxyHelper.java
  nucleus/hk2-config-generator/src/main/java/org/jvnet/hk2/config/WriteableView.java
Labels: code cleaning

#24757 Order WebSocket initializer before Faces one
  appserver/web/web-core/src/main/java/org/apache/catalina/Globals.java
  appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.java
Labels: bug

#24758 Fixes REST ASM resource generator
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/generator/ASMResourcesGenerator.java
Labels: bug

#24759 Guard the websocket upgrade to only happen once for a request.
  appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardPipeline.java
Labels: bug

#24760 Integrate Apache Santuario/XMLSec 4.0.1
  appserver/pom.xml
Labels: component upgrade

#24761 Integrate Woodstox 6.6.0
  appserver/pom.xml
Labels: component upgrade

#24763 More stable GlassFishLogHandlerTest
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/handler/GlassFishLogHandlerTest.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/rotation/LogFileManagerTest.java
Labels: build and test improvement

#24764 Add Websocket TCK runner
  appserver/tests/tck/pom.xml
  appserver/tests/tck/tck-download/jakarta-websocket-tck/pom.xml
  appserver/tests/tck/tck-download/pom.xml
  appserver/tests/tck/websocket/pom.xml
Labels: build and test improvement

#24766 Integrate HK2 3.0.6
  nucleus/parent/pom.xml
Labels: component upgrade

#24765 Patch Tyrus manifest to export org.glassfish.tyrus.client.exception
  appserver/distributions/glassfish/pom.xml
  appserver/distributions/glassfish/src/main/patches/tyrus-client/META-INF/MANIFEST.MF
  appserver/distributions/web/pom.xml
  appserver/distributions/web/src/main/patches/tyrus-client/META-INF/MANIFEST.MF
Labels: bug

#24770 Print processes before the build
  Jenkinsfile
Labels: build and test improvement

#24774 Webpage update for 7.0.12
  docs/website/src/main/resources/README.md
  docs/website/src/main/resources/download.md
  docs/website/src/main/resources/download_gf7.md
Labels: Documentation

#24778 Integrate JNA 5.14
  appserver/libpam4j/pom.xml
Labels: component upgrade
