Repository eclipse-ee4j/glassfish, pull requests merged in 2024-05, with the labels that each got.

#24942 Fix: Display Cluster Monitoring Data in Admin Console
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/MonitoringResource.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/custom/ManagementProxyResource.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/utils/ProxyImpl.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/Utility.java
Labels: bug

#24949 Performance test and fix for logger part of the logging system
  docs/administration-guide/src/main/asciidoc/logging.adoc
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/GlassFishLogger.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/cfg/GlassFishLogManagerConfiguration.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/cfg/GlassFishLoggingConstants.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/formatter/GlassFishLogFormatter.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/handler/LogCollectorHandler.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/handler/LogRecordBuffer.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/handler/LoggingOutputStream.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/record/GlassFishLogRecord.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/GlassFishLoggerPerformanceTest.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/handler/GlassFishLogHandlerTest.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/handler/LoggingPrintStreamTest.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/handler/SimpleLogHandlerTest.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/handler/SyslogHandlerTest.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/record/GlassFishLogRecordTest.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/record/MessageResolverTest.java
Labels: enhancement

#24955 Display debug port
  nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncher.java
Labels: bug

#24959 Fixed IllegalArgumentException + refactoring
  appserver/common/glassfish-naming/src/main/java/com/sun/enterprise/naming/impl/GlassfishNamingManagerImpl.java
  appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/Application.java
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/SecurityContainer.java
  nucleus/deployment/common/src/main/java/com/sun/enterprise/deployment/deploy/shared/JarArchive.java
  nucleus/deployment/common/src/main/java/com/sun/enterprise/deployment/deploy/shared/Util.java
  nucleus/deployment/common/src/test/java/com/sun/enterprise/deployment/deploy/shared/JarArchiveTest.java
Labels: bug, code cleaning

#24961 Updated logging.properties
  nucleus/admin/template/src/main/resources/config/logging.properties
Labels: enhancement

#24963 Improve deployment plan for WAR
  docs/application-deployment-guide/src/main/asciidoc/deploying-applications.adoc
  nucleus/deployment/common/src/main/java/com/sun/enterprise/deployment/deploy/shared/DeploymentPlanArchive.java
Labels: bug

#24966 Integrate Woodstox 6.6.2
  appserver/pom.xml
Labels: component upgrade

#24968 Integrate Yasson 3.0.4
  appserver/pom.xml
Labels: component upgrade

#24970 Integrate Jersey 3.1.7
  nucleus/parent/pom.xml
Labels: component upgrade, ee10-component

#24969 Integrate Commons Codec 1.17.0
  appserver/pom.xml
Labels: component upgrade

#24971 Update SOAP API in appserver tests to 3.0.2
  appserver/tests/application/pom.xml
Labels: build and test improvement

#24972 Integrate JAX-B impl 4.0.5
  nucleus/parent/pom.xml
Labels: component upgrade, ee10-component
