Repository eclipse-ee4j/glassfish, pull requests merged in 2024-12, with the labels that each got.

#25271 Fix CLI031 warning message on executing asadmin ping-connection-pool command
  appserver/connectors/admin/src/main/java/org/glassfish/connectors/admin/cli/PingConnectionPool.java
Labels: bug

#25257 Fix a typo of the WebappClassLoader delegation settings
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
Labels: bug

#25261 Fix #25260 Deprecated settings in Admin Console
  appserver/admingui/war/src/main/webapp/WEB-INF/web.xml
Labels: code cleaning

#25262 Suppress internal processing output on executing asadmin create-local-instance
  nucleus/common/common-util/src/main/java/org/glassfish/admin/payload/PayloadFilesManager.java
Labels: bug

#25279 Disable TLS 1.0 and TLS 1.1 by default
  appserver/admingui/web/src/main/help/en/help/ref-protocolssledit.html
  appserver/admingui/web/src/main/help/en/help/task-protocolssledit.html
  nucleus/admin/config-api/src/test/java/com/sun/enterprise/configapi/tests/Ssl2EnabledTest.java
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/dom/Ssl.java
Labels: security fix

#25270 Improve the connection pool lookup messages
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/service/ConnectorResourceAdminServiceImpl.java
Labels: enhancement

#25284 Improve error messages on deploying apps over upload size limit in Admin Console
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/DeploymentHandler.java
Labels: bug

#25282 Redesign kernel events dispatching facility
  nucleus/core/kernel/pom.xml
  nucleus/core/kernel/src/main/java/org/glassfish/kernel/KernelLoggerInfo.java
  nucleus/core/kernel/src/main/java/org/glassfish/kernel/event/EventsFactory.java
  nucleus/core/kernel/src/main/java/org/glassfish/kernel/event/EventsImpl.java
  nucleus/core/kernel/src/main/java/org/glassfish/kernel/event/OSGiAwareEventsImpl.java
Labels: code cleaning

#25283 Fix versions of X-Powered-By field for empty "product.name"
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/GlassfishNetworkListener.java
Labels: bug

#25294 Remove json-2.0.jar from dependencies
  appserver/admingui/war/pom.xml
  appserver/admingui/war/src/main/webapp/WEB-INF/sun-web.xml
  appserver/pom.xml
Labels: code cleaning

#25289 Fix #25288 asadmin delete-log-levels command fails if the --target option is specified
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java
Labels: bug

#25301 Fixes classloading of the generated classes for the shared EAR libraries
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/ClassGenerator.java
  appserver/itest-tools/src/main/java/org/glassfish/main/itest/tools/GlassFishTestEnvironment.java
  appserver/itest-tools/src/main/java/org/glassfish/main/itest/tools/JarSigner.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/signedear/api/ExampleRemote.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/signedear/impl/ExampleBean.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/signedear/SignedEarDeploymentTest.java
Labels: bug

#25300 Fix creating a lot of ephemeral ports when stopping GlassFish. Fix restart on fast machines
  appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/embedded/EJBContainerImpl.java
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/rest/RestTestBase.java
  appserver/web/web-core/src/main/java/org/apache/catalina/startup/Catalina.java
  nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncher.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/DeleteDomainCommand.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/LocalServerCommand.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/StartServerHelper.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/StopDomainCommand.java
  nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/StopLocalInstanceCommand.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/process/JavaClassRunner.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/process/ProcessUtils.java
  nucleus/core/kernel/pom.xml
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/RestartServer.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/StartServerHook.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/handler/GlassFishLogHandler.java
Labels: bug

#25290 Fix random 403 responses
  nucleus/security/core/src/main/java/com/sun/enterprise/security/SecurityContext.java
Labels: bug
