Repository eclipse-ee4j/glassfish, pull requests merged in 2024-08, with the labels that each got.

#25067 Webpage update for 7.0.16
  docs/pom.xml
  docs/website/src/main/resources/README.md
  docs/website/src/main/resources/download.md
  docs/website/src/main/resources/download_gf7.md
Labels: Documentation

#25073 Validate the structure in all submodules (especially version ids)
  Jenkinsfile
Labels: build and test improvement

#25077 Update Jakarta Validation TCK to 3.1.1
  appserver/tests/tck/tck-download/jakarta-validation-tck/pom.xml
  appserver/tests/tck/validation/pom.xml
  appserver/tests/tck/validation/suite.xml
Labels: build and test improvement

#25082 Fixed dependencies for Servlet TCK
  appserver/tests/tck/servlet/pom.xml
Labels: build and test improvement

#25081 Add profiles to Faces TCK to run subsets
  appserver/tests/tck/faces/pom.xml
Labels: build and test improvement

#25076 Fixes remote JNDI lookup
  appserver/common/glassfish-naming/src/main/java/com/sun/enterprise/naming/impl/RemoteSerialContextProviderImpl.java
  appserver/common/glassfish-naming/src/main/java/com/sun/enterprise/naming/impl/TransientContext.java
Labels: bug

#25080 Fix styling of the command logger button in Admin Console in Chrome
  appserver/admingui/commandrecorder/src/main/resources/META-INF/resources/commandrecorder/plugin/mastheadStatusArea.jsf
Labels: bug

#25084 Website update: Docker and IDE docs, contacts
  docs/website/src/main/resources/CONTRIBUTING.md
  docs/website/src/main/resources/_includes/documentation-toc.html
  docs/website/src/main/resources/_includes/topnav.html
  docs/website/src/main/resources/documentation.md
  docs/website/src/main/resources/download.md
  docs/website/src/main/resources/download_gf7.md
Labels: Documentation

#25087 Fixes #25085 - Use HTTPS in Oracle links of the documentation
  docs/administration-guide/src/main/asciidoc/domains.adoc
  docs/administration-guide/src/main/asciidoc/jms.adoc
  docs/ha-administration-guide/src/main/asciidoc/instances.adoc
  docs/ha-administration-guide/src/main/asciidoc/ssh-setup.adoc
  docs/performance-tuning-guide/src/main/asciidoc/overview.adoc
  docs/reference-manual/src/main/asciidoc/appclient.adoc
  docs/reference-manual/src/main/asciidoc/asadmin.adoc
  docs/reference-manual/src/main/asciidoc/create-service.adoc
  docs/reference-manual/src/main/asciidoc/debug-asadmin.adoc
  docs/reference-manual/src/main/asciidoc/package-appclient.adoc
  docs/reference-manual/src/main/asciidoc/setup-ssh.adoc
  docs/security-guide/src/main/asciidoc/running-in-secure-environment.adoc
Labels: Documentation

#25092 Experimental support of JDK23 and 22 for GlassFish 7
  README.md
  appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/AppClientFacade.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/StaticRmiStubGenerator.java
  nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/AdminMain.java
  nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/LocalStrings.properties
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/JDK.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/MainHelper.java
  nucleus/distributions/nucleus-common/src/main/resources/config/osgi.properties
  nucleus/osgi-platforms/felix/src/main/resources/config/osgi.properties
Labels: component upgrade

#25093 Removed abandoned docker image build
  appserver/distributions/docker/pom.xml
  appserver/distributions/docker/src/main/docker/Dockerfile
  appserver/distributions/docker/src/main/docker/run-glassfish.sh
  appserver/distributions/pom.xml
Labels: code cleaning

#25094 Upgraded command-security-maven-plugin to 1.0.18
  nucleus/parent/pom.xml
Labels: component upgrade

#25090 Document GlassFish API in the Application Development guide
  docs/application-development-guide/pom.xml
  docs/application-development-guide/src/main/asciidoc/class-loaders.adoc
  docs/application-development-guide/src/main/asciidoc/connectors.adoc
  docs/application-development-guide/src/main/asciidoc/container_managed-persistence.adoc
  docs/application-development-guide/src/main/asciidoc/debugging-apps.adoc
  docs/application-development-guide/src/main/asciidoc/ejb.adoc
  docs/application-development-guide/src/main/asciidoc/glassfish-api.adoc
  docs/application-development-guide/src/main/asciidoc/java-clients.adoc
  docs/application-development-guide/src/main/asciidoc/jdbc.adoc
  docs/application-development-guide/src/main/asciidoc/jms.adoc
  docs/application-development-guide/src/main/asciidoc/jndi.adoc
  docs/application-development-guide/src/main/asciidoc/jpa.adoc
  docs/application-development-guide/src/main/asciidoc/lifecycle-listeners.adoc
  docs/application-development-guide/src/main/asciidoc/mail.adoc
  docs/application-development-guide/src/main/asciidoc/osgi.adoc
  docs/application-development-guide/src/main/asciidoc/part-apps-and-app-comps.adoc
  docs/application-development-guide/src/main/asciidoc/part-services-and-apis.adoc
  docs/application-development-guide/src/main/asciidoc/part-tasks-and-tools.adoc
  docs/application-development-guide/src/main/asciidoc/securing-apps.adoc
  docs/application-development-guide/src/main/asciidoc/setting-up-dev-env.adoc
  docs/application-development-guide/src/main/asciidoc/transaction-service.adoc
  docs/application-development-guide/src/main/asciidoc/webapps.adoc
  docs/application-development-guide/src/main/asciidoc/webservices.adoc
Labels: Documentation

#25096 Using release instead of source+target, removing ldapbp module
  README.md
  appserver/ldapbp/pom.xml
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/ctl/AuthorizationIDControl.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/ctl/AuthorizationIDResponseControl.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/ctl/DirSyncControl.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/ctl/DirSyncResponseControl.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/ctl/GetEffectiveRightsControl.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/ctl/PagedResultsControl.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/ctl/PagedResultsResponseControl.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/ctl/PasswordExpiredResponseControl.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/ctl/PasswordExpiringResponseControl.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/ctl/ProxiedAuthorizationControl.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/ctl/RealAttributesOnlyControl.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/ctl/ResponseControlFactory.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/ctl/SortControl.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/ctl/SortKey.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/ctl/SortResponseControl.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/ctl/TreeDeleteControl.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/ctl/VirtualAttributesOnlyControl.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/ctl/VirtualListViewControl.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/ctl/VirtualListViewResponseControl.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/ext/BulkImportFinishedRequest.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/ext/BulkImportStartRequest.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/ext/EmptyExtendedResponse.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/ext/WhoAmIRequest.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/ext/WhoAmIResponse.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/obj/AttrsToCorba.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/obj/CorbaToAttrs.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/obj/GroupOfNames.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/obj/GroupOfURLs.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/obj/GroupOfUniqueNames.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/obj/LdapGroupFactory.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/obj/LdapPrincipal.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/obj/MarshalledToObject.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/obj/RemoteToAttrs.java
  appserver/ldapbp/src/main/java/com/sun/jndi/ldap/obj/RemoteToCorbaToAttrs.java
  appserver/microprofile/config/pom.xml
  appserver/pom.xml
  nucleus/parent/pom.xml
Labels: build and test improvement

#25103 Replace none/only testcompile with full in a profile for JDK 23
  nucleus/parent/pom.xml
Labels: build and test improvement

#25079 Faster autodeploy at startup - do not wait before first autodeployment scan
  nucleus/deployment/autodeploy/src/main/java/org/glassfish/deployment/autodeploy/AutoDeployService.java
Labels: bug

#25108 Integrate Mojarra 4.1.2 and WaSP-M2
  appserver/distributions/glassfish/src/main/patches/jakarta.servlet.jsp.jstl-api/META-INF/MANIFEST.MF
  appserver/pom.xml
Labels: component upgrade, ee11-component

#25088 Improvements and fixes in the SQL trace listener functionality
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/ActiveResourceAdapterImpl.java
  appserver/itest-tools/src/main/java/org/glassfish/main/itest/tools/asadmin/DomainSettings.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/ManagedConnectionFactoryImpl.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/util/SQLTraceDelegator.java
  appserver/tests/application/pom.xml
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/connpool/lib/LastTraceSQLTraceListener.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/connpool/webapp/Employee.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/connpool/webapp/SqlListenerApplication.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/connpool/webapp/SqlListenerEndpoint.java
  appserver/tests/application/src/main/resources/org/glassfish/main/test/app/connpool/webapp/META-INF/load.sql
  appserver/tests/application/src/main/resources/org/glassfish/main/test/app/connpool/webapp/META-INF/persistence.xml
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/connpool/SQLTraceListenerTest.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/persistence/resourceref/JtaDataSourceResourceRefTest.java
  nucleus/common/glassfish-api/src/main/java/org/glassfish/api/jdbc/SQLTraceRecord.java
Labels: bug, enhancement

#25112 Integrate Tags (JSTL) API 3.0.2
  appserver/distributions/glassfish/pom.xml
  appserver/distributions/glassfish/src/main/patches/jakarta.servlet.jsp.jstl-api/META-INF/MANIFEST.MF
  appserver/distributions/web/pom.xml
  appserver/distributions/web/src/main/patches/jakarta.servlet.jsp.jstl-api/META-INF/MANIFEST.MF
  appserver/pom.xml
Labels: component upgrade

#25107 Fix for a ClassCastException when a filter over a WebSocket endpoint wraps the request
  appserver/itest-tools/src/main/java/org/glassfish/main/itest/tools/GlassFishTestEnvironment.java
  appserver/itest-tools/src/main/java/org/glassfish/main/itest/tools/HttpListenerType.java
  appserver/tests/application/pom.xml
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/websocket/CustomRequestResponseServletFilter.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/websocket/HelloWebSocketEndpoint.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/websocket/CustomRequestResponseOnWebSocketTest.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/websocket/WebSocketClient.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/websocket/WebSocketOnDefaultWebModuleTest.java
  appserver/web/web-core/src/main/java/org/apache/catalina/core/WebSocketFilterWrapper.java
Labels: bug

#25115 Spotted bugs in tests
  nucleus/common/glassfish-api/src/test/java/org/glassfish/api/admin/progress/DummyParent.java
  nucleus/common/glassfish-api/src/test/java/org/glassfish/api/admin/progress/ProgressStatusImplTest.java
  nucleus/common/glassfish-api/src/test/java/org/glassfish/api/admin/progress/ProgressStatusMirroringImplTest.java
  nucleus/hk2-config-generator/src/test/java/org/jvnet/hk2/config/test/example/SimpleConfigBeanWrapper.java
  nucleus/hk2-config-generator/src/test/java/org/jvnet/hk2/config/test/example/SimpleConfigViewWrapper.java
Labels: code cleaning

#25114 GJULE - fixed dependency on system default charset
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/formatter/LogFormatDetector.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/handler/GlassFishLogHandler.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/handler/SimpleLogHandler.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/formatter/LogFormatDetectorTest.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/handler/LoggingPrintStreamTest.java
Labels: bug

#25118 Deleted GFBase64* implementations from pre-JDK8 times
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/authentication/glassfish/jdbc/JDBCRealm.java
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModule.java
  nucleus/admin/util/src/main/java/com/sun/enterprise/admin/remote/RemoteAdminCommand.java
  nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/AdminCallbackHandler.java
  nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/HttpConnectorAddress.java
  nucleus/common/common-util/src/main/java/com/sun/appserv/management/client/prefs/MemoryHashLoginInfoStore.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/GFBase64Decoder.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/GFBase64Encoder.java
  nucleus/common/common-util/src/main/java/org/glassfish/security/common/SSHA.java
  nucleus/common/common-util/src/test/java/com/sun/enterprise/universal/BASE64DecoderTest.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/AdminAdapter.java
Labels: code cleaning

#25106 setting local Name and Port for /managment/* URI
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/adapter/RestManagementAdapter.java
Labels: bug, security fix

#25120 Fixes service creation on Solaris operating system
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/services/SMFService.java
Labels: bug

#25119 The common-util: Fixed dependencies on default charset
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/services/WindowsService.java
  nucleus/cluster/ssh/src/main/java/org/glassfish/cluster/ssh/util/SSHUtil.java
  nucleus/common/common-util/src/main/java/com/sun/appserv/server/util/Version.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/security/store/PasswordAdapter.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/glassfish/ASenvPropertyReader.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/process/ProcessManager.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/process/ProcessStreamDrainerWorker.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/process/ProcessUtils.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/xml/MiniXmlParser.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/xml/XmlParserHelper.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/io/FileUtils.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/io/ServerDirs.java
  nucleus/common/common-util/src/main/java/org/glassfish/admin/payload/PayloadImpl.java
  nucleus/common/common-util/src/main/java/org/glassfish/common/util/admin/AsadminInput.java
  nucleus/common/common-util/src/main/java/org/glassfish/common/util/admin/ManPageFinder.java
  nucleus/common/common-util/src/main/java/org/glassfish/security/common/FileRealmHelper.java
  nucleus/common/common-util/src/main/java/org/glassfish/security/common/LocalStrings.properties
  nucleus/common/common-util/src/test/java/org/glassfish/admin/payload/PayloadFilesManagerTest.java
  nucleus/common/common-util/src/test/java/org/glassfish/admin/payload/PayloadImplTest.java
  nucleus/common/common-util/src/test/java/org/glassfish/common/util/admin/locking/FileLockTest.java
  nucleus/distributions/nucleus-common/src/main/resources/config/asenv.bat
  nucleus/distributions/nucleus-common/src/main/resources/config/asenv.conf
Labels: code cleaning

#25122 Fixed EJB business interface annotation processing
  appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/annotation/handlers/AbstractEjbHandler.java
Labels: bug
