Repository eclipse-ee4j/glassfish, pull requests merged in 2024-07, with the labels that each got.

#25015 Integrate EasyMock 5.3.0
  nucleus/parent/pom.xml
Labels: build and test improvement

#25018 Updated HK2 and HK2 inhabitants generator plugin
  nucleus/parent/pom.xml
Labels: component upgrade

#25017 Integrate Parsson 1.1.7
  appserver/pom.xml
Labels: ee10-component

#25016 Add standalone Jakarta JSON Processing Pluggability TCK
  appserver/tests/tck/jsonp_pluggability/pom.xml
  appserver/tests/tck/pom.xml
Labels: build and test improvement

#25019 Remove Jersey-MOXy integration module from GlassFish distributions
  appserver/featuresets/web/pom.xml
Labels: bug

#25023 Fixed CDI TCK signature test
  appserver/tests/tck/cdi/cdi-signature/pom.xml
Labels: build and test improvement

#25025 Integrate EclipseLink-ASM 9.7.0
  appserver/pom.xml
Labels: component upgrade

#25020 Use the standard HK2 topic service
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/web/pom.xml
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/adapter/JerseyContainerCommandService.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/adapter/RestAdapter.java
  nucleus/common/common-util/src/main/java/org/glassfish/hk2util/SimpleTopicDistributionService.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/GlassFishImpl.java
Labels: code cleaning

#25028 Update EE4J/parent to 1.0.9
  appserver/tests/quicklook/pom.xml
  appserver/tests/v2-tests/appserv-tests/util/reportbuilder/pom.xml
  nucleus/parent/pom.xml
Labels: component upgrade

#25029 Test based on reproducer in issue #23266 (passing)
  appserver/tests/application/pom.xml
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/rest/convert/webapp/ParamConverterApplication.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/rest/convert/webapp/ParamConverterResource.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/rest/convert/webapp/PatternParamConverterProvider.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/rest/convert/RestParamConverterTest.java
Labels: build and test improvement

#25030 Integrate EclipseLink 4.0.3
  appserver/pom.xml
Labels: ee10-component

#25032 Fixes Jakarta Servlet API version
  appserver/pom.xml
  appserver/tests/cdi/cases/preDestroyScoping/web/pom.xml
  appserver/tests/hk2/cdi/ear/war1/pom.xml
  appserver/tests/hk2/cdi/ear/war2/pom.xml
  appserver/tests/hk2/isolation/web/iso1/pom.xml
  appserver/tests/hk2/isolation/web/iso2/pom.xml
Labels: bug, build and test improvement

#25003 Integrate Woodstox 7.0.0
  appserver/pom.xml
  nucleus/parent/pom.xml
Labels: component upgrade

#25040 Update Weld to 6 beta 4 and Faces to 4.1.1
  appserver/distributions/glassfish/pom.xml
  appserver/distributions/glassfish/src/main/patches/jakarta.enterprise.cdi-el-api/META-INF/MANIFEST.MF
  appserver/distributions/glassfish/src/main/patches/jakarta.enterprise.concurrent/META-INF/MANIFEST.MF
  appserver/distributions/glassfish/src/main/patches/tyrus-client/META-INF/MANIFEST.MF
  appserver/distributions/glassfish/src/main/patches/weld-osgi-bundle/META-INF/MANIFEST.MF
  appserver/pom.xml
Labels: component upgrade, ee11-component

#25038 Optimize GJULE log record source autodetection
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/record/GlassFishLogRecord.java
Labels: code cleaning

#25046 Improve GJULE log message source detection
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/record/GlassFishLogRecord.java
Labels: code cleaning

#25051 Integrate Expression Language API 6.0.1
  nucleus/parent/pom.xml
Labels: component upgrade, ee11-component

#25053 Update various maven plug-in versions
  appserver/pom.xml
  appserver/tests/application/pom.xml
  docs/sample-app/pom.xml
  nucleus/parent/pom.xml
Labels: build and test improvement

#25037 Admin Logger: Invoke event from a single central point
  appserver/tests/extras/command-logger/src/test/java/org/glassfish/main/test/extras/commandlogger/CommandLoggerITest.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/admin/CommandResource.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/utils/ResourceUtil.java
  nucleus/common/internal-api/src/main/java/org/glassfish/internal/api/events/CommandInvokedEvent.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/CommandRunnerImpl.java
  nucleus/extras/command-logger/src/main/java/org/glassfish/extras/commandlogger/AdminCommandLogger.java
  nucleus/test-utils/pom.xml
  nucleus/test-utils/src/main/java/org/glassfish/tests/utils/junit/HK2JUnit5Extension.java
Labels: code cleaning

#25055 Fixed NPE and upgraded to latest visitor version
  nucleus/hk2-config-generator/src/main/java/org/jvnet/hk2/config/generator/ConfigInjectorGenerator.java
Labels: bug

#25056 Refactoring in security (TLS)
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/deployment/DFDeploymentProperties.java
  appserver/appclient/client/acc/src/test/java/org/glassfish/appclient/client/acc/callbackhandler/DefaultGUICallbackHandlerTest.java
  appserver/appclient/server/core/src/main/java/org/glassfish/appclient/server/core/jws/JavaWebStartInfo.java
  appserver/appclient/server/core/src/main/java/org/glassfish/appclient/server/core/jws/servedcontent/ASJarSigner.java
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/SecurityUtil.java
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/jmac/callback/GlassFishBaseCallbackHandler.java
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/web/integration/SecurityRoleMapperFactoryGen.java
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/web/integration/WebSecurityManager.java
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/connector/coyote/PECoyoteConnector.java
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/pluggable/WebContainerFeatureFactory.java
  nucleus/admin/config-api/pom.xml
  nucleus/admin/util/src/main/java/com/sun/enterprise/admin/commands/CreateSsl.java
  nucleus/common/common-util/src/main/java/org/glassfish/security/common/MasterPassword.java
  nucleus/common/common-util/src/test/java/com/sun/enterprise/universal/process/ProcessManagerTest.java
  nucleus/common/glassfish-api/pom.xml
  nucleus/common/internal-api/pom.xml
  nucleus/common/mbeanserver/src/main/java/org/glassfish/admin/mbeanserver/ssl/SecureRMIServerSocketFactory.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/osgi/EmbeddedOSGiGlassFishImpl.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/DynamicReloader.java
  nucleus/deployment/common/src/main/java/org/glassfish/deployment/common/DeploymentUtils.java
  nucleus/grizzly/config/pom.xml
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/SSLConfigurator.java
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/Utils.java
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/ssl/JSSE14SocketFactory.java
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/ssl/JSSE14Support.java
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/ssl/JSSEFactory.java
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/ssl/JSSESupport.java
  nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/ssl/SSLImplementation.java
  nucleus/grizzly/config/src/test/java/org/glassfish/grizzly/config/test/JSSEImplementation4Tests.java
  nucleus/security/core/pom.xml
  nucleus/security/core/src/main/java/com/sun/enterprise/security/SecurityLoggerInfo.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/admin/cli/SecureAdminCommand.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/admin/cli/SecureAdminConfigUpgrade.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/common/EmbeddedSecurityLifeCycle.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/ssl/GlassfishSSLImpl.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/ssl/GlassfishSSLSupport.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/ssl/GlassfishServerSocketFactory.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/ssl/SSLUtils.java
  nucleus/security/ssl-impl/pom.xml
  nucleus/security/ssl-impl/src/main/java/com/sun/enterprise/security/ssl/impl/MasterPasswordImpl.java
  nucleus/security/ssl-impl/src/main/java/com/sun/enterprise/security/ssl/impl/SecuritySupportImpl.java
  nucleus/security/ssl-impl/src/main/java/com/sun/enterprise/server/pluggable/SecuritySupport.java
Labels: code cleaning
