Repository eclipse-ee4j/glassfish, pull requests merged in 2024-04, with the labels that each got.

#24891 Integrate Maven Surefire plugin 3.2.5
  nucleus/parent/pom.xml
Labels: build and test improvement

#24893 Webpage update for 7.0.14
  docs/pom.xml
  docs/website/src/main/resources/README.md
  docs/website/src/main/resources/download.md
  docs/website/src/main/resources/download_gf7.md
Labels: Documentation

#24896 Integrate Maven Clean plugin 3.3.2
  nucleus/parent/pom.xml
Labels: build and test improvement

#24894 Integrate Maven Git Commit Id plugin 8.0.2
  nucleus/parent/pom.xml
Labels: build and test improvement

#24895 Integrate Maven Compiler plugin 3.13.0
  nucleus/parent/pom.xml
Labels: build and test improvement

#24897 Integrate Maven Javadoc plugin 3.6.3
  nucleus/parent/pom.xml
Labels: build and test improvement

#24902 Update Versions Maven plugin to 2.16.2
  nucleus/parent/pom.xml
Labels: build and test improvement

#24903 Fixes cross-references in Administration Guide
  docs/administration-guide/src/main/asciidoc/general-administration.adoc
  docs/administration-guide/src/main/asciidoc/logging.adoc
  docs/administration-guide/src/main/asciidoc/overview.adoc
Labels: Documentation

#24905 Integrate Commons IO 2.16.1
  nucleus/parent/pom.xml
Labels: component upgrade

#24907 Integrate Helidon Microprofile Config 3.2.7
  appserver/pom.xml
Labels: component upgrade

#24906 Integrate JaCoCo 0.8.12
  nucleus/parent/pom.xml
  pom.xml
  runtests.sh
Labels: build and test improvement

#24908 Integrate Jersey 3.1.6
  nucleus/parent/pom.xml
Labels: ee10-component

#24888 Enable CDI Lang Model TCK
  appserver/tests/tck/cdi/cdi-model/pom.xml
  appserver/tests/tck/cdi/cdi-model/src/test/java/org/glassfish/tck/cdi/lang/model/CDILangModelTCKRunner.java
  appserver/tests/tck/cdi/cdi-model/src/test/java/org/glassfish/tck/cdi/lang/model/CleanupExtension.java
  appserver/tests/tck/cdi/cdi-model/src/test/java/org/glassfish/tck/cdi/lang/model/LangModelVerifierBuildCompatibleExtension.java
Labels: build and test improvement

#24909 Update Jakarta RESTful Web Services TCK to 3.1.5
  appserver/tests/tck/rest/pom.xml
  appserver/tests/tck/tck-download/jakarta-rest-tck/pom.xml
Labels: build and test improvement

#24910 Integrate Jakarta Activation 2.1.3
  nucleus/parent/pom.xml
Labels: ee10-component

#24911 Integrate Jakarta Mail 2.1.3
  nucleus/parent/pom.xml
Labels: ee10-component

#24912 Integrate Eclipse Parsson 1.1.6
  appserver/pom.xml
Labels: ee10-component

#24914 Integrate JBoss Class File Writer 1.3.1.Final
  appserver/pom.xml
Labels: component upgrade

#24913 Integrate Jakarta JSON Binding 3.0.1
  appserver/pom.xml
Labels: ee10-component

#24915 Integrate Mojarra 4.0.7
  appserver/pom.xml
Labels: ee10-component

#24916 Align JUnit5 version in REST CDI TCK with the nucleus parent
  appserver/tests/tck/rest_cdi/pom.xml
Labels: build and test improvement

#24920 Fixed using wrong java command in TCK authentication and managing failures
  appserver/tests/tck/authentication/pom.xml
Labels: bug, build and test improvement

#24921 Fixed package name of the Audit class
  appserver/admin/admin-core/src/test/resources/UpgradeTest.xml
  appserver/admin/template/src/main/resources/config/domain.xml
  appserver/connectors/admin/src/test/resources/DomainTest.xml
  appserver/connectors/connectors-internal-api/src/test/resources/DomainTest.xml
  appserver/connectors/connectors-internal-api/src/test/resources/PasswordAliasTest.xml
  appserver/jdbc/admin/src/test/resources/DomainTest.xml
  appserver/jdbc/jdbc-runtime/src/test/resources/DomainTest.xml
  appserver/orb/orb-connector/src/test/resources/DomainTest.xml
  appserver/resources/mail/mail-connector/src/test/resources/DomainTest.xml
  appserver/resources/resources-connector/src/test/resources/DomainTest.xml
  appserver/tests/embedded/web/web-api/src/main/resources/org/glassfish/tests/webapi/domain.xml
  nucleus/admin/config-api/src/main/java/org/glassfish/config/support/DefaultConfigUpgrade.java
  nucleus/admin/config-api/src/test/resources/ClusterDomain.xml
  nucleus/admin/config-api/src/test/resources/DomainTest.xml
  nucleus/admin/config-api/src/test/resources/parser/c1i1.xml
  nucleus/admin/config-api/src/test/resources/parser/c1i1c1i2.xml
  nucleus/admin/config-api/src/test/resources/parser/i1.xml
  nucleus/admin/config-api/src/test/resources/parser/i1i2.xml
  nucleus/admin/config-api/src/test/resources/parser/noconfigfori1.xml
  nucleus/admin/config-api/src/test/resources/parser/stock.xml
  nucleus/admin/launcher/src/test/resources/domains/baddomain/config/domain.xml
  nucleus/admin/launcher/src/test/resources/domains/domain1/config/domain.xml
  nucleus/admin/launcher/src/test/resources/domains/domain2/config/domain.xml
  nucleus/admin/launcher/src/test/resources/domains/domain3/config/domain.xml
  nucleus/admin/launcher/src/test/resources/domains/domainNoLog/config/domain.xml
  nucleus/common/common-util/src/test/resources/adminport.xml
  nucleus/common/common-util/src/test/resources/adminport2.xml
  nucleus/common/common-util/src/test/resources/big.xml
  nucleus/common/common-util/src/test/resources/clusters1.xml
  nucleus/common/common-util/src/test/resources/hasprofiler.xml
  nucleus/common/common-util/src/test/resources/manysysprops.xml
  nucleus/common/common-util/src/test/resources/monitoringFalse.xml
  nucleus/common/common-util/src/test/resources/monitoringNone.xml
  nucleus/common/common-util/src/test/resources/monitoringTrue.xml
  nucleus/common/common-util/src/test/resources/noconfig.xml
  nucleus/common/common-util/src/test/resources/nodomainname.xml
  nucleus/common/common-util/src/test/resources/olddomain.xml
  nucleus/common/common-util/src/test/resources/rightorder.xml
  nucleus/common/common-util/src/test/resources/rightordernoclosedomain.xml
  nucleus/common/common-util/src/test/resources/wrongorder.xml
  nucleus/common/common-util/src/test/resources/wrongordernoclosedomain.xml
  nucleus/core/kernel/src/main/resources/org/glassfish/embed/domain.xml
  nucleus/core/kernel/src/test/resources/DomainTest.xml
Labels: bug, breaking change

#24917 Update the Administration Console description in the Administration Guide
  docs/administration-guide/src/main/asciidoc/overview.adoc
Labels: Documentation

#24922 Fix embedded web test
  appserver/tests/embedded/utils/pom.xml
  appserver/tests/embedded/utils/src/main/java/org/glassfish/tests/embedded/utils/EmbeddedServerUtils.java
  appserver/tests/embedded/web/servlet/pom.xml
  appserver/tests/embedded/web/servlet/src/main/java/org/glassfish/tests/embedded/web/servlet/HelloWorld.java
  appserver/tests/embedded/web/servlet/src/test/java/org/glassfish/tests/embedded/web/servlet/Application.java
  appserver/tests/embedded/web/servlet/src/test/java/org/glassfish/tests/embedded/web/servlet/ServletMain.java
  appserver/tests/embedded/web/servlet/src/test/java/org/glassfish/tests/embedded/web/servlet/WebClientITest.java
  nucleus/common/internal-api/src/main/java/org/glassfish/internal/embedded/Server.java
Labels: code cleaning, build and test improvement

#24923 Integrate Exousia 2.1.2
  appserver/pom.xml
Labels: ee10-component

#24919 Code cleanups made when I was working on Exousia 2.1.2-SNAPSHOT
  appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/security/application/EJBSecurityManager.java
  appserver/ejb/ejb-container/src/main/resources/com/sun/logging/enterprise/system/container/ejb/LogStrings.properties
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/web/integration/GlassfishRoleMapper.java
Labels: code cleaning

#24925 Revised Ant exec usages in TCK + TCK 10.0.4
  appserver/tests/tck/activation/pom.xml
  appserver/tests/tck/authentication/pom.xml
  appserver/tests/tck/authorization/pom.xml
  appserver/tests/tck/connectors-full/pom.xml
  appserver/tests/tck/connectors/pom.xml
  appserver/tests/tck/expression_language/pom.xml
  appserver/tests/tck/pages/pom.xml
  appserver/tests/tck/pages_debugging/pom.xml
  appserver/tests/tck/pages_tags/pom.xml
  appserver/tests/tck/servlet/pom.xml
  appserver/tests/tck/tck-download/jakarta-connectors-full-tck/pom.xml
  appserver/tests/tck/tck-download/jakarta-platform-tck/pom.xml
  appserver/tests/tck/websocket/pom.xml
Labels: build and test improvement

#24935 Remove unsupported Maven option from Jakarta REST TCK installer's POM
  appserver/tests/tck/tck-download/jakarta-rest-tck/pom.xml
Labels: code cleaning

#24934 Fixes GlassFish home in the REST CDI TCK
  appserver/tests/tck/rest_cdi/pom.xml
Labels: bug, build and test improvement

#24929 Refactor CDI TCK
  appserver/tests/tck/cdi/cdi-full/pom.xml
  appserver/tests/tck/cdi/cdi-model/pom.xml
  appserver/tests/tck/cdi/cdi-model/src/test/java/org/glassfish/tck/cdi/lang/model/CDILangModelTCKRunner.java
  appserver/tests/tck/cdi/cdi-signature/pom.xml
  appserver/tests/tck/cdi/pom.xml
Labels: code cleaning, build and test improvement

#24933 Classloader matching for BeanDeploymentArchives
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/DeploymentImpl.java
Labels: bug

#24932 Fix #24931 compare with known size of 'usedResourceHandles' instead of theoretical maximum 'maxConnectionPoolSize'
  appserver/connectors/connectors-runtime/src/test/java/com/sun/enterprise/resource/pool/ConnectionPoolTest.java
Labels: build and test improvement

#24937 Integrate JLine 3.26.0
  nucleus/parent/pom.xml
Labels: component upgrade

#24938 Fixes keytool executable name on Windows in integration test tools
  appserver/itest-tools/src/main/java/org/glassfish/main/itest/tools/GlassFishTestEnvironment.java
Labels: bug, build and test improvement, Windows

#24939 Add Jakarta JSON Processing standalone TCK runner
  appserver/tests/tck/jsonp/pom.xml
  appserver/tests/tck/pom.xml
Labels: build and test improvement
