Repository eclipse-ee4j/glassfish, pull requests merged in 2024-02, with the labels that each got.

#24773 RecoveryManager thread safety
  appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/DelegatedRecoveryManager.java
  appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/RecoveryManager.java
Labels: bug

#24780 Update download page for 7.0.12
  docs/pom.xml
Labels: Documentation

#24781 Fixes `schedule-exp` EJB timer test
  appserver/tests/appserv-tests/devtests/ejb/ejb31/timer31/schedule_exp/ejb/StlesEJB.java
Labels: bug, build and test improvement

#24785 Fixes issue #24784, cannot build doc modules on Windows
  docs/administration-guide/src/main/asciidoc/logging.adoc
  docs/error-messages-reference/src/main/asciidoc/error-messages.adoc
Labels: Documentation

#24786 Updated artifactId of gf docs in the website publisher
  docs/publish/pom.xml
Labels: build and test improvement, Documentation

#24789 Fixes #24788 No stacktrace is printed in server log when exception occurs in class specified by Lifecycle Module
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ServerLifecycleModule.java
Labels: bug

#24791 I forgot to change also groupId
  docs/publish/pom.xml
Labels: build and test improvement, Documentation

#24787 Add code conventions (taken from the EE4J ones that got lost)
  CODE_CONVENTIONS.md
Labels: Documentation

#24793 Fixes data race during Admin Console initialization
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/adapter/AdminConsoleAdapter.java
Labels: bug

#24796 Fixes GlassFish event filtering
  nucleus/core/kernel/src/main/java/org/glassfish/kernel/event/EventsImpl.java
Labels: bug

#24803 Fixes issue #24746 replaces all http://www.oracle.com/technetwork links with their https://jakarta.ee/ counterpart where possible.
  appserver/admingui/cluster/src/main/help/en/help/ref-standaloneinstancegeneral.html
  appserver/admingui/common/src/main/help/en/help/ref-predefinedconfigsysproperties.html
  docs/administration-guide/src/main/asciidoc/transactions.adoc
  docs/application-deployment-guide/src/main/asciidoc/overview.adoc
  docs/application-development-guide/src/main/asciidoc/java-clients.adoc
  docs/application-development-guide/src/main/asciidoc/jdbc.adoc
  docs/application-development-guide/src/main/asciidoc/jndi.adoc
  docs/application-development-guide/src/main/asciidoc/securing-apps.adoc
  docs/application-development-guide/src/main/asciidoc/transaction-service.adoc
  docs/application-development-guide/src/main/asciidoc/webapps.adoc
  docs/deployment-planning-guide/src/main/asciidoc/checklist.adoc
  docs/embedded-server-guide/src/main/asciidoc/embedded-server-guide.adoc
  docs/installation-guide/src/main/asciidoc/installing.adoc
  docs/performance-tuning-guide/src/main/asciidoc/tuning-apps.adoc
  docs/performance-tuning-guide/src/main/asciidoc/tuning-java.adoc
  docs/reference-manual/src/main/asciidoc/copy-config.adoc
  docs/reference-manual/src/main/asciidoc/create-cluster.adoc
  docs/reference-manual/src/main/asciidoc/create-domain.adoc
  docs/reference-manual/src/main/asciidoc/create-instance.adoc
  docs/reference-manual/src/main/asciidoc/create-local-instance.adoc
  docs/reference-manual/src/main/asciidoc/restart-domain.adoc
  docs/reference-manual/src/main/asciidoc/restart-instance.adoc
  docs/reference-manual/src/main/asciidoc/restart-local-instance.adoc
  docs/reference-manual/src/main/asciidoc/start-instance.adoc
  docs/reference-manual/src/main/asciidoc/start-local-instance.adoc
  docs/release-notes/src/main/asciidoc/release-notes.adoc
  docs/security-guide/src/main/asciidoc/user-security.adoc
  docs/troubleshooting-guide/src/main/asciidoc/overview.adoc
  nucleus/admin/config-api/src/main/manpages/com/sun/enterprise/config/serverbeans/create-cluster.1
  nucleus/admin/server-mgmt/src/main/manpages/com/sun/enterprise/admin/servermgmt/cli/create-domain.1
  nucleus/admin/server-mgmt/src/main/manpages/com/sun/enterprise/admin/servermgmt/cli/restart-domain.1
  nucleus/admin/server-mgmt/src/main/manpages/com/sun/enterprise/admin/servermgmt/cli/start-domain.1
  nucleus/cluster/admin/src/main/manpages/com/sun/enterprise/v3/admin/cluster/copy-config.1
  nucleus/cluster/admin/src/main/manpages/com/sun/enterprise/v3/admin/cluster/create-instance.1
  nucleus/cluster/admin/src/main/manpages/com/sun/enterprise/v3/admin/cluster/restart-instance.1
  nucleus/cluster/admin/src/main/manpages/com/sun/enterprise/v3/admin/cluster/start-cluster.1
  nucleus/cluster/admin/src/main/manpages/com/sun/enterprise/v3/admin/cluster/start-instance.1
  nucleus/cluster/cli/src/main/manpages/com/sun/enterprise/admin/cli/cluster/create-local-instance.1
  nucleus/cluster/cli/src/main/manpages/com/sun/enterprise/admin/cli/cluster/restart-local-instance.1
  nucleus/cluster/cli/src/main/manpages/com/sun/enterprise/admin/cli/cluster/start-local-instance.1
Labels: Documentation

#24804 Refactor GlassFish events processing
  appserver/batch/glassfish-batch-connector/src/main/java/org/glassfish/batch/spi/impl/BatchRuntimeHelper.java
  appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/managedbean/ManagedBeanManagerImpl.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/module/ConnectorApplication.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/module/ConnectorDeployer.java
  appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/startup/EjbDeployer.java
  appserver/ha/ha-shoal-cache-bootstrap/src/main/java/org/glassfish/ha/store/adapter/cache/ShoalBackingStoreProxy.java
  appserver/orb/orb-connector/src/main/java/org/glassfish/enterprise/iiop/api/GlassFishORBHelper.java
  appserver/persistence/jpa-container/src/main/java/org/glassfish/persistence/jpa/JPADeployer.java
  appserver/resources/resources-runtime/src/main/java/org/glassfish/resources/module/ResourcesDeployer.java
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/SecurityDeployer.java
  appserver/transaction/internal-api/src/main/java/com/sun/enterprise/transaction/startup/TransactionLifecycleService.java
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebContainer.java
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java
  nucleus/admin/monitor/src/main/java/org/glassfish/admin/monitor/MonitoringBootstrap.java
  nucleus/cluster/gms-adapter/src/main/java/org/glassfish/gms/GMSAdapterImpl.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/impl/AMXStartupService.java
  nucleus/common/glassfish-api/src/main/java/org/glassfish/api/event/EventListener.java
  nucleus/common/glassfish-api/src/main/java/org/glassfish/api/event/EventTypes.java
  nucleus/common/glassfish-api/src/main/java/org/glassfish/api/event/Events.java
  nucleus/common/glassfish-api/src/main/java/org/glassfish/api/event/RestrictTo.java
  nucleus/common/internal-api/src/main/java/org/glassfish/internal/data/ApplicationInfo.java
  nucleus/common/internal-api/src/main/java/org/glassfish/internal/data/ModuleInfo.java
  nucleus/common/mbeanserver/src/main/java/org/glassfish/admin/mbeanserver/JMXStartupService.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/AdminAdapter.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/JobManagerService.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/adapter/AdminConsoleAdapter.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/AppServerStartup.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLoaderService.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/DomainCreationStartup.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/LifecycleModuleService.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/services/impl/GrizzlyService.java
  nucleus/core/kernel/src/main/java/org/glassfish/kernel/FileMonitoringImpl.java
  nucleus/core/kernel/src/main/java/org/glassfish/kernel/event/EventsImpl.java
  nucleus/core/kernel/src/test/java/com/sun/enterprise/v3/server/AppServerStartupTest.java
  nucleus/core/kernel/src/test/java/org/glassfish/tests/kernel/deployment/EventsTest.java
  nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/CreateApplicationRefCommand.java
  nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/DeployCommand.java
  nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/UndeployCommand.java
Labels: code cleaning

#24807 Fixes log message info
  docs/error-messages-reference/src/main/asciidoc/error-messages.adoc
  docs/error-messages-reference/src/main/asciidoc/title.adoc
  nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/AdminLoggerInfo.java
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/util/AMXLoggerInfo.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/CULoggerInfo.java
  nucleus/common/internal-api/src/main/java/org/glassfish/internal/api/InternalLoggerInfo.java
  nucleus/core/kernel/src/main/java/org/glassfish/kernel/KernelLoggerInfo.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/SecurityLoggerInfo.java
Labels: code cleaning, Documentation

#24806 GlassFishORBHelper changed to singleton, lifecycle
  appserver/orb/orb-connector/src/main/java/org/glassfish/enterprise/iiop/api/GlassFishORBHelper.java
  appserver/orb/orb-connector/src/main/java/org/glassfish/enterprise/iiop/api/ProtocolManager.java
  appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/PEORBConfigurator.java
Labels: bug

#24809 Fixes contribution year in the Guides
  docs/add-on-component-development-guide/src/main/asciidoc/title.adoc
  docs/administration-guide/src/main/asciidoc/title.adoc
  docs/application-deployment-guide/src/main/asciidoc/title.adoc
  docs/application-development-guide/src/main/asciidoc/title.adoc
  docs/deployment-planning-guide/src/main/asciidoc/title.adoc
  docs/embedded-server-guide/src/main/asciidoc/title.adoc
  docs/ha-administration-guide/src/main/asciidoc/title.adoc
  docs/installation-guide/src/main/asciidoc/title.adoc
  docs/performance-tuning-guide/src/main/asciidoc/title.adoc
  docs/quick-start-guide/src/main/asciidoc/title.adoc
  docs/reference-manual/src/main/asciidoc/title.adoc
  docs/release-notes/src/main/asciidoc/title.adoc
  docs/security-guide/src/main/asciidoc/title.adoc
  docs/troubleshooting-guide/src/main/asciidoc/title.adoc
  docs/upgrade-guide/src/main/asciidoc/title.adoc
Labels: Documentation

#24810 Add event filtering test
  nucleus/core/kernel/src/test/java/org/glassfish/tests/kernel/deployment/EventFilteringTest.java
Labels: build and test improvement

#24812 Increase `stop-domain` command timeout in tests
  appserver/itest-tools/src/main/java/org/glassfish/main/itest/tools/GlassFishTestEnvironment.java
Labels: build and test improvement

#24813 Take into account JDK versions when patching jars
  appserver/distributions/glassfish/pom.xml
Labels: build and test improvement

#24815 Store the DistinguishedPrincipalCredential in the Subject principals
  appserver/security/webintegration/src/main/java/com/sun/web/security/RealmAdapter.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/SecurityContext.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/login/DistinguishedPrincipalCredential.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/realm/certificate/CertificateRealm.java
Labels: bug

#24817 Fixes #24816 Non-ASCII characters are not saved correctly in JVM options added using the JVM Options page
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/SecurityHandler.java
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/handlers/UtilHandlers.java
Labels: bug

#24820 Integrate JUnit 5.10.2
  nucleus/parent/pom.xml
Labels: build and test improvement

#24821 Integrate Helidon MicroProfile Config 3.2.6
  appserver/pom.xml
Labels: component upgrade

#24824 Integrate Jackson 2.16.1
  nucleus/parent/pom.xml
Labels: component upgrade

#24823 Integrate Commons Codec 1.16.1
  appserver/pom.xml
Labels: component upgrade

#24825 Jackson Databind does not longer need its own version.
  nucleus/parent/pom.xml
Labels: build and test improvement

#24826 Integrate Aries 1.3.7
  nucleus/parent/pom.xml
Labels: component upgrade

#24827 Integrate XMLSec 4.0.2
  appserver/pom.xml
Labels: component upgrade

#24828 Fixes `applications-tests` on Windows
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/security/jmac/http/servlet/basic/HttpServletBasicAuthTest.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/security/jmac/http/servlet/challenge/HttpServletChallengeAuthTest.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/security/jmac/http/soap/embedded/HttpSoapEmbeddedAuthTest.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/security/multirolemapping/MultiRoleMappingTest.java
Labels: bug, build and test improvement, Windows

#24829 Add console loading option to the domain template
  appserver/admin/template/src/main/resources/config/domain.xml
Labels: enhancement

#24811 Unregister event listeners from uninstalled bundles
  nucleus/core/kernel/src/main/java/org/glassfish/kernel/event/EventsImpl.java
Labels: bug

#24834 Integrate HK2 3.1.0 and JSF Template 4.0.4
  appserver/pom.xml
  nucleus/parent/pom.xml
Labels: component upgrade

#24830 Improve OSGi interactive console
  nucleus/osgi-platforms/osgi-cli-interactive/src/main/java/org/glassfish/osgi/cli/interactive/LocalOSGiShellCommand.java
Labels: enhancement

#24831 Integrate JLine 3.25.1
  nucleus/parent/pom.xml
Labels: component upgrade
