Repository eclipse-ee4j/glassfish, pull requests merged in 2024-10, with the labels that each got.

#25173 GJULE - Easier default configuration
  nucleus/glassfish-jul-extension/pom.xml
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/GlassFishLogManager.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/GlassFishLogManagerInitializer.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/cfg/GlassFishLoggingConstants.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/formatter/OneLineFormatter.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/GlassFishLogManagerLifeCycleTest.java
  nucleus/parent/pom.xml
Labels: enhancement

#25172 Smaller cleanups
  appserver/appclient/server/core/src/main/java/org/glassfish/appclient/server/core/CarHandler.java
  appserver/deployment/jakartaee-core/src/main/java/org/glassfish/javaee/core/deployment/JavaEEDeployer.java
  appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/EjbJarHandler.java
  appserver/extras/embedded/common/bootstrap/pom.xml
  appserver/extras/embedded/common/bootstrap/src/main/java/org/glassfish/uberjar/bootstrap/UberJarOSGiGlassFishRuntimeBuilder.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/ManagedConnectionFactoryImpl.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/resources/com/sun/gjc/spi/LogStrings.properties
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/ClusterITest.java
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/OSGiCommandsITest.java
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/webapp/HttpServerNameITest.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/connpool/SQLTraceListenerTest.java
  appserver/web/web-core/src/main/java/org/apache/catalina/mbeans/.gitkeep_empty_dir
  appserver/web/web-core/src/main/java/org/apache/coyote/http11/.gitkeep_empty_dir
  appserver/web/web-core/src/main/java/org/apache/tomcat/util/buf/res/.gitkeep_empty_dir
  appserver/web/web-core/src/main/java/org/apache/tomcat/util/collections/.gitkeep_empty_dir
  appserver/web/web-core/src/main/java/org/apache/tomcat/util/compat/.gitkeep_empty_dir
  appserver/web/web-core/src/main/java/org/apache/tomcat/util/http/res/.gitkeep_empty_dir
  appserver/web/web-core/src/main/java/org/apache/tomcat/util/net/res/.gitkeep_empty_dir
  appserver/web/web-core/src/main/java/org/apache/tomcat/util/res/.gitkeep_empty_dir
  appserver/web/web-core/src/main/java/org/apache/tomcat/util/threads/res/.gitkeep_empty_dir
  appserver/web/web-core/src/main/java/org/glassfish/web/util/.gitkeep_empty_dir
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebDeployer.java
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModuleListener.java
  appserver/web/web-glue/src/main/java/org/glassfish/web/jsp/JSPCompiler.java
  appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/monitoring/WebServiceTesterServlet.java
  nucleus/admin/launcher/pom.xml
  nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/ArgumentManager.java
  nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFEmbeddedLauncher.java
  nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncher.java
  nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncherConstants.java
  nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncherLogger.java
  nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncherMain.java
  nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncherNativeHelper.java
  nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/JvmOptions.java
  nucleus/admin/launcher/src/main/resources/com/sun/enterprise/admin/launcher/LocalStrings.properties
  nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/glassfish/ASenvPropertyReader.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/EarlyLogger.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/LocalStrings.properties
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/io/InstanceDirs.java
  nucleus/common/common-util/src/main/java/org/glassfish/common/util/CommonUtilsActivator.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/LocalStrings.properties
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/RestartServer.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LoggerInfoMetadataService.java
  nucleus/deployment/common/src/main/java/org/glassfish/deployment/common/LocalStrings.properties
  nucleus/deployment/common/src/main/java/org/glassfish/loader/util/ASClassLoaderUtil.java
  nucleus/deployment/common/src/main/resources/org/glassfish/deployment/common/LocalStrings.properties
  nucleus/deployment/common/src/test/java/com/sun/enterprise/deploy/shared/FileArchiveTest.java
Labels: code cleaning

#25174 Reduced number of builds to keep from 10 to 2 as requested by Jenkins ops
  Jenkinsfile
Labels: build and test improvement

#25161 Enhance start-db command - initdb and suspend
  appserver/admin/cli-optional/src/main/java/com/sun/enterprise/admin/cli/optional/DerbyControl.java
  appserver/admin/cli-optional/src/main/java/com/sun/enterprise/admin/cli/optional/DerbyExecuteSQL.java
  appserver/admin/cli-optional/src/main/java/com/sun/enterprise/admin/cli/optional/StartDatabaseCommand.java
  docs/reference-manual/src/main/asciidoc/start-database.adoc
Labels: New feature

#25177 Reduced number of builds to keep from 10 to 2 as requested by Jenkins ops
  Jenkinsfile
Labels: build and test improvement

#25179 Fixed default-web.xml
  appserver/admin/template/src/main/resources/config/default-web.xml
Labels: bug

#25180 CLI Environment - more useful log file
  nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/CLIUtil.java
  nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/Environment.java
Labels: code cleaning, breaking change

#25181 GlassFish Launchers - code cleanup
  nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFDomainLauncher.java
  nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFEmbeddedLauncher.java
  nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncherConstants.java
  nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncherFactory.java
  nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GlassFishMainLauncher.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/ASMain.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/GlassFishMain.java
Labels: code cleaning

#25182 Updated logging-annotation-processor with JPMS.
  nucleus/parent/pom.xml
Labels: component upgrade

#25189 IntelliJ plugin fix: bring back the previous constructor to avoid a breaking change
  nucleus/admin/util/src/main/java/com/sun/enterprise/admin/remote/RemoteResponseManager.java
Labels: bug

#25194 Integrate JLine 3.27.1
  nucleus/parent/pom.xml
Labels: component upgrade

#25195 Integrate Helidon MicroProfile Config 3.2.10
  appserver/pom.xml
Labels: component upgrade

#25176 Issue #24900 add a few unit tests for ManagedConnectionImpl and ConnectionHolder to understand associateConnection logic
  appserver/jdbc/jdbc-ra/jdbc-core/pom.xml
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/DSManagedConnectionFactory.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/ManagedConnectionImpl.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/base/ConnectionHolder.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/resources/com/sun/gjc/spi/LogStrings.properties
  appserver/jdbc/jdbc-ra/jdbc-core/src/test/java/com/sun/gjc/spi/AbstractManagedConnectionFactoryImplTest.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/test/java/com/sun/gjc/spi/CPManagedConnectionFactoryImplTest.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/test/java/com/sun/gjc/spi/ConnectionHolderTest.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/test/java/com/sun/gjc/spi/DMManagedConnectionFactoryImplTest.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/test/java/com/sun/gjc/spi/DSManagedConnectionFactoryImplTest.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/test/java/com/sun/gjc/spi/ManagedConnectionImplTest.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/test/java/com/sun/gjc/spi/XAManagedConnectionFactoryImplTest.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/test/java/com/sun/gjc/spi/stub/MyConnection.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/test/java/com/sun/gjc/spi/stub/MyConnectionHolder.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/test/java/com/sun/gjc/spi/stub/MyConnectionPoolDatasource.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/test/java/com/sun/gjc/spi/stub/MyDataSource.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/test/java/com/sun/gjc/spi/stub/MyDriver.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/test/java/com/sun/gjc/spi/stub/MyPooledConnection.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/test/java/com/sun/gjc/spi/stub/MyXAConnection.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/test/java/com/sun/gjc/spi/stub/MyXADataSource.java
  appserver/tests/appserv-tests/connectors-ra-redeploy/jars/src/main/java/com/sun/jdbcra/spi/ManagedConnection.java
Labels: enhancement
