Repository eclipse-ee4j/glassfish, pull requests merged in 2024-06, with the labels that each got.

#24975 Removed jar files committed by mistake
  appserver/tests/appserv-tests/devtests/cdi/javaee-integration/cdi-servlet-3.0-annotation-with-web-inf-lib-extension-alternative/lib/bean-lib.jar
  appserver/tests/appserv-tests/devtests/cdi/javaee-integration/cdi-servlet-3.0-annotation-with-web-inf-lib-javaee-injection/lib/bean-lib.jar
  appserver/tests/appserv-tests/devtests/cdi/javaee-integration/cdi-servlet-3.0-annotation-with-web-inf-lib-ordering-reversed/lib/alpha.jar
  appserver/tests/appserv-tests/devtests/cdi/javaee-integration/cdi-servlet-3.0-annotation-with-web-inf-lib-ordering-reversed/lib/bravo.jar
  appserver/tests/appserv-tests/devtests/cdi/javaee-integration/cdi-servlet-3.0-annotation-with-web-inf-lib-ordering/lib/alpha.jar
  appserver/tests/appserv-tests/devtests/cdi/javaee-integration/cdi-servlet-3.0-annotation-with-web-inf-lib-ordering/lib/bravo.jar
  appserver/tests/appserv-tests/devtests/cdi/javaee-integration/cdi-servlet-3.0-annotation-with-web-inf-lib/lib/bean-lib.jar
  appserver/tests/appserv-tests/devtests/cdi/javaee-integration/embedded-resource-adapter-as-bean-archive/ra/generic-ra.jar
  appserver/tests/appserv-tests/devtests/cdi/javaee-integration/embedded-resource-adapter-as-bean-archive/ra/generic-ra.rar
  appserver/tests/appserv-tests/devtests/cdi/portable-extensions/new-bean-registration-extension-in-lib/lib/weld-extension.jar
Labels: build and test improvement

#24981 Continue to remove references to the security manager
  appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/managedbean/ManagedBeanManagerImpl.java
  appserver/common/container-common/src/main/java/com/sun/enterprise/container/common/impl/util/InjectionManagerImpl.java
  appserver/common/glassfish-naming/src/main/java/com/sun/enterprise/naming/GlassFishNamingBuilder.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/EJBUtils.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/BaseContainer.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/StatefulContainerFactory.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/StatefulSessionContainer.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/StatelessContainerFactory.java
  appserver/extras/embedded/common/bootstrap/src/main/java/org/glassfish/uberjar/activator/UberJarGlassFishActivator.java
  appserver/ha/ha-file-store/src/main/java/org/glassfish/ha/store/adapter/file/FileBackingStore.java
  appserver/orb/orb-iiop/src/main/java/org/glassfish/enterprise/iiop/impl/POARemoteReferenceFactory.java
  appserver/persistence/cmp/generator-database/src/main/java/com/sun/jdo/spi/persistence/generator/database/MappingPolicy.java
  appserver/persistence/common/src/main/java/org/glassfish/persistence/common/database/PropertyHelper.java
  appserver/persistence/entitybean-container/src/main/java/org/glassfish/persistence/ejb/entitybean/container/EntityContainer.java
  appserver/persistence/entitybean-container/src/main/java/org/glassfish/persistence/ejb/entitybean/container/distributed/DistributedReadOnlyBeanServiceImpl.java
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/authentication/jakarta/AuthMessagePolicy.java
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/authorization/cache/PermissionCache.java
  appserver/security/ejb.security/pom.xml
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/ConnectionExecutionContext.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/SecClientRequestInterceptor.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/SecServerRequestInterceptor.java
  appserver/security/ejb.security/src/main/java/com/sun/enterprise/iiop/security/SecurityContextUtil.java
  appserver/security/webintegration/src/main/java/com/sun/web/security/RealmAdapter.java
  appserver/security/webservices.security/src/main/java/com/sun/enterprise/security/webservices/SoapAuthenticationService.java
  nucleus/security/core/src/main/java/com/sun/enterprise/common/iiop/security/SecurityContext.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/LoginContext.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/SecurityContext.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/SecurityLoggerInfo.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/auth/login/LoginContextDriver.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/ssl/J2EEKeyManager.java
Labels: code cleaning

#24980 Fixed deadlock when rolling the file under a heavy load
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/GlassFishLogManager.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/handler/GlassFishLogHandler.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/handler/LogRecordBuffer.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/rotation/LogFileManager.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/tracing/GlassFishLoggingTracer.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/handler/GlassFishLogHandlerTest.java
Labels: bug

#24976 The catch is not required to stop GF instance
  appserver/itest-tools/src/main/java/org/glassfish/main/itest/tools/GlassFishTestEnvironment.java
Labels: code cleaning, build and test improvement

#24987 Webpage update for 7.0.15
  docs/pom.xml
  docs/website/src/main/resources/README.md
  docs/website/src/main/resources/download.md
  docs/website/src/main/resources/download_gf7.md
Labels: Documentation

#24946 Improve application-specific libraries loading
  appserver/admin/template/src/main/resources/config/domain.xml
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/applib/lib/LibraryResource.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/applib/webapp/LibraryApplication.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/applib/webapp/LibraryEndpoint.java
  appserver/tests/application/src/main/resources/org/glassfish/main/test/app/applib/v1/Version.properties
  appserver/tests/application/src/main/resources/org/glassfish/main/test/app/applib/v2/Version.properties
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/applib/ApplicationLibraryTest.java
  nucleus/admin/template/src/main/resources/config/domain.xml
  nucleus/admin/template/src/main/resources/lib/snapshots/.gitkeep_empty_dir
  nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ServerSynchronizer.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/io/FileUtils.java
  nucleus/common/internal-api/src/main/java/org/glassfish/internal/api/DelegatingClassLoader.java
  nucleus/core/extra-jre-packages/pom.xml
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/AppLibClassLoaderServiceImpl.java
  nucleus/deployment/common/src/main/java/org/glassfish/deployment/common/DeploymentContextImpl.java
Labels: bug, enhancement, code cleaning

#25004 Integrate jsch 0.2.18
  nucleus/parent/pom.xml
Labels: component upgrade

#25005 Integrate Nimbus 9.40
  appserver/pom.xml
Labels: component upgrade

#25012 Integrate JLine 3.26.2
  nucleus/parent/pom.xml
Labels: component upgrade

#25013 Integrate Helidon MicroProfile Config 3.2.8
  appserver/pom.xml
Labels: component upgrade

#25014 Integrate JUnit 5.10.3
  nucleus/parent/pom.xml
Labels: build and test improvement
