Repository eclipse-ee4j/glassfish, pull requests merged in 2024-09, with the labels that each got.

#25137 Remove unknown plugin parameter
  appserver/distributions/pom.xml
Labels: build and test improvement

#25138 Fixes the `get` and `set` asadmin commands
  nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/modularity/GetSetModularityHelper.java
Labels: bug

#25142 The XFS file system doesn't return size of the directory content
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/io/FileUtils.java
  nucleus/common/common-util/src/test/java/com/sun/enterprise/util/io/FileUtilsTest.java
Labels: build and test improvement

#25144 Fixed masking passwords in a map used for logging in admingui + added warning to documentation
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/RestUtil.java
  docs/administration-guide/src/main/asciidoc/logging.adoc
  docs/security-guide/src/main/asciidoc/running-in-secure-environment.adoc
Labels: bug, Documentation

#25148 Abandoned MD5 to SHA-256 used for caching command models
  nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/CachedCommandModel.java
Labels: deprecation

#25147 Fixed insecure XML processing - all XSDs and DTD have to be local
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/domain/DomainBuilder.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/stringsubs/impl/StringSubstitutionParser.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/template/TemplateInfoHolder.java
Labels: bug

#25146 Runnable Glassfish Embedded
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/nucleus/pom.xml
  appserver/extras/embedded/shell/glassfish-embedded-static-shell/pom.xml
  appserver/extras/embedded/web/pom.xml
  docs/embedded-server-guide/src/main/asciidoc/embedded-server-guide.adoc
  nucleus/common/common-util/src/main/java/org/glassfish/common/util/admin/GlassFishErrorServiceImpl.java
  nucleus/common/simple-glassfish-api/src/main/java/org/glassfish/embeddable/GlassFishProperties.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/GlassFishImpl.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/UberMain.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/embedded/EmbeddedGlassFishRuntimeBuilder.java
  nucleus/core/kernel/src/main/java/org/glassfish/runnablejar/InfoPrinter.java
  nucleus/core/kernel/src/main/java/org/glassfish/runnablejar/UberMain.java
  nucleus/core/kernel/src/main/java/org/glassfish/runnablejar/commandline/Arguments.java
  nucleus/core/kernel/src/main/java/org/glassfish/runnablejar/commandline/CommandLineParser.java
  nucleus/core/kernel/src/main/java/org/glassfish/runnablejar/commandline/Option.java
  nucleus/core/kernel/src/main/java/org/glassfish/runnablejar/commandline/UnknownPropertyException.java
  nucleus/core/kernel/src/main/java/org/glassfish/runnablejar/commandline/WordWrapCollector.java
  nucleus/core/kernel/src/main/manpages/org/glassfish/runnablejar/glassfish-embedded.1
  nucleus/core/kernel/src/test/java/org/glassfish/runnablejar/UberMainTest.java
  nucleus/core/kernel/src/test/java/org/glassfish/runnablejar/commandline/WordWrapperTest.java
  nucleus/hk2-config-generator/src/main/java/org/jvnet/hk2/config/ConfigParser.java
Labels: New feature

#25151 Fix exception if GF Embedded config file is set without schema
  appserver/tests/embedded/basic/config/README.md
  appserver/tests/embedded/basic/config/pom.xml
  appserver/tests/embedded/basic/config/src/test/java/org/glassfish/tests/embedded/basic/config/ConfigTest.java
  appserver/tests/embedded/basic/config/src/test/resources/domain.xml
  appserver/tests/embedded/basic/pom.xml
  appserver/tests/embedded/pom.xml
  nucleus/admin/config-api/src/main/java/org/glassfish/config/support/DomainXml.java
  nucleus/common/simple-glassfish-api/src/main/java/org/glassfish/embeddable/GlassFishProperties.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/embedded/EmbeddedGlassFishRuntime.java
  nucleus/core/kernel/src/main/java/org/glassfish/kernel/embedded/EmbeddedDomainXml.java
Labels: bug

#25158 issues/25156 show port number/range in failure message
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/domain/CustomTokenClient.java
Labels: enhancement

#25160 Fallback to basic file attributes if sun.nio.fs cannot be used
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/AppLibClassLoaderServiceImpl.java
Labels: bug

#25155 Part 1,2,3,4 for issue #24900 Document and rename some ResourceHandle fields.
  appserver/connectors/connectors-inbound-runtime/src/main/java/com/sun/enterprise/connectors/inbound/BasicResourceAllocator.java
  appserver/connectors/connectors-inbound-runtime/src/main/java/com/sun/enterprise/connectors/inbound/ConnectorMessageBeanClient.java
  appserver/connectors/connectors-internal-api/src/main/java/com/sun/appserv/connectors/internal/api/ResourceHandle.java
  appserver/connectors/connectors-internal-api/src/main/java/com/sun/appserv/connectors/internal/api/TransactedPoolManager.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/ConnectorConnectionPool.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/ConnectorRuntime.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/util/ConnectionPoolReconfigHelper.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/AssocWithThreadResourceHandle.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/ConnectorXAResource.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/ResourceHandle.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/ResourceSpec.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/ResourceState.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/allocator/AbstractConnectorAllocator.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/allocator/ConnectorAllocator.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/allocator/LocalTxConnectorAllocator.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/allocator/NoTxConnectorAllocator.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/allocator/ResourceAllocator.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/listener/LocalTxConnectionEventListener.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/AbstractPoolManager.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/AssocWithThreadResourcePool.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/ConnectionPool.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/PoolManager.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/PoolManagerImpl.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/PoolStatus.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/PoolTxHelper.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/ResourcePool.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/UnpooledResource.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/datastructure/DataStructure.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/datastructure/DataStructureFactory.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/datastructure/ListDataStructure.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/datastructure/RWLockDataStructure.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/resizer/AssocWithThreadPoolResizer.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/resizer/Resizer.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/rm/LazyEnlistableResourceManagerImpl.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/rm/ResourceManager.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/rm/ResourceManagerImpl.java
  appserver/connectors/connectors-runtime/src/test/java/com/sun/enterprise/resource/listener/LocalTxConnectionEventListenerTest.java
  appserver/connectors/connectors-runtime/src/test/java/com/sun/enterprise/resource/pool/ConnectionPoolTest.java
  appserver/connectors/connectors-runtime/src/test/java/com/sun/enterprise/resource/pool/InjectionUtil.java
  appserver/connectors/connectors-runtime/src/test/java/com/sun/enterprise/resource/pool/PoolManagerImplTest.java
  appserver/connectors/connectors-runtime/src/test/java/com/sun/enterprise/resource/pool/datastructure/RWLockDataStructureTest.java
  appserver/connectors/connectors-runtime/src/test/java/com/sun/enterprise/resource/pool/mock/JavaEETransactionManagerMock.java
  appserver/connectors/connectors-runtime/src/test/java/com/sun/enterprise/resource/pool/mock/JavaEETransactionMock.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBContainerTransactionManager.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/ManagedConnectionImpl.java
  appserver/jdbc/jdbc-ra/jdbc-core/src/main/java/com/sun/gjc/spi/base/ConnectionHolder.java
  appserver/transaction/internal-api/src/main/java/com/sun/enterprise/transaction/api/JavaEETransaction.java
  appserver/transaction/internal-api/src/main/java/com/sun/enterprise/transaction/api/JavaEETransactionManager.java
  appserver/transaction/internal-api/src/main/java/com/sun/enterprise/transaction/spi/TransactionalResource.java
  appserver/transaction/jta/src/main/java/com/sun/enterprise/transaction/JavaEETransactionImpl.java
  appserver/transaction/jta/src/main/java/com/sun/enterprise/transaction/JavaEETransactionManagerSimplified.java
  appserver/transaction/jts/src/main/java/com/sun/enterprise/transaction/jts/JavaEETransactionManagerJTSDelegate.java
  appserver/transaction/jts/src/test/java/com/sun/enterprise/transaction/jts/JavaEETransactionManagerTest.java
Labels: code cleaning

#25153 Dynamically update classloader after adding a library with the add-library command
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/connpool/SQLTraceListenerTest.java
  nucleus/common/common-util/src/main/java/org/glassfish/common/util/GlassfishUrlClassLoader.java
  nucleus/core/kernel/pom.xml
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/CommonClassLoaderServiceImpl.java
  nucleus/core/kernel/src/test/assembly/assembly-commonClassLoader.xml
  nucleus/core/kernel/src/test/java/com/sun/enterprise/v3/server/CommonClassLoaderServiceImplTest.java
  nucleus/core/kernel/src/test/java/com/sun/enterprise/v3/server/CommonClassLoaderServiceImplTestAdditionalClass.java
  nucleus/core/kernel/src/test/java/com/sun/enterprise/v3/server/CommonClassLoaderServiceImplTestDomainClass.java
  nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/AddLibraryCommand.java
Labels: New feature
