Repository eclipse-ee4j/glassfish, pull requests merged in 2025-07, with the labels that each got.

#25585 Fix #25584 The message which is "resource not found" is outputed when sending a javamail
  appserver/resources/mail/mail-connector/src/main/resources/META-INF/javamail.default.address.map
Labels: bug

#25589 Fix #25588 RemoveCount is not incremented when @Remove-annotated method is called
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/StatefulSessionContainer.java
Labels: bug

#25606 Added info for Jakarta 10 and 11 on the compatibility web page
  docs/website/src/main/resources/compatibility.md
Labels: Documentation

#25621 Drop unused method parameter
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/deployer/AdminObjectResourceDeployer.java
Labels: code cleaning

#25619 Fixes `WebappClassLoader` race condition on `definePackage`
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
Labels: bug, race condition

#25620 Do not produce result as it's not used anyway
  appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/embedded/EJBContainerProviderImpl.java
Labels: code cleaning

#25627 Minimal JDK version updated from 11 to 17
  README.md
  appserver/admin/template/src/main/resources/config/default-web.xml
  appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/AppClientContainerHolder.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/StaticRmiStubGenerator.java
  appserver/microprofile/config/pom.xml
  appserver/tests/appserv-tests/devtests/cdi/javaee-integration/cdi-servlet-3.0-annotation-with-web-inf-lib-extension-alternative/build.xml
  appserver/tests/appserv-tests/devtests/cdi/javaee-integration/cdi-servlet-3.0-annotation-with-web-inf-lib-javaee-injection/build.xml
  appserver/tests/appserv-tests/devtests/cdi/javaee-integration/cdi-servlet-3.0-annotation-with-web-inf-lib-ordering-reversed/build.xml
  appserver/tests/appserv-tests/devtests/cdi/javaee-integration/cdi-servlet-3.0-annotation-with-web-inf-lib-ordering/build.xml
  appserver/tests/appserv-tests/devtests/cdi/javaee-integration/cdi-servlet-3.0-annotation-with-web-inf-lib/build.xml
  appserver/tests/appserv-tests/devtests/ejb/ee/cluster-tests/asynctest/pom.xml
  appserver/tests/appserv-tests/devtests/ejb/ee/cluster-tests/ha-web/pom.xml
  appserver/tests/appserv-tests/devtests/ejb/ee/cluster-tests/instance-restart-test/pom.xml
  appserver/tests/appserv-tests/devtests/ejb/ee/cluster-tests/method-checkpoint/pom.xml
  appserver/tests/appserv-tests/devtests/ejb/ee/cluster-tests/multi-restart/pom.xml
  appserver/tests/appserv-tests/devtests/ejb/ee/cluster-tests/simple-failover/pom.xml
  appserver/tests/appserv-tests/devtests/jdbc/config/ee-common.xml
  appserver/tests/appserv-tests/devtests/security/ejb-auth-async/scheduler-service/pom.xml
  appserver/tests/appserv-tests/devtests/web/ha/cluster-tests/ha-web/pom.xml
  appserver/tests/appserv-tests/devtests/web/ha/cluster-tests/simple-failover-modified-attribute/pom.xml
  appserver/tests/appserv-tests/devtests/web/ha/cluster-tests/simple-failover-modified-session/pom.xml
  appserver/tests/appserv-tests/devtests/web/ha/cluster-tests/simple-failover/pom.xml
  appserver/tests/appserv-tests/devtests/web/jspResourceInjectionTagHandler/build-ng.xml
  appserver/tests/appserv-tests/devtests/web/sessionIdUrlRewrite/build-ng.xml
  appserver/tests/appserv-tests/devtests/web/tagPluginForEach/build-ng.xml
  appserver/tests/appserv-tests/report-builder/src/main/java/com/sun/appserv/test/util/results/HtmlReportProducer.java
  appserver/tests/appserv-tests/reporter/src/main/java/com/sun/ejte/ccl/reporter/Reporter.java
  appserver/tests/quicklook/amx/pom.xml
  appserver/tests/quicklook/gfproject/build-impl.xml
  appserver/tests/tck/jsonp/pom.xml
  appserver/tests/tck/microprofile/jwt/pom.xml
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
  docs/installation-guide/src/main/asciidoc/installing.adoc
  docs/performance-tuning-guide/src/main/asciidoc/tuning-java.adoc
  docs/reference-manual/src/main/asciidoc/generate-jvm-report.adoc
  docs/reference-manual/src/main/asciidoc/package-appclient.adoc
  docs/release-notes/src/main/asciidoc/release-notes.adoc
  docs/troubleshooting-guide/src/main/asciidoc/overview.adoc
  docs/troubleshooting-guide/src/main/asciidoc/specific-issues.adoc
  nucleus/admin/cli/pom.xml
  nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/AdminMain.java
  nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/VersionCommand.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/ASURLClassLoader.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/GlassFishMain.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/VersionCommand.java
  nucleus/distributions/nucleus-common/src/main/resources/config/osgi.properties
  nucleus/osgi-platforms/felix/src/main/resources/config/osgi.properties
  nucleus/parent/pom.xml
Labels: breaking change, jdk17

#25631 Raise the generated bytecode level to JDK 17
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/AsmSerializableBeanGenerator.java
  appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/EjbOptionalIntfGenerator.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/composite/CompositeUtil.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/generator/ASMClassWriter.java
  nucleus/flashlight/framework/src/main/java/org/glassfish/flashlight/impl/client/BtraceClientGenerator.java
  nucleus/flashlight/framework/src/main/java/org/glassfish/flashlight/impl/core/ProviderImplGenerator.java
Labels: jdk17

#25632 Remove unused method
  nucleus/common/amx-core/src/main/java/org/glassfish/admin/amx/impl/mbean/MBeanImplBase.java
Labels: code cleaning

#25633 Remove unused duplicate class AppserverServiceType
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/AppserverServiceType.java
Labels: code cleaning
