Repository eclipse-ee4j/glassfish, pull requests merged in 2025-03, with the labels that each got.

#25407 Fixed heavy need of garbage collector in GlassFishLogHandlerTest
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/handler/GlassFishLogHandlerTest.java
Labels: build and test improvement

#25409 Integrate JLine 3.29
  nucleus/parent/pom.xml
Labels: component upgrade

#25410 Integrate Jsch 0.2.24
  nucleus/parent/pom.xml
Labels: component upgrade

#25412 Integrate JNA 5.17
  appserver/libpam4j/pom.xml
Labels: component upgrade

#25414 Integrate Mojarra 4.0.11
  appserver/pom.xml
Labels: component upgrade, ee10-component

#25413 Integrate Weld 5.1.5
  appserver/pom.xml
Labels: component upgrade, ee10-component

#25416 Update plugins for building and testing
  appserver/tests/appserv-tests/lib/pom.xml
  appserver/tests/pom.xml
  docs/parent/pom.xml
  docs/security-guide/src/main/asciidoc/running-in-secure-environment.adoc
  nucleus/parent/pom.xml
  pom.xml
  qa/pom.xml
Labels: build and test improvement

#25417 Drop unused maven-invoker-plugin
  nucleus/parent/pom.xml
Labels: build and test improvement

#25364 Using CORBA+ORB+PFL to be compatible with JDK11 - 23
  appserver/connectors/connectors-runtime/pom.xml
  appserver/connectors/work-management/pom.xml
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/nucleus/pom.xml
  appserver/extras/embedded/shell/glassfish-embedded-static-shell/pom.xml
  appserver/extras/embedded/web/pom.xml
  appserver/jdbc/jdbc-ra/jdbc-core/pom.xml
  appserver/orb/orb-connector/pom.xml
  appserver/security/core-ee/pom.xml
  appserver/security/webintegration/pom.xml
  appserver/transaction/jta/pom.xml
  appserver/web/admin/pom.xml
  nucleus/admin/monitor/pom.xml
  nucleus/core/kernel/pom.xml
  nucleus/deployment/common/pom.xml
  nucleus/featuresets/atomic/pom.xml
  nucleus/grizzly/nucleus-grizzly-all/pom.xml
  nucleus/parent/pom.xml
  nucleus/security/core/pom.xml
Labels: component upgrade

#25423 Integrate Jboss Logging Annotations 3.0.4
  nucleus/parent/pom.xml
Labels: component upgrade

#25419 integrate hibernate validation 8.0.2
  nucleus/parent/pom.xml
Labels: component upgrade, ee10-component

#25428 Updated website after 7.0.23 release
  RELEASE.md
  docs/pom.xml
  docs/website/src/main/resources/README.md
  docs/website/src/main/resources/download.md
  docs/website/src/main/resources/download_gf7.md
Labels: Documentation

#25398 Issue #25397 use java.nio Files.walkFileTree instead of recursively finding files.
  nucleus/deployment/admin/src/main/java/org/glassfish/deployment/admin/DeployCommand.java
  nucleus/deployment/common/src/main/java/com/sun/enterprise/deploy/shared/FileArchive.java
Labels: enhancement
