Repository eclipse-ee4j/glassfish, pull requests merged in 2025-05, with the labels that each got.

#25468 Improved Derby and CommonClassLoaderService initialization
  appserver/admin/cli-optional/src/main/java/com/sun/enterprise/admin/cli/optional/DatabaseCommand.java
  appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/ACCStartupContext.java
  appserver/connectors/connectors-internal-api/src/main/java/com/sun/appserv/connectors/internal/api/ConnectorConstants.java
  appserver/connectors/connectors-internal-api/src/main/java/com/sun/appserv/connectors/internal/api/ConnectorsClassLoaderUtil.java
  appserver/connectors/connectors-internal-api/src/main/java/com/sun/appserv/connectors/internal/api/ConnectorsUtil.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/util/DriverLoader.java
  appserver/jdbc/admin/src/main/java/org/glassfish/jdbc/admin/cli/internal/GetDatabaseVendorNames.java
  appserver/jdbc/jdbc-runtime/src/main/java/org/glassfish/jdbcruntime/service/JdbcAdminServiceImpl.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/util/SystemPropertyConstants.java
  nucleus/common/common-util/src/main/java/org/glassfish/server/ServerEnvironmentImpl.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/cfg/BootstrapKeys.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/CommonClassLoaderServiceImpl.java
  nucleus/core/kernel/src/test/java/com/sun/enterprise/v3/admin/CommandRunnerImplServiceTest.java
  nucleus/core/kernel/src/test/java/com/sun/enterprise/v3/admin/CreateProfilerTest.java
  nucleus/core/kernel/src/test/java/com/sun/enterprise/v3/server/AppServerStartupTest.java
  nucleus/core/kernel/src/test/java/org/glassfish/main/core/kernel/test/KernelJUnitExtension.java
  nucleus/test-utils/src/main/java/org/glassfish/tests/utils/junit/HK2JUnit5Extension.java
  nucleus/test-utils/src/main/java/org/glassfish/tests/utils/mock/TestServerEnvironment.java
Labels: enhancement, code cleaning

#25483 Testing 8.0 branch + reenabled tests
  .github/workflows/build-linux.yml
  .github/workflows/build-macos.yml
  .github/workflows/build-windows.yml
  nucleus/core/kernel/src/test/java/com/sun/enterprise/v3/server/CommonClassLoaderServiceImplTest.java
Labels: build and test improvement

#25477 Fix 25444 Fix possible nullpointer. Fix avoid begin() new transaction call in case of rollback.
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/ConnectorXAResource.java
  appserver/connectors/connectors-runtime/src/test/java/com/sun/enterprise/resource/ConnectorXAResourceTest.java
  appserver/connectors/connectors-runtime/src/test/java/com/sun/enterprise/resource/pool/mock/LocalTransactionMock.java
  appserver/connectors/connectors-runtime/src/test/java/com/sun/enterprise/resource/pool/mock/ManagedConnectionFactoryMock.java
  appserver/connectors/connectors-runtime/src/test/java/com/sun/enterprise/resource/pool/mock/ManagedConnectionMock.java
  appserver/connectors/connectors-runtime/src/test/java/com/sun/enterprise/resource/pool/mock/TransactionalResourceMock.java
Labels: bug

#25479 Improvements in GJULE
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/handler/LogRecordBuffer.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/handler/LoggingOutputStream.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/rotation/LogFileManager.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/tracing/GlassFishLoggingTracer.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/handler/GlassFishLogHandlerTest.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/handler/LoggingPrintStreamTest.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/rotation/LogFileManagerTest.java
Labels: bug

#25488 Fixed log messages - throwable is not a parameter
  nucleus/admin/util/src/main/java/com/sun/enterprise/admin/remote/RemoteRestAdminCommand.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/handler/GlassFishLogHandlerTest.java
Labels: bug

#25490 Classloaders parallelCapable and named
  appserver/appclient/client/acc-standalone/src/main/java/org/glassfish/appclient/client/acc/agent/ACCAgentClassLoader.java
  appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/AppClientFacade.java
  appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/ACCClassLoader.java
  appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/JWSACCClassLoader.java
  appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/ProviderContainerContractInfoImpl.java
  appserver/appclient/server/core/src/main/java/org/glassfish/appclient/server/core/AppClientServerApplication.java
  appserver/appclient/server/core/src/main/java/org/glassfish/appclient/server/core/CarHandler.java
  appserver/connectors/connectors-internal-api/src/main/java/com/sun/appserv/connectors/internal/api/ConnectorClassFinder.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/util/ConnectorClassLoader.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/util/ConnectorRARClassLoader.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/util/DriverLoader.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/util/RARUtils.java
  appserver/deployment/jakartaee-full/src/main/java/org/glassfish/javaee/full/deployment/EarClassLoader.java
  appserver/deployment/jakartaee-full/src/main/java/org/glassfish/javaee/full/deployment/EarLibClassLoader.java
  appserver/ejb/ejb-container/src/main/java/org/glassfish/ejb/deployment/EjbJarHandler.java
  appserver/extras/embedded/common/bootstrap/src/main/java/org/glassfish/uberjar/bootstrap/UberJarOSGiGlassFishRuntimeBuilder.java
  appserver/tests/appserv-tests/devtests/connector/v3/administered-object-definition/ut/ArchiveTest.java
  appserver/tests/appserv-tests/devtests/connector/v3/connection-factory-definition/ut/ArchiveTest.java
  appserver/tests/appserv-tests/devtests/connector/v3/jms-destination-definition/ut/ArchiveTest.java
  appserver/tests/appserv-tests/devtests/jdbc/flushconnectionpool/ejb/SimpleBMPBean.java
  appserver/tests/quicklook/ejb/remoteview/src/test/RemoteViewTestNG.java
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/ServletContainerInitializerUtil.java
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
  appserver/web/war-util/src/test/java/org/glassfish/web/loader/WebappClassLoaderTest.java
  appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModule.java
  appserver/web/weld-integration/src/main/java/org/glassfish/weld/BeanDeploymentArchiveImpl.java
  appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/WebServicesDeployer.java
  appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/monitoring/WebServiceTesterServlet.java
  nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/CLIContainer.java
  nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/DirectoryClassLoader.java
  nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/modularity/customization/CustomizationTokensProvider.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/VerifyDomainXmlCommand.java
  nucleus/common/common-util/src/main/java/com/sun/enterprise/loader/ASURLClassLoader.java
  nucleus/common/common-util/src/main/java/org/glassfish/common/util/GlassfishUrlClassLoader.java
  nucleus/common/common-util/src/test/java/org/glassfish/common/util/GlassfishUrlClassLoaderTest.java
  nucleus/common/internal-api/src/main/java/org/glassfish/internal/api/DelegatingClassLoader.java
  nucleus/common/simple-glassfish-api/src/main/java/org/glassfish/embeddable/GlassFishRuntime.java
  nucleus/common/simple-glassfish-api/src/main/java/org/glassfish/embeddable/spi/RuntimeBuilder.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/cp/ClassPathBuilder.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/embedded/EmbeddedGlassFishRuntimeBuilder.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/osgi/EmbeddedOSGiGlassFishRuntimeBuilder.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/osgi/OSGiFrameworkLauncher.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/osgi/OSGiGlassFishRuntimeBuilder.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/AppLibClassLoaderServiceImpl.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/CommonClassLoaderServiceImpl.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ServerLifecycleModule.java
  nucleus/core/logging/src/main/java/com/sun/enterprise/server/logging/LoggerInfoMetadataService.java
Labels: enhancement

#25497 Fixed checking of free ports on create-domain with --checkports=false
  .github/workflows/build-linux.yml
  nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/modularity/customization/ConfigCustomizationToken.java
  nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/modularity/customization/FileTypeDetails.java
  nucleus/admin/config-api/src/main/java/com/sun/enterprise/config/modularity/customization/PortTypeDetails.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/CreateDomainCommand.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/domain/CustomTokenClient.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/domain/DomainBuilder.java
Labels: bug

#25496 TemplateInfoHolder - do not hide the cause of the problem!
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/template/TemplateInfoHolder.java
Labels: bug

#25498 Improved stopping local servers
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/LocalServerCommand.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/RestartDomainCommand.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/StopDomainCommand.java
  nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/RestartLocalInstanceCommand.java
  nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/StopLocalInstanceCommand.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/StartServerHook.java
Labels: bug

#25507 SshClusterITest - added --interactive=false
  appserver/tests/admin/ssh-cluster/src/test/java/org/glassfish/main/test/clusterssh/SshClusterITest.java
Labels: build and test improvement

#25502 Add instructions in README on how to find the built artifacts
  README.md
Labels: Documentation

#25515 Updated documentation of the known issue with Windows signals
  docs/administration-guide/src/main/asciidoc/domains.adoc
Labels: Documentation
