Repository eclipse-ee4j/glassfish, pull requests merged in 2025-04, with the labels that each got.

#25436 Revisited scripts around asenv
  appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/CLIBootstrap.java
  appserver/appclient/client/acc/src/test/java/org/glassfish/appclient/client/CLIBootstrapTest.java
  appserver/appclient/client/appclient-scripts/src/main/resources/glassfish/bin/appclient
  appserver/appclient/client/appclient-scripts/src/main/resources/glassfish/bin/appclient.bat
  appserver/appclient/client/appclient-scripts/src/main/resources/glassfish/bin/appclient.js
  appserver/appclient/client/appclient-scripts/src/main/resources/glassfish/bin/package-appclient
  appserver/appclient/client/appclient-scripts/src/main/resources/glassfish/bin/package-appclient.bat
  appserver/distributions/glassfish-common/src/main/resources/bin/asadmin
  appserver/distributions/glassfish-common/src/main/resources/bin/asadmin.bat
  appserver/distributions/glassfish-common/src/main/resources/bin/debug-asadmin
  appserver/distributions/glassfish-common/src/main/resources/bin/debug-asadmin.bat
  appserver/distributions/glassfish-common/src/main/resources/bin/startserv
  appserver/distributions/glassfish-common/src/main/resources/bin/startserv.bat
  appserver/distributions/glassfish-common/src/main/resources/bin/stopserv
  appserver/distributions/glassfish-common/src/main/resources/bin/stopserv.bat
  appserver/distributions/glassfish-common/src/main/resources/glassfish/bin/asadmin
  appserver/distributions/glassfish-common/src/main/resources/glassfish/bin/asadmin.bat
  appserver/itest-tools/src/main/java/org/glassfish/main/itest/tools/GlassFishTestEnvironment.java
  appserver/itest-tools/src/main/java/org/glassfish/main/itest/tools/asadmin/Asadmin.java
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/PathWithSpacesITest.java
  appserver/tests/appserv-tests/config/jws-appclient
  appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/schemagen
  appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/schemagen.bat
  appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsgen
  appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsgen.bat
  appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsimport
  appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsimport.bat
  appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/xjc
  appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/xjc.bat
  nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/CommandLine.java
  nucleus/admin/launcher/src/main/java/com/sun/enterprise/admin/launcher/GFLauncher.java
  nucleus/admin/launcher/src/test/java/com/sun/enterprise/admin/launcher/GFLauncherTest.java
  nucleus/distributions/nucleus-common/src/main/resources/bin/jspc
  nucleus/distributions/nucleus-common/src/main/resources/bin/jspc.bat
  nucleus/distributions/nucleus-common/src/main/resources/bin/nadmin
  nucleus/distributions/nucleus-common/src/main/resources/bin/nadmin.bat
  nucleus/distributions/nucleus-common/src/main/resources/bin/startserv
  nucleus/distributions/nucleus-common/src/main/resources/bin/startserv.bat
  nucleus/distributions/nucleus-common/src/main/resources/bin/stopserv
  nucleus/distributions/nucleus-common/src/main/resources/bin/stopserv.bat
  nucleus/distributions/nucleus-common/src/main/resources/config/asenv.bat
  nucleus/distributions/nucleus-common/src/main/resources/config/asenv.conf
  nucleus/distributions/nucleus-common/src/main/resources/config/config.bat
  nucleus/distributions/nucleus-common/src/main/resources/config/config.sh
Labels: bug

#25449 More robust pid file read
  nucleus/common/common-util/src/main/java/com/sun/enterprise/universal/process/ProcessUtils.java
Labels: bug

#25452 Property management used just by embedded pushed down
  nucleus/common/simple-glassfish-api/src/main/java/org/glassfish/embeddable/GlassFishProperties.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/GlassFishImpl.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/embedded/AutoDisposableGlassFish.java
  nucleus/core/bootstrap/src/main/java/com/sun/enterprise/glassfish/bootstrap/osgi/EmbeddedOSGiGlassFishRuntime.java
Labels: bug

#25451 More robust nadmin/asadmin execution in build
  appserver/distributions/pom.xml
  nucleus/distributions/pom.xml
Labels: build and test improvement

#25450 BAT file and startlocal vs endlocal, windows path separator
  appserver/appclient/client/appclient-scripts/src/main/resources/glassfish/bin/appclient.bat
  appserver/distributions/glassfish-common/src/main/resources/bin/asadmin.bat
  appserver/distributions/glassfish-common/src/main/resources/bin/debug-asadmin.bat
  appserver/distributions/glassfish-common/src/main/resources/bin/startserv.bat
  appserver/distributions/glassfish-common/src/main/resources/bin/stopserv.bat
  appserver/distributions/glassfish-common/src/main/resources/glassfish/bin/asadmin.bat
  nucleus/distributions/nucleus-common/src/main/resources/bin/jspc.bat
  nucleus/distributions/nucleus-common/src/main/resources/bin/nadmin.bat
  nucleus/distributions/nucleus-common/src/main/resources/bin/startserv.bat
  nucleus/distributions/nucleus-common/src/main/resources/bin/stopserv.bat
  nucleus/distributions/nucleus-common/src/main/resources/config/asenv.bat
  nucleus/distributions/nucleus-common/src/main/resources/config/config.bat
Labels: bug

#25453 Added build on MacOS and ARM + fixed scripts
  .github/workflows/build-macos.yml
  appserver/appclient/client/appclient-scripts/src/main/resources/glassfish/bin/appclient
  appserver/appclient/client/appclient-scripts/src/main/resources/glassfish/bin/package-appclient
  appserver/distributions/glassfish-common/src/main/resources/bin/asadmin
  appserver/distributions/glassfish-common/src/main/resources/bin/debug-asadmin
  appserver/distributions/glassfish-common/src/main/resources/bin/startserv
  appserver/distributions/glassfish-common/src/main/resources/bin/stopserv
  appserver/distributions/glassfish-common/src/main/resources/glassfish/bin/asadmin
  appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/schemagen
  appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsgen
  appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/wsimport
  appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/xjc
  nucleus/distributions/nucleus-common/src/main/resources/bin/jspc
  nucleus/distributions/nucleus-common/src/main/resources/bin/nadmin
  nucleus/distributions/nucleus-common/src/main/resources/bin/startserv
  nucleus/distributions/nucleus-common/src/main/resources/bin/stopserv
  nucleus/distributions/nucleus-common/src/main/resources/config/config.sh
Labels: bug

#25455 GitHub Actions - Using Windows 2025 instead of 2022
  .github/workflows/build-windows.yml
Labels: build and test improvement

#25458 Jdk24 fixes
  appserver/admin/template/src/main/resources/config/domain.xml
  appserver/security/webservices.security/src/main/java/com/sun/enterprise/security/webservices/SoapAuthenticationService.java
  appserver/tests/quicklook/gfproject/db-targets.xml
  gftest.sh
  nucleus/admin/template/src/main/resources/config/domain.xml
  runtests.sh
Labels: enhancement

#25459 Stabilized tests around logging
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/rest/LoggingRestITest.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/handler/LoggingOutputStream.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/GlassFishLogManagerLifeCycleTest.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/handler/LoggingPrintStreamTest.java
Labels: build and test improvement

#25460 Fixed SMGlobalPolicyUtil's conversion of file to url
  appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/perms/SMGlobalPolicyUtil.java
Labels: bug

#25464 Fix View JMS Physical Destination Statistics
  appserver/admingui/jms-plugin/src/main/java/org/glassfish/admingui/plugin/jms/JmsHandlers.java
Labels: bug

#25473 Migrate away from deprecated DerbyDB classes to replacements
  appserver/jdbc/templates/src/main/resources/glassfish/lib/install/databases/dbvendormapping/cpds.properties
  appserver/jdbc/templates/src/main/resources/glassfish/lib/install/databases/dbvendormapping/ds.properties
  appserver/jdbc/templates/src/main/resources/glassfish/lib/install/databases/dbvendormapping/xads.properties
  appserver/jdbc/templates/src/main/resources/glassfish/lib/install/templates/resources/jdbc/javadb_type4_datasource.xml
  appserver/tests/appserv-tests/connectors-ra-redeploy/rars-xa/src/main/rar/META-INF/ra.xml
  appserver/tests/appserv-tests/connectors-ra-redeploy/rars/src/main/rar/META-INF/ra.xml
  appserver/tests/appserv-tests/devtests/connector/txlevelswitch/ra/src/com/sun/jdbcra/spi/1.4/ra-xa.xml
  appserver/tests/appserv-tests/devtests/connector/v3/embeddedweb-resources-xml/ra/src/com/sun/jdbcra/spi/1.4/ra-ds.xml
  appserver/tests/appserv-tests/devtests/connector/v3/nonstringmcfproperties/ra/src/com/sun/jdbcra/spi/1.4/ra-ds.xml
  appserver/tests/appserv-tests/devtests/connector/v3/osgi-resources-test/src/main/java/org/glassfish/osgi_resources_test/ResourcesTestActivator.java
  appserver/tests/appserv-tests/devtests/jdbc/datasource40/build.xml
  appserver/tests/appserv-tests/devtests/jdbc/v3/osgi-jdbc-test/src/main/java/org/glassfish/osgijdbc_test/JDBCActivator.java
  docs/administration-guide/src/main/asciidoc/jdbc.adoc
Labels: enhancement, Documentation

#25470 Fixed race condition in LoggingOutputStream
  appserver/tests/admin/ssh-cluster/src/test/java/org/glassfish/main/test/clusterssh/SshClusterITest.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/handler/LogCollectorHandler.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/handler/LoggingOutputStream.java
  nucleus/glassfish-jul-extension/src/main/java/org/glassfish/main/jul/handler/LoggingPrintStream.java
  nucleus/glassfish-jul-extension/src/test/java/org/glassfish/main/jul/handler/LoggingPrintStreamTest.java
Labels: bug
