Repository eclipse-ee4j/glassfish, pull requests merged in 2025-08, with the labels that each got.

#25654 Display GitHub workflow names in pull requests
  .github/workflows/build-docs.yml
  .github/workflows/build-linux.yml
  .github/workflows/build-macos.yml
  .github/workflows/build-windows.yml
  .github/workflows/stale-issues.yml
Labels: build and test improvement

#25662 Fix for Security TCK - default SSLContextProvider
  appserver/web/jersey-ejb-component-provider/src/main/java/org/glassfish/jersey/gf/ejb/internal/GlassFishSslContextProvider.java
  appserver/web/jersey-ejb-component-provider/src/main/resources/META-INF/services/org.glassfish.jersey.client.spi.DefaultSslContextProvider
  appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
Labels: enhancement

#25658 Remove Solaris service installer
  docs/reference-manual/src/main/asciidoc/create-service.adoc
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/LocalStrings.properties
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/services/Constants.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/services/LinuxService.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/services/LocalStrings.properties
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/services/NonSMFServiceAdapter.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/services/PlatformServicesInfo.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/services/SMFService.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/services/Service.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/services/ServiceAdapter.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/services/ServiceFactory.java
  nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/services/WindowsService.java
  nucleus/distributions/nucleus-common/src/main/resources/lib/install/templates/Domain-service-smf.xml.template
Labels: code cleaning

#25664 Remove all Distributed Component Object Model (DCOM) references
  appserver/tests/appserv-tests/devtests/admin/cli/src/admin/AdminBaseDevTest.java
  docs/administration-guide/src/main/asciidoc/asadmin-subcommands.adoc
  docs/ha-administration-guide/src/main/asciidoc/instances.adoc
  docs/ha-administration-guide/src/main/asciidoc/loe.adoc
  docs/ha-administration-guide/src/main/asciidoc/nodes.adoc
  docs/ha-administration-guide/src/main/asciidoc/overview.adoc
  docs/ha-administration-guide/src/main/asciidoc/ssh-setup.adoc
  docs/reference-manual/src/main/asciidoc/asadmin.adoc
  docs/reference-manual/src/main/asciidoc/create-instance.adoc
  docs/reference-manual/src/main/asciidoc/create-local-instance.adoc
  docs/reference-manual/src/main/asciidoc/create-node-config.adoc
  docs/reference-manual/src/main/asciidoc/create-node-dcom.adoc
  docs/reference-manual/src/main/asciidoc/create-node-ssh.adoc
  docs/reference-manual/src/main/asciidoc/delete-instance.adoc
  docs/reference-manual/src/main/asciidoc/delete-local-instance.adoc
  docs/reference-manual/src/main/asciidoc/delete-node-config.adoc
  docs/reference-manual/src/main/asciidoc/delete-node-dcom.adoc
  docs/reference-manual/src/main/asciidoc/delete-node-ssh.adoc
  docs/reference-manual/src/main/asciidoc/install-node-dcom.adoc
  docs/reference-manual/src/main/asciidoc/install-node-ssh.adoc
  docs/reference-manual/src/main/asciidoc/install-node.adoc
  docs/reference-manual/src/main/asciidoc/list-nodes-config.adoc
  docs/reference-manual/src/main/asciidoc/list-nodes-dcom.adoc
  docs/reference-manual/src/main/asciidoc/list-nodes-ssh.adoc
  docs/reference-manual/src/main/asciidoc/list-nodes.adoc
  docs/reference-manual/src/main/asciidoc/ping-connection-pool.adoc
  docs/reference-manual/src/main/asciidoc/ping-node-dcom.adoc
  docs/reference-manual/src/main/asciidoc/ping-node-ssh.adoc
  docs/reference-manual/src/main/asciidoc/set-log-levels.adoc
  docs/reference-manual/src/main/asciidoc/setup-local-dcom.adoc
  docs/reference-manual/src/main/asciidoc/setup-ssh.adoc
  docs/reference-manual/src/main/asciidoc/start-cluster.adoc
  docs/reference-manual/src/main/asciidoc/start-instance.adoc
  docs/reference-manual/src/main/asciidoc/start-local-instance.adoc
  docs/reference-manual/src/main/asciidoc/uninstall-node-dcom.adoc
  docs/reference-manual/src/main/asciidoc/uninstall-node-ssh.adoc
  docs/reference-manual/src/main/asciidoc/uninstall-node.adoc
  docs/reference-manual/src/main/asciidoc/update-node-config.adoc
  docs/reference-manual/src/main/asciidoc/update-node-dcom.adoc
  docs/reference-manual/src/main/asciidoc/update-node-ssh.adoc
  docs/reference-manual/src/main/asciidoc/uptime.adoc
  docs/reference-manual/src/main/asciidoc/validate-dcom.adoc
  docs/reference-manual/src/main/asciidoc/validate-multicast.adoc
  nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/LocalStrings.properties
  nucleus/cluster/ssh/src/main/java/org/glassfish/cluster/ssh/util/LocalStrings.properties
Labels: code cleaning, Documentation

#25665 Fixes `update-node-ssh` page links in documentation
  docs/reference-manual/src/main/asciidoc/asadmin.adoc
  docs/reference-manual/src/main/asciidoc/create-node-config.adoc
  docs/reference-manual/src/main/asciidoc/create-node-ssh.adoc
  docs/reference-manual/src/main/asciidoc/delete-node-config.adoc
  docs/reference-manual/src/main/asciidoc/delete-node-ssh.adoc
  docs/reference-manual/src/main/asciidoc/ping-node-ssh.adoc
  docs/reference-manual/src/main/asciidoc/update-node-config.adoc
  docs/reference-manual/src/main/asciidoc/update-password-alias.adoc
Labels: Documentation

#25669 Fixes processing of the detached admin commands
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/TemplateExecCommand.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/resources/admin/CommandResource.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/utils/DetachedSseAdminCommandInvoker.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/utils/SseEventOutput.java
Labels: bug

#25647 Upgrade JNoSQL to 1.1.10. Move OSGi bundle to GlassFish
  appserver/distributions/glassfish/pom.xml
  appserver/distributions/web/pom.xml
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/shell/glassfish-embedded-static-shell/pom.xml
  appserver/featuresets/glassfish/pom.xml
  appserver/featuresets/web/pom.xml
  appserver/persistence/cmp/support-ejb/pom.xml
  appserver/persistence/cmp/support-sqlstore/pom.xml
  appserver/persistence/jnosql-integration/pom.xml
  appserver/persistence/jnosql-integration/src/main/java/org/glassfish/main/jnosql/jakartapersistence/mapping/glassfishcontext/GlassFishClassScanner.java
  appserver/persistence/jnosql-integration/src/test/java/org/glassfish/main/jnosql/jakartapersistence/mapping/glassfishcontext/GlassFishClassScannerTest.java
  appserver/persistence/jnosql-jakarta-persistence-osgi-bundle/pom.xml
  appserver/persistence/jnosql-jakarta-persistence-osgi-bundle/src/assembly/sources.xml
  appserver/persistence/jnosql-jakarta-persistence-osgi-bundle/src/main/resources/META-INF/services/org.eclipse.jnosql.mapping.core.repository.RepositoryReturn
  appserver/persistence/pom.xml
  appserver/pom.xml
  nucleus/parent/pom.xml
  nucleus/pom.xml
Labels: component upgrade, 8.0

#25683 Update command security plugin to 1.0.20
  nucleus/parent/pom.xml
Labels: build and test improvement

#25684 Integrate Jersey 4.0.0-M3
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/shell/glassfish-embedded-static-shell/pom.xml
  appserver/extras/embedded/web/pom.xml
  appserver/featuresets/web/pom.xml
  appserver/tests/tck/connectors/src/test/resources/ts.jte
  appserver/tests/tck/enterprise-beans/src/test/resources/ts.jte
  nucleus/parent/pom.xml
Labels: component upgrade

#25687 Updated Arquillian GF Container - fixes OOME in CDI and Validation TCK
  appserver/tests/tck/pom.xml
Labels: bug, component upgrade
