Repository eclipse-ee4j/glassfish, pull requests merged in 2025-06, with the labels that each got.

#25525 Released 7.0.25 - updated docs and download links
  README.md
  docs/pom.xml
  docs/website/src/main/resources/README.md
  docs/website/src/main/resources/download.md
  docs/website/src/main/resources/download_gf7.md
Labels: Documentation

#25527 Issue 24900 Documentation improvements. Some ConnectionPool changes. Removal of selfmanaged option.
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/ActiveOutboundResourceAdapter.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/ConnectorConnectionPool.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/ConnectorDescriptorInfo.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/ConnectorRegistry.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/ConnectorRuntime.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/connectors/util/ConnectionPoolObjectsUtils.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/deployer/ConnectorConnectionPoolDeployer.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/AssocWithThreadResourcePool.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/ConnectionPool.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/PoolManager.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/PoolManagerImpl.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/ResourcePool.java
  appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/UnpooledResource.java
  docs/application-development-guide/src/main/asciidoc/jdbc.adoc
  docs/reference-manual/src/main/asciidoc/create-connector-connection-pool.adoc
  docs/reference-manual/src/main/asciidoc/create-jdbc-connection-pool.adoc
  nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingXMLNames.java
  nucleus/common/common-util/src/main/java/com/sun/logging/LogDomains.java
Labels: code cleaning

#25536 Jakarta EE 11 Platform TCK results for GlassFish 8 M12
  docs/website/src/main/resources/certifications/jakarta-platform/11/TCK-Results-8.0.0-M12.md
Labels: Documentation

#25542 Removed maven download from GitHub CI - 24.04 already contains that
  .github/workflows/build-linux.yml
Labels: ci-pipeline

#25556 DetachAttachITest - removed sleep
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/progress/DetachAttachITest.java
Labels: build and test improvement

#25557 Removed embedded-nucleus - nobody used it, we did not test it
  appserver/extras/embedded/nucleus/pom.xml
  appserver/extras/embedded/nucleus/src/assembly/package.xml
  appserver/extras/embedded/pom.xml
  docs/embedded-server-guide/src/main/asciidoc/embedded-server-guide.adoc
Labels: build and test improvement

#25561 Refactored SecureWebAppTest
  appserver/tests/embedded/maven-plugin/secureWebApp/pom.xml
  appserver/tests/embedded/maven-plugin/secureWebApp/src/test/java/org/glassfish/tests/embedded/securewebapp/SecureWebAppTest.java
  appserver/tests/embedded/maven-plugin/secureWebApp/src/test/resources/bootstrap.properties
  appserver/tests/embedded/maven-plugin/secureWebApp/src/test/resources/glassfish.properties
  appserver/tests/embedded/maven-plugin/secureWebApp/src/test/resources/system.properties
Labels: build and test improvement

#25559 Excluded module-info.class files poisoning embedded packages
  appserver/extras/embedded/all/pom.xml
  appserver/extras/embedded/all/src/assembly/package.xml
  appserver/extras/embedded/web/pom.xml
  appserver/extras/embedded/web/src/assembly/package.xml
Labels: bug

#25566 The java.security.auth.login.config system property must be an URL
  appserver/appclient/client/acc-standalone/src/main/java/org/glassfish/appclient/client/acc/agent/CLIBootstrap.java
  appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/AppClientContainerSecurityHelper.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/SecurityLifecycle.java
Labels: bug

#25577 Several smaller fixes and improvements
  appserver/ejb/ejb-container/src/test/java/com/sun/ejb/EjbClassGeneratorFactoryBenchmarkTest.java
  appserver/itest-tools/src/main/java/org/glassfish/main/itest/tools/asadmin/Asadmin.java
  appserver/itest-tools/src/main/java/org/glassfish/main/itest/tools/asadmin/DetachedTerseAsadminResult.java
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/AsadminLoggingITest.java
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/AsadminVersionITest.java
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/PathWithSpacesITest.java
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/progress/JobManagerITest.java
  appserver/tests/admin/tests/src/test/java/org/glassfish/main/admin/test/rest/LoggingRestITest.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/utils/DetachedCommandHelper.java
  nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/utils/SseCommandHelper.java
  nucleus/common/glassfish-api/src/main/java/org/glassfish/api/admin/AdminCommandEventBroker.java
  nucleus/common/internal-api/src/main/java/org/glassfish/internal/data/EngineRef.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/AdminCommandInstanceImpl.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/JobManagerService.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/RunnableAdminCommandListener.java
Labels: code cleaning, build and test improvement

#25579 Added keeping server.logs from tests on GH CI + synced files
  .github/workflows/build-linux.yml
  .github/workflows/build-macos.yml
  .github/workflows/build-windows.yml
Labels: build and test improvement

#25581 Fixes scattered web archive processing
  appserver/web/web-glue/src/main/java/org/glassfish/web/embed/impl/ScatteredWebArchivist.java
Labels: bug
