Repository eclipse-ee4j/glassfish, pull requests merged in 2025-02, with the labels that each got.

#25361 Bump OpenMQ version from 6.5.0 to 6.5.1
  appserver/pom.xml
Labels: component upgrade

#25356 Fix principal in Jakarta SecurityContext when using SSO
  appserver/itest-tools/src/main/java/org/glassfish/main/itest/tools/GlassFishTestEnvironment.java
  appserver/security/webintegration/src/main/java/com/sun/web/security/RealmAdapter.java
  appserver/tests/application/pom.xml
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/security/jakartasecurity/CustomPrincipal.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/security/jakartasecurity/CustomPrincipalServlet.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/security/jakartasecurity/SerializableCoreSecurityContextServlet.java
  appserver/tests/application/src/main/java/org/glassfish/main/test/app/security/jakartasecurity/TestAuthenticationMechanism.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/security/jakartasecurity/JakartaSecurityTest.java
  appserver/tests/application/src/test/java/org/glassfish/main/test/app/security/simplemultirolemapping/SimpleMultiRoleMappingTest.java
  nucleus/security/core/src/main/java/com/sun/enterprise/security/SecurityContext.java
Labels: bug

#25384 Backport of changes done in gf8 - Jenkinsfile and jdbc_all split
  Jenkinsfile
  appserver/tests/appserv-tests/devtests/jdbc/build.xml
  appserver/tests/appserv-tests/devtests/jdbc/run_test.sh
Labels: build and test improvement

#25388 Update minimum Java version in release-notes
  docs/release-notes/src/main/asciidoc/release-notes.adoc
Labels: Documentation

#25386 Fix: Properly unload failed app
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java
Labels: bug
