Repository eclipse-ee4j/glassfish, pull requests merged in 2025-09, with the labels that each got.

#25692 Fix leak in the events listener storage
  nucleus/core/kernel/src/main/java/org/glassfish/kernel/event/EventsImpl.java
  nucleus/core/kernel/src/main/java/org/glassfish/kernel/event/OSGiAwareEventsImpl.java
Labels: bug

#25681 Update MicroProfile REST Client to 4.0
  appserver/distributions/glassfish/src/main/patches/microprofile-rest-client-api/META-INF/MANIFEST.MF
  appserver/pom.xml
  appserver/tests/tck/microprofile/rest-client/pom.xml
  appserver/tests/tck/microprofile/rest-client/src/test/java/org/glassfish/microprofile/rest/client/tck/RestClientArquillianExtension.java
  appserver/tests/tck/microprofile/rest-client/src/test/java/org/glassfish/microprofile/rest/client/tck/client/BeansXmlTransformer.java
  appserver/tests/tck/microprofile/rest-client/src/test/java/org/glassfish/microprofile/rest/client/tck/client/WireMockLibraryIncluder.java
  appserver/tests/tck/microprofile/rest-client/src/test/resources/beans.xml
  appserver/tests/tck/microprofile/rest-client/tck-suite.xml
  appserver/tests/tck/pom.xml
Labels: component upgrade

#25680 Simplify and refactor the GlassFish upgrade guide
  docs/ha-administration-guide/src/main/asciidoc/preface.adoc
  docs/ha-administration-guide/src/main/asciidoc/title.adoc
  docs/upgrade-guide/src/main/asciidoc/appendix.adoc
  docs/upgrade-guide/src/main/asciidoc/loe.adoc
  docs/upgrade-guide/src/main/asciidoc/lot.adoc
  docs/upgrade-guide/src/main/asciidoc/preface.adoc
  docs/upgrade-guide/src/main/asciidoc/title.adoc
  docs/upgrade-guide/src/main/asciidoc/upgrade-compatibility-issues.adoc
  docs/upgrade-guide/src/main/asciidoc/upgrading-legacy-installation.adoc
Labels: Documentation

#25707 Upgrade command-security-maven-plugin to support build on Java 25
  nucleus/parent/pom.xml
Labels: build and test improvement, jdk25

#25710 Upgrade easymock to run tests on Java 25
  nucleus/parent/pom.xml
Labels: build and test improvement

#25717 Add release profile to pom
  pom.xml
Labels: build and test improvement
