Repository eclipse-ee4j/glassfish, pull requests merged in 2025-01, with the labels that each got.

#25320 Integrate Jersey 3.1.10
  nucleus/parent/pom.xml
Labels: component upgrade, ee10-component

#25307 Mask secrets in CommandInvokedEvent and Command logger
  appserver/admingui/common/src/main/java/org/glassfish/admingui/common/util/RestUtil.java
  appserver/itest-tools/src/main/java/org/glassfish/main/itest/tools/GlassFishTestEnvironment.java
  appserver/itest-tools/src/main/java/org/glassfish/main/itest/tools/asadmin/Asadmin.java
  appserver/tests/extras/command-logger/src/test/java/org/glassfish/main/test/extras/commandlogger/CommandLoggerITest.java
  nucleus/common/common-util/src/main/java/org/glassfish/common/util/Constants.java
  nucleus/common/glassfish-api/pom.xml
  nucleus/common/glassfish-api/src/main/java/org/glassfish/api/admin/ParameterMap.java
  nucleus/common/glassfish-api/src/test/java/org/glassfish/api/admin/ParameterMapTest.java
  nucleus/common/internal-api/src/main/java/org/glassfish/internal/api/events/CommandInvokedEvent.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/AdminAdapter.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/CommandRunnerExecutionContext.java
  nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/CommandRunnerImpl.java
Labels: security fix

#25326 Fixed the wrong project id in Jenkinsfile. #25322
  Jenkinsfile
Labels: build and test improvement

#25331 Add space before backtick to restore formatting
  docs/security-guide/src/main/asciidoc/administrative-security.adoc
Labels: Documentation

#25332 Drop case for specific user.name
  appserver/tests/appserv-tests/devtests/admin/cli/src/admin/AdminBaseDevTest.java
  appserver/tests/quicklook/utils/src/com/sun/appserv/test/AdminBaseDevTest.java
  appserver/tests/v2-tests/appserv-tests/devtests/ee/admin/mbeanapi/deployment/com/sun/enterprise/admin/mbeanapi/deployment/DeploymentTestsUI.java
Labels: code cleaning

#25345 Integrate JLine 3.28.0
  nucleus/parent/pom.xml
Labels: component upgrade

#25348 Use maven with `--no-transfer-progress` in workflow
  .github/workflows/build-windows.yml
Labels: build and test improvement

#25352 Integrate JSch 0.2.23
  nucleus/parent/pom.xml
Labels: component upgrade

#25351 Integrate JUnit 5.11.4
  nucleus/parent/pom.xml
Labels: build and test improvement

#25354 Improve HTTP admin login flow
  nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/GenericAdminAuthenticator.java
Labels: security fix, code cleaning

#25355 AdminMain - don't drop causes from logs
  nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/AdminMain.java
Labels: bug
